// Text pages: How to play and controls, and About Konane (verified facts only; museum-label tone).
// Split into short, single-concept pages (usually one sentence, occasionally a clause) so every
// page still fits the reader card at the top text-size step (300%). A page's `title` is optional:
// only the first page of a section carries one, continuation pages carry none. A page that also
// carries a title, `demo` or `stones` illustration gets an even shorter sentence, since that art
// eats into the same fixed-height reader card.
export const HELP_PAGES = [
  { title: 'The goal', demo: { cells: ['B', 'W', '.', 'W', '.'], hop: [0, [1, 3], 4] },
    body: ['Black and white stones fill the slab.'] },
  { body: ['Each turn you JUMP one of your stones over a touching enemy stone into the empty square right behind it.'] },
  { body: ['The stone you jumped is removed.'] },
  { body: ['You may keep hopping in the same straight line, and you may stop after any hop.'] },
  { body: ['You cannot turn a corner in one move.'] },
  { body: ['You must jump if you can.'] },
  { body: ['The first player who has no jump left LOSES. There are no draws.'] },
  { title: 'Controls', body: ['TAP a stone of yours to pick it up. Its landing squares glow.'] },
  { body: ['Gold rings mean a single hop; an orange x2 or x3 means a longer jump.'] },
  { body: ['TAP a glowing square to jump there.'] },
  { body: ['TAP the same stone again to put it down.'] },
  { body: ['If you tap a square that is not allowed, the stone tries, comes back, and the message tells you why.'] },
  { body: ['TAP Take back to undo your last move (and the reply).'] },
  { body: ['TAP Hint for a suggestion with its reason.'] },
  { body: ['TAP Menu to leave; an unfinished game is saved.'] },
  { body: ['Keyboard: ARROW keys move the green cursor, SPACE or ENTER is a tap.'] },
  { body: ['ESCAPE is Menu, U is Take back, H is Hint.'] },
  { title: 'The opening', body: ['Black starts by removing one black stone from a corner'] },
  { body: ['or from the middle of the slab.'] },
  { body: ['White then removes a white stone that touches that empty square.'] },
  { body: ['After that Black makes the first jump.'] },
  { body: ['On the title screen, TAP Learn to play for eight short hands-on lessons,'] },
  { body: ['or Daily puzzle for a new position every day where exactly one first jump wins by force.'] },
  { title: 'Auto Play', body: ['TAP Auto Play (free, silent) to watch a full game play itself, one decision at a time.'] },
  { body: ['It pauses so you can work out your own answer, then reveals every legal option and the one it is about to play.'] },
  { body: ['A stepper on that screen sets how long it pauses, from 2 to 10 seconds.'] },
  { title: 'Thinking ahead', body: ['Count jumps.'] },
  { body: ['Each turn, look at how many jumps you would have and how many your opponent would have after your move.'] },
  { body: ['Leaving them with few or none is how games are won.'] },
  { body: ['Sometimes stopping early is a mistake and sometimes going further is.'] },
  { body: ['Try both before you decide.'] },
  { body: ["Hints show the computer's best idea and the jump counts after it, so you can learn why."] },
];
// Exhaustive rules reference (verified against web/src/rules.js, the authoritative rule book). Rulebook tone, not tutorial tone.
// Split into short, single-concept pages (usually one sentence, occasionally a clause) so every
// page still fits the reader card at 300% text size.
export const RULES = [
  { title: 'The papamū and stones', body: ['This version is played on a square board (a papamū) of your choice: 6x6, 8x8 or 10x10 points,'] },
  { body: ['picked on the New game screen before a match starts.'] },
  { body: ['At the start every point is filled in a strict checkerboard pattern:'] },
  { body: ['the point at column x, row y holds a Black stone if x+y is even,'] },
  { body: ['and a White stone if x+y is odd.'] },
  { body: ['No point is empty until the opening removal below.'] },
  { title: 'The opening removal', body: ["Black moves first, and that first move is not a jump:"] },
  { body: ["Black removes one of Black's own stones."] },
  { body: ['Exactly four starting points are offered, whatever the board size —'] },
  { body: ['the two central points and two of the four corners (the top-left and the bottom-right).'] },
  { body: ['No other point can be chosen to open with.'] },
  { body: ['White then removes one White stone that touches the new empty point orthogonally'] },
  { body: ['(up, down, left or right, whichever exist on the board):'] },
  { body: ['two choices after a corner opening, up to four after a centre opening.'] },
  { body: ['From here on Black jumps first, and every later turn is a jump.'] },
  { title: 'The stone', stones: true, body: ['Konane has only one kind of piece: a flat stone, black or white.'] },
  { body: ['It never changes what it can do — there is no promotion, no ranking, no special stone.'] },
  { body: ["A stone's only legal action is to jump: it captures by hopping in a straight line"] },
  { body: ['over one adjacent enemy stone and landing on the empty point immediately beyond it.'] },
  { body: ['A stone that has no jump available simply cannot move at all —'] },
  { body: ['it cannot slide to an empty point any other way.'] },
  { title: 'How a jump works', body: ['A jump travels in a straight line along a row or a column only —'] },
  { body: ['this build never allows a diagonal jump.'] },
  { body: ['To jump, there must be an enemy stone on the very next point in that direction,'] },
  { body: ['and the point immediately beyond that enemy stone must be empty.'] },
  { body: ['The stone hops over the enemy stone onto that empty point,'] },
  { body: ['and the enemy stone is removed from the board at once.'] },
  { body: ['Any of the four directions — up, down, left or right — is equally legal each time you jump;'] },
  { body: ['there is no "forward only" restriction.'] },
  { title: 'Chaining jumps', demo: { cells: ['W', 'B', '.', 'B', '.'], hop: [0, [1, 3], 4] },
    body: ['After landing, the same stone may continue jumping again,'] },
  { body: ['in the SAME straight-line direction,'] },
  { body: ['over the next enemy stone and into the next empty point beyond it,'] },
  { body: ['as many times in a row as the board allows.'] },
  { body: ['You choose, after every hop, whether to keep going or to stop;'] },
  { body: ['stopping after any hop is always allowed,'] },
  { body: ['and each different stopping point counts as a separate move you may pick.'] },
  { title: 'A chain cannot turn', body: ['A chain cannot change direction partway through.'] },
  { body: ['Once a jump starts moving, say, to the right,'] },
  { body: ['every further hop that same turn must keep moving to the right.'] },
  { body: ['Turning a corner takes a whole new turn.'] },
  { title: 'You must jump', body: ['Jumping is mandatory whenever it is possible.'] },
  { body: ['Once the opening removals are done, the only legal moves the game will ever offer are jumps:'] },
  { body: ['there is no way to pass, and no way to move a stone without capturing one.'] },
  { body: ['If, on your turn, none of your stones has a legal jump, you have no legal move at all,'] },
  { body: ['and the game ends immediately — you lose.'] },
  { title: 'Winning', body: ['The game is won the instant a player, on their turn, cannot make a single legal jump.'] },
  { body: ['That player loses; the opponent who forced that position wins.'] },
  { body: ['There is no other way to win, and no way to resign or offer a draw.'] },
  { body: ['The only route to victory is leaving your opponent with no jump left.'] },
  { title: 'No draws', body: ['This build has no drawn or tied games.'] },
  { body: ['Every legal turn removes at least one stone from the board, so the stone count only ever shrinks'] },
  { body: ['and the game is always guaranteed to end, with exactly one side unable to jump.'] },
  { body: ['When a game ends, the reason shown says plainly which side ran out of jumps,'] },
  { body: ['for example "Black has no jump left."'] },
];
// Split into short, single-concept pages (usually one sentence) so every page still fits the
// reader card at 300% text size.
export const ABOUT = [
  { title: 'A game of Hawaii', body: ['Konane (written konane or with a macron, kōnane) is a'] },
  { body: ['traditional strategy game of Hawaii for two players.'] },
  { body: ['It is played on a rectangular grid with black and white pieces.'] },
  { body: ['The playing board is called the papamū.'] },
  { body: ['Each move is a jump that removes the piece jumped, and the player who cannot jump loses.'] },
  { title: 'Stone and coral', body: ['The game is traditionally described as played on a large carved rock'] },
  { body: ['that served as both board and table, with black lava (basalt) pieces and white coral pieces.'] },
  { body: ['The slab, stones and border in this game are drawn to suggest those materials.'] },
  { body: ['The geometric border is inspired by Hawaiian tapa cloth patterns and is decoration only.'] },
  { title: 'Boards and records', body: ['Boards were made in many sizes.'] },
  { body: ['Square boards from 6x6 up to 14x14 are described, as well as rectangles such as 8x9 and 14x17.'] },
  { body: ['Konane appears in written accounts from the voyages of Captain James Cook,'] },
  { body: ['who reached the Hawaiian Islands in 1778 and 1779.'] },
  { body: ['This game offers 6x6, 8x8 and 10x10 boards.'] },
  { title: 'This version', body: ['The opening follows the traditional description:'] },
  { body: ['Black removes a stone from the middle or a corner,'] },
  { body: ['White removes a neighbouring stone, and then the jumping begins.'] },
  { body: ['Everything else here, the lessons, the computer players, Auto Play and the daily puzzle, was made for this game.'] },
];
