// view3d public API. Import from here:  import { createStage, loadHuman, CameraRig } from './vendor3d/index.js';
export { createStage, webglSupported } from './stage.js';
export { loadHuman, loadClips, Human, SKIN_TONES, HAIR_COLORS, defaultAssetBase } from './human.js';
export { CameraRig } from './camera.js';
export { buildClip, ikClip, ease, semanticRot } from './author.js';
export { Clip, Layer, MASKS, sampleClip } from './animation.js';
export { FINGER_POSES } from './rig.js';
export { CLIP_BONES } from './clipcodec.js';
export { addSportClips, addBatClips, addThrowClips, addFieldClips, BAT_LEAD } from './sportclips.js';
export { makeCricketBat, makeBall, makeStumps, makeStick } from './props.js';
export * as THREE from './three.js';
export const VIEW3D_VERSION = '1.5.2';
export { addGloves, addPads, addWhites, addHelmet, addCap, equipBatter } from './equipment.js';
export { buildLodSet, LOD_NAMES, LOD_POLICY, screenHeightPx, pickLod } from './lod.js';
export { createCrowd } from './crowd.js';
export { createBlobShadows } from './blob.js';
export { footQuat, footContactPoint, ankleForBall, solveFootBall, bodyPoint, capsulesOf, penetration, resolvePenetration, rotateBody } from './contact.js';
