// Learn to play: nine short hands-on lessons. Each is a position and one thing to do. Add a lesson = add an object.
//   pits: 14 seed counts (bottom row 0-6 then top row 7-13, see rules.js);  store: [yours, opponent's]  (all together always 70)
//   want: houses that count as doing it right   text: what to do (says the exact command)   done: what to say afterwards
//   hint: shown when they tap a different legal house
// On screen the bottom row runs right to left: house 0 is the far right of your row, house 6 (the guarded one) the far left.
export const LESSONS = [
  { title: 'Sowing seeds', want: [0],
    pits: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], store: [0, 0],
    text: 'Each house starts with five seeds. TAP the glowing house on the far right of your row.',
    done: 'The five seeds were sown one by one into the next five houses, going to the left. That is a move.' },
  { title: 'The way round', want: [4],
    pits: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], store: [0, 0],
    text: 'Seeds travel clockwise. TAP the glowing house, third from the left in your row.',
    done: 'The seeds left your row and went into your opponent’s row, from the top left towards the right. Every move goes this way.' },
  { title: 'Taking seeds', want: [4],
    pits: [5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5], store: [2, 1],
    text: 'Capture a house that ends with two, three or four seeds. TAP the glowing house: its last seed lands on the house holding two.',
    done: 'The last seed made that house three, so you took all three. Landing so a house holds two, three or four is how you capture.',
    hint: 'That one does not capture. Only the glowing house ends on the house holding two seeds.' },
  { title: 'A chain', want: [4],
    pits: [5, 5, 5, 4, 5, 5, 5, 5, 2, 2, 5, 5, 5, 5], store: [4, 3],
    text: 'After a capture, look at the house before it. If that is also two to four, you take it too. TAP the glowing house.',
    done: 'Two houses taken in one move: six seeds. Chains are where games are won.',
    hint: 'Look for the house that reaches the two houses holding two seeds each.' },
  { title: 'The first house', want: [2],
    pits: [5, 5, 5, 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5], store: [2, 2],
    text: 'The first house of each row, where sowing enters it, is safe from a single landing seed. TAP the glowing house: its last seed lands on your opponent’s first house, at the top left.',
    done: 'Their first house now holds two seeds, but a single landing seed never captures a first house.' },
  { title: 'The leftmost house', want: [0, 1, 2, 3, 4, 5],
    pits: [5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5], store: [2, 1],
    text: 'Your leftmost house, on the far left, has two seeds. First TAP it to see the rule. Then TAP any glowing house.',
    done: 'A leftmost house with fewer than three seeds stays put, unless two seeds capture, or it is your only move.',
    hint: 'That house is fine to play, but first TAP the leftmost house on the far left to read the rule.' },
  { title: 'Long sowings', want: [5],
    pits: [2, 3, 1, 6, 2, 15, 1, 1, 0, 5, 5, 5, 5, 5], store: [7, 7],
    text: 'A house with fourteen or more seeds goes once round, then only into your opponent’s row. TAP the glowing house with 15 seeds.',
    done: 'Thirteen seeds went once round. The last two went only into your opponent’s first two houses, which ended at three and two. You took five.' },
  { title: 'You must feed', want: [5, 6],
    pits: [0, 0, 0, 2, 4, 9, 8, 0, 0, 0, 0, 0, 0, 0], store: [23, 24],
    text: 'Your opponent has no seeds, so you must put at least seven seeds on their side if you can. First TAP the house with four seeds to see the rule. Then TAP a glowing house.',
    done: 'With nothing on their side, the opponent must be fed seven seeds or more. If no move can, you must give as many as you can, and if none can reach them the game ends.',
    hint: 'That house cannot give seven seeds. Tap a glowing house.' },
  { title: 'Reaching forty', want: [4],
    pits: [0, 0, 0, 0, 4, 0, 0, 0, 2, 0, 3, 2, 2, 0], store: [37, 20],
    text: 'The first to capture forty seeds wins. You have 37. TAP the glowing house to take three more.',
    done: 'That is forty: you win. If the game ends before anyone reaches forty, each side adds the seeds on its own side, and if nobody has forty it is a draw.' },
];
