// Learn-to-play content as data. Boards are text rows on a 7x7 board: '.' empty, 'A' attacker, 'D' defender, 'K' king.
// Fields: title, text (what to do), done (shown when finished), turn (1 attackers / 2 defenders), rows,
//   want: 'move' | 'capture' | 'refused' | 'win' | 'fork' | 'block'
//   at: optional list of [x, y] target squares (the move must end on one of them) — they are drawn with a marker
//   hint: shown when the player does something else
export const LESSONS = [
  { title: 'Moving', turn: 2, want: 'move', at: [[2, 5]], hint: 'Tap the pale piece, then tap the ringed square.',
    text: 'Every piece slides in a straight line, like a rook: along a row or column, any distance. TAP the pale defender, then TAP the ringed square.',
    done: 'That is a move. Pieces glide over empty squares only.',
    rows: ['.......', '.......', '..D....', '.......', '.......', '.....K.', '.A.....'] },
  { title: 'No jumping', turn: 2, want: 'refused', hint: 'Tap the defender, then tap the square BEHIND the dark piece. Watch what happens.',
    text: 'Pieces never jump. TAP the defender, then TAP the square beyond the dark attacker and see why it is refused.',
    done: 'A piece in the way stops the slide. Every refused move tells you why.',
    rows: ['.......', '.......', '..D....', '.......', '..A....', '.....K.', '.......'] },
  { title: 'Capturing', turn: 2, want: 'capture', at: [[3, 2]], hint: 'Move the top defender down to the ringed square: the attacker is then between two of yours.',
    text: 'Trap an enemy piece between two of yours on a line and it is taken. Slide the top defender to the ringed square.',
    done: 'Captured! Sandwich a piece along a row or a column.',
    rows: ['...D...', '.......', '.DA....', '.......', '.......', '.....K.', '.......'] },
  { title: 'Safe in the middle', turn: 2, want: 'move', at: [[3, 2]], hint: 'Slide the defender down to the ringed square, between the two attackers.',
    text: 'You are never captured by moving in between two enemies. Only the side that moves closes the trap. Slide in between.',
    done: 'Nothing happened: it is safe. They would have to move away and back to take it.',
    rows: ['...D...', '.......', '..A.A..', '.......', '.......', '.....K.', '.......'] },
  { title: 'Corners are hostile', turn: 2, want: 'capture', at: [[0, 2]], hint: 'Slide the defender left along row 3 to the ringed square, next to the attacker.',
    text: 'The four corners count as an enemy to everyone. An attacker beside a corner needs only one piece of yours on the other side.',
    done: 'The corner did the second half of the sandwich. The throne in the centre is hostile to attackers too.',
    rows: ['.......', 'A......', '...D...', '.......', '.......', '.....K.', '.......'] },
  { title: 'The armed king', turn: 2, want: 'capture', at: [[3, 2]], hint: 'Slide the king up to the ringed square: he sandwiches the attacker with the defender.',
    text: 'The king fights too. Slide the king up to the ringed square to sandwich the attacker with your defender.',
    done: 'The king counts as one of your pieces when capturing.',
    rows: ['.......', '.......', '....AD.', '.......', '.......', '...K...', '.......'] },
  { title: 'Escape!', turn: 2, want: 'win', at: [[6, 0], [6, 6]], hint: 'The king is on the right edge. Slide him along the edge to a corner.',
    text: 'The defenders win if the king reaches any corner. The king is on the edge and the way is open. Slide him to a corner.',
    done: 'The king is out. That is how the defenders win.',
    rows: ['.......', '.......', '.......', '......K', '....A..', '.......', '.A.....'] },
  { title: 'Two threats at once', turn: 2, want: 'fork', at: [[6, 3]], hint: 'Slide the king right along the middle row to the edge square with an open line each way.',
    text: 'Threaten two corners at once and the attackers can only block one. Slide the king to the edge, where both directions are open.',
    done: 'A double threat. The attackers can only shut one door. This is the defenders\' best weapon.',
    rows: ['.......', '.A.....', '.......', '...K...', '.......', '..A....', '.......'] },
  { title: 'Take the king', turn: 1, want: 'win', at: [[3, 1]], hint: 'Slide the right-hand attacker left along the top row until it stands beside the king.',
    text: 'You are the attackers now. On this small board an ordinary sandwich takes the king. Slide the right-hand attacker beside him.',
    done: 'The king is taken. (On the big board it takes four attackers around him, or three beside the throne.)',
    rows: ['.......', '.AK..A.', '.......', '.......', '.......', '....D..', '.......'] },
  { title: 'Shut the corner', turn: 1, want: 'block', hint: 'Slide the attacker on row 2 to the right edge, between the king and the corner.',
    text: 'The king has an open line to the top-right corner. Block it: slide the attacker into the way.',
    done: 'Blocked. Attackers win by guarding the corners, then closing the ring.',
    rows: ['.......', '..A....', '......K', '.......', '......A', '.......', '.......'] },
];
