// The heritage page: short, factual, respectful. Anything not certain is left out.
export const ABOUT = {
  title: 'About Congklak',
  parts: [
    ["One game, many names", "This game is called Congklak in Indonesia (also Dakon in Javanese), Congkak in Malaysia,"],
    ["One game, many names (cont.)", "Brunei and Singapore, and Sungka in the Philippines."],
    ["One game, many names (cont.)", "It belongs to the mancala family of sowing games."],
    ["The board", "Boards are carved from wood, often long and shaped like a boat,"],
    ["The board (cont.)", "with two rows of seven cup-shaped houses and a larger storehouse at each end."],
    ["The board (cont.)", "The standard game uses 98 pieces: seven in every house."],
    ["The pieces", "Traditionally the pieces are cowrie shells,"],
    ["The pieces (cont.)", "which is one reason the game’s name has come to mean the shells themselves,"],
    ["The pieces (cont.)", "or small seeds and pebbles."],
    ["The pieces (cont.)", "With no board at all, people have scooped holes in the ground."],
    ["How it is played", "Both players begin at the same moment,"],
    ["How it is played (cont.)", "sowing shells one by one round the board and into their own storehouse only."],
    ["How it is played (cont.)", "Where the last shell lands decides whether you play on, take shells,"],
    ["How it is played (cont.)", "or pass the turn."],
    ["Rounds and burnt houses", "After a round each player refills their houses from their storehouse."],
    ["Rounds and burnt houses (cont.)", "A player who cannot fill a house has it burnt shut,"],
    ["Rounds and burnt houses (cont.)", "and the match goes on until one player has no houses left."],
    ["These rules", "This game follows the common Indonesian and Malay rules with one small simplification:"],
    ["These rules (cont.)", "the player who finishes the opening first moves next."],
    ["These rules (cont.)", "Local rules vary from family to family, and that is part of the fun."],
  ],
};

// Exhaustive rules reference. Every claim here is cross-checked against the actual implementation in
// rules.js (the single source of truth for legality) so this page can never contradict the engine.
// `art` names an illustration drawn with the board's own real pit/store/seed drawing functions
// (art.js) — never a separate simplified icon. Fragmented into short single-thought pages so every
// one fits at the top text-size step (300%); a "(cont.)" title continues the previous page's topic.
export const RULES = [
  { title: "The board", lines: ["Fourteen small houses in all: seven in your own column, the right-hand side you tap,"] },
  { title: "The board (cont.)", lines: ["and seven in your opponent’s column on the left."] },
  { title: "The board (cont.)", lines: ["Each house starts with 7 shells — 98 shells on the board altogether."] },
  { title: "Storehouses", lines: ["Each side also has one storehouse: yours at the bottom of your column,"] },
  { title: "Storehouses (cont.)", lines: ["your opponent’s at the top of theirs. Both storehouses start empty."] },
  { title: "Setup: who moves first", lines: ["To begin,"] },
  { title: "Setup: who moves first (cont.)", lines: ["both players choose one of their own houses and sow it at exactly the same"] },
  { title: "Setup: who moves first (cont.)", lines: ["moment (see “The simultaneous opening”, later on this page list)."] },
  { title: "Setup: who moves first (cont.)", lines: ["Whichever side’s sowing finishes first is the one who moves next; on an exact tie,"] },
  { title: "Setup: who moves first (cont.)", lines: ["player one moves next."] },
  { title: "Setup: see Controls too", lines: ["(This page covers the rules only — see Controls for how to tap and play.)"] },
  { title: "A house (small pit)", lines: ["Each small house holds shells —"], art: "house" },
  { title: "A house (small pit) (cont.)", lines: ["yours or your opponent’s —"] },
  { title: "A house (small pit) (cont.)", lines: ["and can be sown from or sown into."] },
  { title: "Lifting a house", lines: ["Tapping one of your own houses that has shells lifts every shell out of it,"] },
  { title: "Lifting a house (cont.)", lines: ["leaving it empty."] },
  { title: "Sowing from a house", lines: ["It then sows them one by one into the houses ahead: up your own column,"] },
  { title: "Sowing from a house (cont.)", lines: ["across the top, and down your opponent’s column —"] },
  { title: "Sowing from a house (cont.)", lines: ["reaching your own storehouse and starting round the board again if there are enough shells"] },
  { title: "Sowing from a house (cont.)", lines: ["to go that far."] },
  { title: "A house: whose you can tap", lines: ["Both players sow into every house on the board, yours and your opponent’s alike —"] },
  { title: "A house: whose you can tap (cont.)", lines: ["only the two storehouses are private."] },
  { title: "A house: whose you can tap (cont.)", lines: ["You can never tap an empty house, one of your opponent’s houses,"] },
  { title: "A house: whose you can tap (cont.)", lines: ["or a house that has been burnt shut (see later pages)."] },
  { title: "Your storehouse", lines: ["Your storehouse banks your shells."], art: "store" },
  { title: "Your storehouse (cont.)", lines: ["Once a shell lands there it is safe for the"] },
  { title: "Your storehouse (cont.)", lines: ["rest of the round and is never sown again until"] },
  { title: "Your storehouse (cont.)", lines: ["houses are refilled between rounds."] },
  { title: "Playing again", lines: ["If the very last shell you sow lands exactly in your own storehouse,"] },
  { title: "Playing again (cont.)", lines: ["your turn does not pass —"] },
  { title: "Playing again (cont.)", lines: ["you immediately choose another house of yours and sow again."] },
  { title: "Playing again (cont.)", lines: ["A good run can chain several of these “play again” turns in a row."] },
  { title: "Your storehouse: what it skips", lines: ["Sowing always skips over your opponent’s storehouse completely:"] },
  { title: "Your storehouse: what it skips (cont.)", lines: ["no shell of yours is ever dropped there, and landing in it is never possible."] },
  { title: "Relay sowing", lines: ["If the very last shell you sow lands in a house —"] },
  { title: "Relay sowing (cont.)", lines: ["yours or your opponent’s — that already had one or more shells in it,"] },
  { title: "Relay sowing (cont.)", lines: ["you immediately scoop up everything now sitting in that house,"] },
  { title: "Relay sowing (cont.)", lines: ["including the shell you just dropped, and keep sowing onward from there."] },
  { title: "Relay sowing: what it costs", lines: ["This costs nothing extra and does not end your turn:"] },
  { title: "Relay sowing: what it costs (cont.)", lines: ["it is still the same single move."] },
  { title: "Relay sowing: how far it can run", lines: ["A relay can circle the board more than once —"] },
  { title: "Relay sowing: how far it can run (cont.)", lines: ["if it comes back around to the house it started from,"] },
  { title: "Relay sowing: how far it can run (cont.)", lines: ["that house (now empty) simply receives a shell like any other."] },
  { title: "Relay sowing: the safety limit", lines: ["Relays are rare but can run long:"] },
  { title: "Relay sowing: the safety limit (cont.)", lines: ["the longest seen in this game’s own testing is 342 shells sown in one move."] },
  { title: "Relay sowing: the safety limit (cont.)", lines: ["As a safety limit, a single relay is never let run past 500 shells sown."] },
  { title: "The simultaneous opening", lines: ["At the very start of every round,"] },
  { title: "The simultaneous opening (cont.)", lines: ["both players choose one of their own houses and sow at the same moment —"] },
  { title: "The simultaneous opening (cont.)", lines: ["both hands move on the shared board together, one shell at a time,"] },
  { title: "The simultaneous opening (cont.)", lines: ["rather than one player waiting for the other."] },
  { title: "Opening: a shared board", lines: ["Because the board is shared while this happens, it is possible, though unusual,"] },
  { title: "Opening: a shared board (cont.)", lines: ["for one player’s sowing to relay back around to the very house the other player"] },
  { title: "Opening: a shared board (cont.)", lines: ["already emptied a moment before; when that happens,"] },
  { title: "Opening: a shared board (cont.)", lines: ["that side’s turn simply ends there with nothing more to do."] },
  { title: "Opening: who moves next", lines: ["Whichever side’s opening sow finishes first is the one who takes the next ordinary turn."] },
  { title: "Opening: who moves next (cont.)", lines: ["If both finish at exactly the same instant, player one moves next."] },
  { title: "Capturing (the shoot)", lines: ["If the very last shell you sow lands in one"], art: "capture" },
  { title: "Capturing (the shoot) (cont.)", lines: ["of your OWN houses that was completely empty a moment"] },
  { title: "Capturing (the shoot) (cont.)", lines: ["before, look at the house directly opposite it,"] },
  { title: "Capturing (the shoot) (cont.)", lines: ["on your opponent’s side."] },
  { title: "Capturing: the shoot", lines: ["If that opposite house has one or more shells in it, you capture:"] },
  { title: "Capturing: the shoot (cont.)", lines: ["every shell in it, plus the one shell you just dropped,"] },
  { title: "Capturing: the shoot (cont.)", lines: ["all go straight into your own storehouse at once, emptying both houses."] },
  { title: "Capturing: an empty opposite", lines: ["If the opposite house is empty too, nothing is captured —"] },
  { title: "Capturing: an empty opposite (cont.)", lines: ["your dropped shell simply stays put in your own empty house,"] },
  { title: "Capturing: an empty opposite (cont.)", lines: ["and your turn ends as normal."] },
  { title: "Capturing: what never triggers it", lines: ["Landing your last shell in an empty house on your OPPONENT’s side never captures anything,"] },
  { title: "Capturing: what never triggers it (cont.)", lines: ["no matter what: the shell stays there and your turn ends."] },
  { title: "Capturing: what never triggers it (cont.)", lines: ["Only an empty house on your own side can ever trigger a capture."] },
  { title: "Capturing: turns after a capture", lines: ["A capture, or a sow that lands harmlessly in an empty house,"] },
  { title: "Capturing: turns after a capture (cont.)", lines: ["always ends your turn — unlike landing in your own storehouse,"] },
  { title: "Capturing: turns after a capture (cont.)", lines: ["it never earns you another go."] },
  { title: "How a round ends", lines: ["A round ends the instant the player about to move has no shells left in"] },
  { title: "How a round ends (cont.)", lines: ["any of their own houses."] },
  { title: "End of round: sweeping shells home", lines: ["At that moment every remaining shell is swept home at once:"] },
  { title: "End of round: sweeping shells home (cont.)", lines: ["whatever is left in your houses goes into your own storehouse,"] },
  { title: "End of round: sweeping shells home (cont.)", lines: ["and whatever is left in your opponent’s houses goes into theirs."] },
  { title: "End of round: sweeping shells home (cont.)", lines: ["No shell sitting in a house carries over into the next round."] },
  { title: "End of round: who wins it", lines: ["Whoever has more shells in their storehouse"] },
  { title: "End of round: who wins it (cont.)", lines: ["once everything is swept home wins that round;"] },
  { title: "End of round: who wins it (cont.)", lines: ["an exact tie is a tied round."] },
  { title: "Refilling houses, and burnt houses", lines: ["If the match continues into another round,"] },
  { title: "Refilling houses, and burnt houses (cont.)", lines: ["each player refills their own houses back up to 7 shells,"] },
  { title: "Refilling houses, and burnt houses (cont.)", lines: ["spending shells from their own storehouse, filling the house nearest their own storehouse first,"] },
  { title: "Refilling houses, and burnt houses (cont.)", lines: ["then the next, and so on."] },
  { title: "Burnt houses", lines: ["Any house that side cannot refill — because they have run out of open houses,"] },
  { title: "Burnt houses (cont.)", lines: ["or simply do not have 7 shells left to spend —"] },
  { title: "Burnt houses (cont.)", lines: ["is burnt shut for the rest of the match: skipped by every future sow,"] },
  { title: "Burnt houses (cont.)", lines: ["on both sides, and never filled or played again."] },
  { title: "Refilling: leftovers and a failed refill", lines: ["Leftover shells that are not enough to fill a whole house stay banked safely in"] },
  { title: "Refilling: leftovers and a failed refill (cont.)", lines: ["the storehouse."] },
  { title: "Refilling: leftovers and a failed refill (cont.)", lines: ["If a player cannot refill even a single house,"] },
  { title: "Refilling: leftovers and a failed refill (cont.)", lines: ["the match ends immediately in the other player’s favour — no further round is played."] },
  { title: "Winning the match", lines: ["Match length is chosen in Settings: One round (a single round decides everything),"] },
  { title: "Winning the match (cont.)", lines: ["Three rounds (best of three), or Full match (up to nine rounds)."] },
  { title: "Winning the match (cont.)", lines: ["Across a match of more than one round,"] },
  { title: "Winning the match (cont.)", lines: ["whoever has won more rounds by the end wins the match."] },
  { title: "Winning: rounds tied", lines: ["If rounds won are tied after the last round played,"] },
  { title: "Winning: rounds tied (cont.)", lines: ["the match is decided instead by that final round’s own storehouse count;"] },
  { title: "Winning: rounds tied (cont.)", lines: ["if that is tied too, the match is a draw."] },
  { title: "Winning: an early finish", lines: ["A match can also end earlier than its planned length the moment a player is"] },
  { title: "Winning: an early finish (cont.)", lines: ["unable to refill any house after a round (see the previous page) —"] },
  { title: "Winning: an early finish (cont.)", lines: ["the other player wins immediately."] },
];

// The Controls / How to play page. Always the same capital-letter verbs: TAP, HOLD (not used), DRAG (not used).
export const HOWTO = {
  title: 'How to play',
  parts: [
    ["Controls", "TAP a glowing house on your side (the right-hand column) to sow it."],
    ["Controls (cont.)", "That is every control: there is no DRAG and no HOLD."],
    ["Controls (cont.)", "TAP anywhere while shells are moving to fast-forward."],
    ["Buttons", "Undo takes back your last move."],
    ["Buttons (cont.)", "Hint shows a good move and says why (3 per game)."],
    ["Buttons (cont.)", "Menu leaves the game; it is saved."],
    ["Keyboard", "UP and DOWN move along your column, ENTER or SPACE sows, U is Undo,"],
    ["Keyboard (cont.)", "H is Hint, F fast-forwards, ESC opens the menu."],
    ["Sowing", "Lift every shell from one of your houses and drop one in each place ahead,"],
    ["Sowing (cont.)", "going up your column, across the top and down the other."],
    ["Sowing (cont.)", "Your storehouse gets a shell; your opponent’s never does."],
    ["Where the last shell lands", "Your storehouse: play again. A house with shells: scoop them all up and keep sowing."],
    ["Where the last shell lands (cont.)", "Your own empty house: take everything in the house opposite."],
    ["Where the last shell lands (cont.)", "An empty house on the other side: your turn ends."],
    ["Rounds", "A round ends when the player to move has no shells."],
    ["Rounds (cont.)", "Then houses are refilled from the storehouses;"],
    ["Rounds (cont.)", "a player who cannot fill a house has it burnt shut."],
    ["Rounds (cont.)", "Choose one round, three or a full match in Settings."],
  ],
};
