// Exhaustive rules reference for the title-screen "Rules" page. Every claim here is cross-checked
// against the actual implementation in rules.js (the single source of truth for legality), the way
// the engine really plays it - not idealised textbook Toguz Korgool. See design/GDD.md for the
// documented simplifications (the 300-quiet-move fallback; no clock; no opening-move restriction).
// `art` names which real in-game element view.js's renderRules() draws for that page - never a
// separate simplified icon, always the same drawBoard()/drawSeed()/contents() used during play.
//
// One concept per page, kept short: at the largest text-size step (see layout.js TEXT_SCALES) a page
// with several long paragraphs would overflow the reader-card panel, so each original topic that ran
// long is now split across several shorter pages rather than shrinking the font to fit. Re-checked at
// each ceiling raise (130% -> 200% -> 300%, see STATUS.md): pages that read fine at a smaller step
// kept needing further splitting as the font grew, down to short clause-sized fragments at 300%.
export const RULES = [
  { title: 'The board', lines: ['Eighteen pits in a ring: your nine run along the bottom row, numbered 1 to 9 left to right.'] },
  { title: 'The opponent’s row', lines: ['Your opponent’s nine run along the top row, numbered 1 to 9 from their own end.'] },
  { title: 'Reading their numbers', lines: ['That means right to left on your screen.'] },
  { title: 'The pebbles', lines: ['Every pit starts with nine kumalak - one pebble is a kumalak - for 162 in play.'] },
  { title: 'A kazan, or store', lines: ['Each side also has a kazan: a store beside its own row.'] },
  { title: 'What a kazan holds', lines: ['It keeps every pebble that side has won.'] },
  { title: 'Sowing direction', lines: ['Sowing always runs counter-clockwise around the whole board.'] },
  { title: 'The full circuit', lines: ['From pit 1 of your row, through pit 9, into your opponent’s pit 1.'] },
  { title: 'Back to the start', lines: ['On to their pit 9, then back to your pit 1.'] },
  { title: 'Who moves first', lines: ['You, the bottom row, always move first.'] },
  { title: 'No opening restrictions', lines: ['There is no separate opening phase or restricted first move.'] },
  { title: 'Any pit is legal', lines: ['From turn one, any of your nine pits that still holds pebbles is a legal move.'] },
  { title: 'Tapping a pit', art: 'pit', lines: ['One of the eighteen pits on the board - yours or your opponent’s.'] },
  { title: 'What’s in a pit', lines: ['Each pit holds some number of kumalak.'] },
  { title: 'Legal taps only', lines: ['TAP one of your OWN pits that still has pebbles, to sow it.'] },
  { title: 'What can’t be tapped', lines: ['Your opponent’s pits and an empty pit of yours can never be picked.'] },
  { title: 'Tuz pits are off-limits', lines: ['Your opponent’s tuz can never be picked either.'] },
  { title: 'How sowing travels', lines: ['Sowing lifts every pebble out of the chosen pit. If it holds exactly one, that lone pebble simply moves on to the next pit.'] },
  { title: 'Sowing more than one pebble', lines: ['If it holds more than one, the FIRST pebble is dropped straight back into the very pit it came from.'] },
  { title: 'The rest travel on', lines: ['The rest travel on, one per pit, counter-clockwise.'] },
  { title: 'Sowing more than once around', lines: ['A long sow can lap the board more than once.'] },
  { title: 'The lifted pit isn’t skipped', lines: ['The pit just lifted from is not skipped the second time round.'] },
  { title: 'It can be sown into again', lines: ['It can receive a pebble again, like any other pit.'] },
  { title: 'The kazan (store)', art: 'kazan', lines: ['Each player has exactly one kazan, beside their own row.'] },
  { title: 'What it holds', lines: ['It holds every pebble that player has won so far.'] },
  { title: 'How pebbles reach a kazan', lines: ['Pebbles reach a kazan two ways: by capturing a pit,'] },
  { title: 'Or through a tuz', lines: ['or by passing through a tuz on the way round (the next page).'] },
  { title: 'Once in, always in', lines: ['Once a pebble is in a kazan, it never leaves.'] },
  { title: 'Reaching 82 pebbles', lines: ['Whichever player’s kazan reaches 82 or more of the 162 pebbles - more than half - wins the game at once.'] },
  { title: 'The tuz (won pit)', art: 'tuz', lines: ['A tuz is one pit belonging to your opponent that you have won for good.'] },
  { title: 'Won for the rest of the game', lines: ['You keep it for the rest of the game.'] },
  { title: 'How a tuz looks', lines: ['It’s shown here with a small flag planted in your colour.'] },
  { title: 'A tuz pit stays empty', lines: ['A tuz pit always holds zero pebbles.'] },
  { title: 'Where its pebbles go', lines: ['Every pebble that lands in it afterwards, sown by either player,'] },
  { title: 'Straight to the owner', lines: ['goes straight into the tuz owner’s kazan instead of staying in the pit.'] },
  { title: 'A tuz pit can never be sown', lines: ['A tuz pit can never be sown by anyone, by either player.'] },
  { title: 'Always empty', lines: ['It is always empty, so there is never anything in it to lift.'] },
  { title: 'One tuz per player', lines: ['Each player may own at most one tuz at a time, for the whole game.'] },
  { title: 'How a tuz is made', lines: ['Exactly how a pit becomes a tuz is on the next page.'] },
  { title: 'Capturing on an even count', lines: ['If the LAST pebble you sow lands in one of your opponent’s pits'] },
  { title: 'An even count captures', lines: ['and that pit’s new count is EVEN, every pebble sitting in it flies straight to your kazan.'] },
  { title: 'The pit is left empty', lines: ['The pit is left empty.'] },
  { title: 'When nothing is captured', lines: ['Landing your last pebble on an odd count, or in one of your own pits, captures nothing.'] },
  { title: 'The pebbles simply stay', lines: ['The pebbles simply stay where they landed.'] },
  { title: 'Landing in a tuz', lines: ['Landing your last pebble in a tuz - yours or your opponent’s -'] },
  { title: 'Never captures extra', lines: ['never captures anything extra either.'] },
  { title: 'It already went to the kazan', lines: ['A single pebble going into a tuz already went straight to its owner’s kazan'] },
  { title: 'As soon as it landed', lines: ['as it landed.'] },
  { title: 'Making a tuz', lines: ['If the LAST pebble you sow lands in one of your opponent’s pits'] },
  { title: 'On exactly three', lines: ['and that pit’s new count is exactly THREE, it can become your tuz.'] },
  { title: 'Making a tuz: the reward', lines: ['Three pebbles go to your kazan and a flag is planted -'] },
  { title: 'But only if…', lines: ['but only if every one of these conditions is true:'] },
  { title: 'Condition: no tuz yet', lines: ['You do not already own a tuz.'] },
  { title: 'One per player, once', lines: ['One tuz per player, once, for the whole game.'] },
  { title: 'Condition: not their 9th pit', lines: ['It is not your opponent’s own 9th pit -'] },
  { title: 'That pit can never be a tuz', lines: ['that one pit of theirs can never become a tuz.'] },
  { title: 'Condition: a free pit number', lines: ['It does not share the same pit NUMBER as your opponent’s own tuz,'] },
  { title: 'If they already have one', lines: ['if they already have one.'] },
  { title: 'If a condition fails', lines: ['If any of those is not true, landing on three does nothing at all.'] },
  { title: 'The pebbles stay put', lines: ['The three pebbles simply stay put in the pit.'] },
  { title: 'Winning the game', art: 'kazan', lines: ['A player wins the instant their kazan reaches 82 or more of the pebbles.'] },
  { title: 'Checked after every move', lines: ['This is checked after every single move - the game ends immediately.'] },
  { title: 'Why 82', lines: ['162 splits exactly in half at 81.'] },
  { title: 'More than half', lines: ['82 is the smallest total that guarantees strictly more than half:'] },
  { title: 'The other side', lines: ['the other side can then hold at most 80.'] },
  { title: 'Running out of pebbles', lines: ['At the start of a turn, if the player to move'] },
  { title: 'Zero pebbles left', lines: ['has zero pebbles left across all nine of their own pits,'] },
  { title: 'The game ends there', lines: ['the game ends there:'] },
  { title: 'The other side sweeps up', lines: ['the OTHER player sweeps every pebble remaining on their own side'] },
  { title: 'Straight to their kazan', lines: ['straight into their own kazan.'] },
  { title: 'Comparing the kazans', lines: ['The two kazans are then compared:'] },
  { title: 'Who wins', lines: ['whoever holds more of the 162 pebbles wins outright, even without reaching 82.'] },
  { title: 'A draw', lines: ['An exact 81-81 split is a draw.'] },
  { title: 'The 300-move fallback', lines: ['A fallback added for safety, not part of traditional play:'] },
  { title: 'If 300 moves pass quietly', lines: ['if 300 moves pass with neither a capture nor a new tuz by either player,'] },
  { title: 'The same sweep happens', lines: ['the same sweep, then compare, happens instead.'] },
  { title: 'Rarely needed', lines: ['In 3000 simulated random games this was never once needed.'] },
];
