// Learn to play: eight short hands-on lessons. Each is a position and one thing to do. Add a lesson = add an object.
//   pits: 12 seed counts (bottom row 0-5 then top row 6-11, see rules.js);  store: [yours, opponent's]  (all together always 48)
//   want: pits that count as doing it right   text: what to do (says the exact command)   done: what to say afterwards
//   hint: shown when they tap a different legal pit
export const LESSONS = [
  { title: 'Sowing seeds', want: [0],
    pits: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4], store: [0, 0],
    text: 'Each pit starts with four seeds. TAP the glowing pit on the far left of your row.',
    done: 'The four seeds were sown one by one into the next four pits, going to the right. That is a move.' },
  { title: 'The way round', want: [5],
    pits: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4], store: [0, 0],
    text: 'Seeds always travel counter-clockwise. TAP the glowing pit on the far right of your row.',
    done: 'The seeds left your row and went along your opponent’s row, right to left. Every move goes this way.' },
  { title: 'Taking seeds', want: [4],
    pits: [3, 3, 3, 3, 4, 3, 3, 3, 1, 3, 3, 3], store: [6, 7],
    text: 'Capture a pit that ends with 2 or 3 seeds. TAP the glowing pit: its last seed lands on the pit holding one seed.',
    done: 'The last seed made that pit two, so you took it. Landing so a pit becomes 2 or 3 is how you capture.',
    hint: 'That one does not capture. Only the glowing pit ends on the pit holding a single seed.' },
  { title: 'A chain', want: [3],
    pits: [3, 3, 2, 6, 3, 3, 4, 4, 1, 1, 4, 4], store: [5, 5],
    text: 'After a capture, look back at the pit before it. If that is also 2 or 3, you take it too. TAP the glowing pit.',
    done: 'Two pits taken in one move: four seeds. Chains are where games are won.',
    hint: 'Look for the pit that reaches the two lonely single seeds. It has six seeds.' },
  { title: 'Laps', want: [5],
    pits: [2, 3, 1, 4, 2, 13, 1, 1, 3, 4, 2, 4], store: [4, 4],
    text: 'A big pit can go all the way round. TAP the glowing pit with 13 seeds and watch it skip its own pit.',
    done: 'The origin pit is always skipped on a lap, so the last seed landed two pits further than it looks. You took six.' },
  { title: 'You must feed', want: [4, 5],
    pits: [0, 0, 0, 1, 2, 5, 0, 0, 0, 0, 0, 0], store: [19, 21],
    text: 'Your opponent has no seeds, so you must give them some. First TAP the pit with one seed to see the rule. Then TAP a glowing pit.',
    done: 'A move must give an opponent with no seeds something to play. If no move can, the game ends.',
    hint: 'That pit cannot reach the other row. Tap a glowing pit.' },
  { title: 'Grand slam', want: [5],
    pits: [2, 2, 3, 3, 3, 3, 1, 1, 2, 0, 0, 0], store: [14, 14],
    text: 'Taking every seed your opponent has is called a grand slam. TAP the glowing pit and see what happens.',
    done: 'A grand slam is allowed but takes nothing: the opponent must keep something to play with.' },
  { title: 'Reaching 25', want: [5],
    pits: [0, 1, 2, 0, 1, 4, 4, 4, 4, 1, 0, 0], store: [23, 4],
    text: 'The first to capture 25 seeds wins. You have 23. TAP the glowing pit to take the last two.',
    done: 'That is 25: you win. If nobody can reach 25 the seeds on each side go to their owner; 24 each is a draw.' },
];
