// Encounters on the road. Pure data: the engine resolves them (engine.js). Fields:
//   tags   the leg tags this can happen on (any of); legs [min,max] optional; once = at most once per journey
//   art    painted scene: time of day + props the painter knows (art.js)
//   choices[]  label, sub (short note), cost {silver}, req {guards|tongues|customs}, odds {base, mods[]} with win/lose, or just win
//   outcome  {t: text, fx: effects}. fx keys: silver water food str days rep customs tongues camels guards loss(0..1 of cargo value) g{good:n} rival news
// Odds mods: guards, tongues, customs, rep, strength (all documented on the Rules page).

const o = (t, fx = {}) => ({ t, fx });

export const EVENTS = [
  { id: 'gate', tags: ['civil'], legs: [0, 0], once: true, who: 'lu', title: 'The inspector at the gate',
    art: { time: 'dawn', props: ['gate', 'crowd'] },
    text: 'At the last gate of the city, Inspector Lu counts your camels and frowns at your papers. A line of carts waits behind you.',
    choices: [
      { label: 'Show your papers in order', sub: 'Take your time', odds: { base: 0.55, mods: ['customs', 'rep'] },
        win: o('Lu nods, stamps the pass and wishes you a safe road. Word of a careful merchant spreads.', { rep: 5, customs: 1 }),
        lose: o('A missing seal costs you half a morning and a small fine.', { silver: -12, days: 1 }) },
      { label: 'Offer a small gift', sub: '8 silver', cost: { silver: 8 }, win: o('The line moves and your caravan is waved through before noon.', { rep: 2 }) },
      { label: 'Argue the delay', sub: 'Risky for your name', odds: { base: 0.3, mods: ['tongues', 'rep'] },
        win: o('Your argument is sound. Lu apologises and clears you at once.', { rep: 1 }),
        lose: o('Lu remembers your tone. You wait a day and pay a fine.', { silver: -20, days: 1, rep: -4 }) },
    ] },
  { id: 'ferry', tags: ['river'], legs: [1, 1], once: true, who: 'zhao', title: 'The river crossing',
    art: { time: 'day', props: ['river', 'boat'] },
    text: 'The Yellow River runs brown and wide. Zhao, a ferryman, has rafts of inflated sheepskins and a fee for each camel.',
    choices: [
      { label: 'Hire Zhao\'s rafts', sub: '16 silver', cost: { silver: 16 }, odds: { base: 0.88, mods: ['strength'] },
        win: o('The rafts glide across. Zhao teaches you a few words of the river dialect.', { tongues: 0, rep: 2, customs: 1 }),
        lose: o('A camel panics on the raft and a few bales soak through.', { loss: 0.06 }) },
      { label: 'Look for a ford upstream', sub: '+2 days', odds: { base: 0.5, mods: ['guards', 'strength'] },
        win: o('You find shallows and cross for free, though it takes two days.', { days: 2 }),
        lose: o('The ford is deeper than it looks. You lose cargo and a camel is shaken.', { days: 2, loss: 0.15, str: -8 }) },
    ] },
  { id: 'sandstorm', tags: ['desert'], title: 'A wall of dust',
    art: { time: 'dusk', props: ['storm'] },
    text: 'The horizon turns the colour of rust. A sandstorm is rolling across the road, faster than any camel can walk.',
    choices: [
      { label: 'Kneel the camels and shelter', sub: 'Lose a day', odds: { base: 0.75, mods: ['strength', 'guards'] },
        win: o('You wait it out behind the loads. Tired, but whole.', { days: 1, water: -3 }),
        lose: o('The wind tears at the cargo and scatters a few bales before it passes.', { days: 1, water: -3, loss: 0.1 }) },
      { label: 'Push on', sub: 'Risk lost goods', odds: { base: 0.35, mods: ['strength', 'tongues'] },
        win: o('You stay ahead of the worst of it and gain half a day.', { str: -4 }),
        lose: o('The storm catches you in the open. Camels stumble and cargo is lost.', { loss: 0.18, str: -14, water: -5 }) },
      { label: 'Pay your hands to rig a windbreak', sub: '10 silver', cost: { silver: 10 }, win: o('A wall of loads and cloth turns the wind. Nothing is lost.', { days: 1 }) },
    ] },
  { id: 'mirage', tags: ['desert'], title: 'A lake on the horizon',
    art: { time: 'day', props: ['mirage'] },
    text: 'A shining lake lies ahead, with trees at its edge. The camels lean toward it. Your hands say it is a mirage, but they are thirsty.',
    choices: [
      { label: 'Trust the compass and stay on the road', odds: { base: 0.8, mods: ['customs', 'strength'] },
        win: o('The lake fades as you approach. The road leads to a real well by evening.', { water: 4, customs: 1 }),
        lose: o('You doubt yourself and lose half a day wandering before you find the road.', { days: 1, water: -4 }) },
      { label: 'Follow the lake', sub: 'Dangerous', odds: { base: 0.15, mods: ['tongues'] },
        win: o('To your luck, it is a real pool in a hollow. The camels drink.', { water: 12 }),
        lose: o('It was only light on the sand. You lose a day and a great deal of water.', { days: 1, water: -10, str: -8 }) },
    ] },
  { id: 'bandits', tags: ['desert', 'mountain', 'plain'], title: 'Riders on the ridge',
    art: { time: 'day', props: ['riders'] },
    text: 'A line of riders appears on the ridge and a horn sounds. They want a toll, and they would prefer not to fight for it.',
    choices: [
      { label: 'Pay the toll', sub: '40 silver', cost: { silver: 40 }, win: o('The riders take the silver and escort you to the next landmark.', { rep: 1 }) },
      { label: 'Parley in their tongue', sub: 'Depends on languages', req: { tongues: 1 }, odds: { base: 0.3, mods: ['tongues', 'customs', 'rep'] },
        win: o('You share tea and news. Their chief lowers the toll to a token and waves you on.', { silver: -8, rep: 4, customs: 1 }),
        lose: o('Talks stall. In the end you pay the full toll and a gift.', { silver: -55, rep: -2 }) },
      { label: 'Show your guards', sub: 'Needs guards', req: { guards: 1 }, odds: { base: 0.3, mods: ['guards', 'rep'] },
        win: o('Your guards stand firm. The riders judge the price too high and ride away.', { rep: 2 }),
        lose: o('A scuffle, then a hurried bargain. Cargo is lost.', { loss: 0.08, silver: -25, guards: 0 }) },
      { label: 'Take the hidden road', sub: '+2 days', odds: { base: 0.55, mods: ['strength'] },
        win: o('A side track avoids them entirely.', { days: 2, water: -4 }),
        lose: o('The side track was dry and long.', { days: 3, water: -9, str: -8 }) },
    ] },
  { id: 'inn', tags: ['civil', 'plain', 'mountain'], who: 'tamar', title: 'A caravanserai at dusk',
    art: { time: 'dusk', props: ['gate', 'fire'] },
    text: 'Tamar keeps a walled courtyard with stalls for the camels and a warm kitchen. She offers a bed, hot food, and the news of the road for a small price.',
    choices: [
      { label: 'Stay the night and pay in full', sub: '14 silver', cost: { silver: 14 }, win: o('You sleep deeply. The camels are fed and rested. Tamar tells you which cities are short of what.', { str: 10, rep: 2, news: 1 }) },
      { label: 'Share a meal and swap stories', sub: 'Free if you know the customs', req: { customs: 1 }, win: o('You follow every courtesy. Tamar refuses payment and adds a bag of dried fruit.', { rep: 4, customs: 1, food: 6, news: 1 }) },
      { label: 'Move on', win: o('You camp outside the walls and save the silver.', { str: -2 }) },
    ] },
  { id: 'feast', tags: ['desert', 'plain'], who: 'aydar', title: 'Tea at a herder\'s tent',
    art: { time: 'dusk', props: ['tent', 'fire'] },
    text: 'Elder Aydar waves you to his tent. Milk tea, bread and fat sheep are laid out. In return he asks only for news and a gift of cloth or salt.',
    choices: [
      { label: 'Accept and give a gift', sub: '10 silver', cost: { silver: 10 }, win: o('You are fed, watered and sent off with blessings and a full water skin.', { rep: 4, customs: 1, water: 10, food: 5 }) },
      { label: 'Share news of the road', req: { tongues: 2 }, win: o('Aydar listens closely. In return he describes the wells ahead.', { rep: 3, tongues: 1, water: 6, news: 1 }) },
      { label: 'Decline politely', odds: { base: 0.5, mods: ['customs'] }, win: o('He understands. You part on good terms.', {}), lose: o('He is hurt by the refusal. News of it travels.', { rep: -3 }) },
    ] },
  { id: 'rival1', tags: ['desert', 'civil', 'plain', 'mountain'], legs: [1, 4], once: true, who: 'vakhu', rival: 1, title: 'A rival at the well',
    art: { time: 'day', props: ['well', 'caravan2'] },
    text: 'Another caravan is watering at the same well. Its leader, Vakhushu, greets you with a bow and a smile. He also carries silk, and he is also going west.',
    choices: [
      { label: 'Share the well and the news', win: o('You trade stories. Vakhushu tells you prices he has heard of the cities ahead.', { rival: 1, rep: 2, news: 1, water: 3 }) },
      { label: 'Race him to the next market', sub: 'Quick pace today', odds: { base: 0.45, mods: ['strength', 'guards'] },
        win: o('You pull ahead of his dust. He will be one market behind you.', { rival: -1, str: -6, days: -1 }),
        lose: o('Your camels tire. He passes you on the road, grinning.', { rival: -1, str: -10 }) },
      { label: 'Ignore him and water the camels', win: o('You keep to yourself. He shrugs and rides on.', { water: 4 }) },
    ] },
  { id: 'rival2', tags: ['desert', 'civil', 'plain', 'mountain'], legs: [3, 6], once: true, who: 'vakhu', rival: 2, title: 'Vakhushu undercuts you',
    art: { time: 'day', props: ['market', 'caravan2'] },
    text: 'You hear that Vakhushu has been telling buyers your silk is of poor quality. A buyer here is hesitating over your price.',
    choices: [
      { label: 'Show your goods and speak plainly', odds: { base: 0.5, mods: ['tongues', 'rep'] },
        win: o('The buyer inspects your bolts, laughs, and pays well. Vakhushu\'s trick has backfired.', { silver: 45, rep: 5, rival: -1 }),
        lose: o('The buyer is not persuaded and takes a lower offer.', { silver: 5, rep: -2 }) },
      { label: 'Offer to meet Vakhushu and agree on prices', odds: { base: 0.45, mods: ['customs', 'tongues'] },
        win: o('You split the market fairly. Both of you do well for the season.', { silver: 30, rep: 3, rival: 2 }),
        lose: o('He does not turn up. The day is lost.', { days: 1, rival: -1 }) },
      { label: 'Cut your price to win the buyer', sub: '-30 silver', cost: { silver: 30 }, win: o('You keep the buyer\'s trust and the rumour dies.', { rep: 3 }) },
    ] },
  { id: 'rival3', tags: ['desert', 'civil', 'plain', 'mountain'], legs: [5, 7], once: true, who: 'vakhu', rival: 3, title: 'A caravan in trouble',
    art: { time: 'dusk', props: ['sick', 'caravan2'] },
    text: 'On the road you find Vakhushu\'s caravan stopped, a camel lame and his water short. He looks up and says nothing.',
    choices: [
      { label: 'Share water and wait for his camel', sub: '12 water, +1 day', cost: { water: 12 }, win: o('He is stunned. Before you part he gives you a name to ask for in the next city.', { days: 1, rep: 7, rival: 3, customs: 1 }) },
      { label: 'Sell him a camel at a fair price', sub: '+90 silver', win: o('You sell him a camel and he pays without haggling.', { silver: 90, camels: -1, rival: 1, rep: 2 }) },
      { label: 'Ride on', win: o('You do not stop. You make good time, but word of it travels.', { rep: -3, rival: -1 }) },
    ] },
  { id: 'sick', tags: ['desert', 'plain', 'mountain'], who: 'saleh', title: 'A camel stops',
    art: { time: 'day', props: ['sick'] },
    text: 'One of your camels is limping and lowers its head. Saleh, a breeder travelling the other way, looks it over and says it is lame in the foot.',
    choices: [
      { label: 'Rest a day and tend the foot', sub: '+1 day, 6 silver', cost: { silver: 6 }, odds: { base: 0.8, mods: ['customs'] },
        win: o('The camel recovers. Saleh shows you how to bind the foot.', { days: 1, str: 12, customs: 1 }),
        lose: o('It recovers slowly and you lose another half day.', { days: 2, str: 6 }) },
      { label: 'Sell the camel to Saleh', sub: '+40 silver', win: o('You take a fair price and lighten your load.', { silver: 40, camels: -1 }) },
      { label: 'Push on', odds: { base: 0.4, mods: ['strength'] },
        win: o('It walks it off by afternoon.', {}),
        lose: o('The camel collapses and must be left behind.', { camels: -1, str: -5 }) },
    ] },
  { id: 'lost', tags: ['desert'], who: 'anar', title: 'The trail disappears',
    art: { time: 'day', props: ['cairn'] },
    text: 'Wind has erased the track. The cairns are knocked over. Anar, a guide travelling alone, offers to lead you to the next well.',
    choices: [
      { label: 'Hire Anar', sub: '22 silver', cost: { silver: 22 }, win: o('Anar reads the dunes and finds the well by afternoon. He teaches you how to read the cairns.', { water: 5, customs: 1, rep: 1 }) },
      { label: 'Search for the cairns yourself', odds: { base: 0.5, mods: ['customs', 'strength'] },
        win: o('You find the old marks and the road returns.', { customs: 1 }),
        lose: o('You circle for a day before you find the track again.', { days: 1, water: -6 }) },
    ] },
  { id: 'snow', tags: ['mountain'], legs: [4, 4], title: 'Snow on the high pass',
    art: { time: 'day', props: ['snow'] },
    text: 'The track narrows between white slopes. Fresh snow covers the path and the camels breathe hard in the thin air.',
    choices: [
      { label: 'Wait for the weather to clear', sub: '+2 days', odds: { base: 0.85, mods: ['strength'] },
        win: o('The storm passes. You cross at first light.', { days: 2, food: -4 }),
        lose: o('It snows longer than expected.', { days: 3, food: -8 }) },
      { label: 'Cross now in single file', odds: { base: 0.45, mods: ['strength', 'customs'] },
        win: o('Slow, careful steps. You reach the far side safe.', { str: -6 }),
        lose: o('A camel slips. You save the animal but lose cargo down the slope.', { loss: 0.14, str: -12 }) },
      { label: 'Hire local porters', sub: '30 silver', cost: { silver: 30 }, win: o('The porters know every ledge. You cross quickly and safely.', { rep: 1, customs: 1 }) },
    ] },
  { id: 'toll', tags: ['mountain'], who: 'sher', title: 'The toll keeper',
    art: { time: 'day', props: ['gate'] },
    text: 'Captain Sher stands at the narrowest point of the pass with a ledger and a brass scale. Every caravan pays by the load.',
    choices: [
      { label: 'Pay the tariff', sub: '35 silver', cost: { silver: 35 }, win: o('He weighs and notes everything and wishes you luck.', { rep: 1 }) },
      { label: 'Bargain in his tongue', req: { tongues: 2 }, odds: { base: 0.35, mods: ['tongues', 'rep', 'customs'] },
        win: o('Sher likes a trader who speaks plainly. The toll is cut by half.', { silver: -16, rep: 3 }),
        lose: o('He holds to his price and notes that you tried.', { silver: -40 }) },
      { label: 'Offer goods for the toll', win: o('He picks three bolts of silk to cover it.', { loss: 0.05 }) },
    ] },
  { id: 'horsefair', tags: ['mountain', 'plain'], legs: [4, 5], once: true, who: 'bay', title: 'A horse fair in the valley',
    art: { time: 'day', props: ['horses', 'crowd'] },
    text: 'Bay Temir leads out a line of tall, fine-boned horses. Buyers circle with wary looks. He offers you two at a discount if you can speak well of them.',
    choices: [
      { label: 'Buy two horses', sub: '120 silver', cost: { silver: 120 }, win: o('Fine animals, and Bay Temir adds a rope halter each. Horses sell high in the east.', { g: { horse: 2 }, rep: 1 }) },
      { label: 'Learn what makes a good horse', win: o('Bay Temir shows you the signs. You will know a fair price next time.', { customs: 1, tongues: 1 }) },
      { label: 'Move on', win: o('Nothing here is for you today.', {}) },
    ] },
  { id: 'papermill', tags: ['plain', 'civil'], legs: [4, 5], once: true, who: 'ahmad', title: 'The papermaker\'s yard',
    art: { time: 'day', props: ['workshop'] },
    text: 'In a yard by a canal, Ahmad lifts a sieve from a vat of pulp and lays a sheet to dry. Paper made here is cheaper than anything brought from the east.',
    choices: [
      { label: 'Buy a bundle at the workshop price', sub: '60 silver', cost: { silver: 60 }, win: o('You load four reams of fresh paper. Ahmad shows you how to keep it dry on the road.', { g: { paper: 4 }, customs: 1 }) },
      { label: 'Watch the whole process', win: o('From rags to pulp to sheet. Ahmad is pleased by your interest.', { customs: 1, tongues: 1, rep: 1 }) },
    ] },
  { id: 'interpreter', tags: ['civil', 'plain', 'desert'], who: 'lian', title: 'A traveller who speaks everything',
    art: { time: 'day', props: ['market'] },
    text: 'Lian waits at the roadside with a satchel of scrolls. She is looking for a caravan that wants a scribe and translator for a stretch.',
    choices: [
      { label: 'Hire her for the leg', sub: '35 silver', cost: { silver: 35 }, win: o('Her patient lessons, evening after evening, improve your languages.', { tongues: 1, rep: 2 }) },
      { label: 'Trade stories instead', win: o('She shares a handful of phrases for tea.', { customs: 1 }) },
    ] },
  { id: 'wolves', tags: ['mountain', 'desert', 'plain'], title: 'Night watch',
    art: { time: 'night', props: ['fire', 'wolves'] },
    text: 'Wolves howl somewhere beyond the fire. The camels shift and strain at their ropes.',
    choices: [
      { label: 'Set a double watch', sub: 'Needs guards', req: { guards: 1 }, odds: { base: 0.6, mods: ['guards'] },
        win: o('The watch keeps the fires bright. Morning comes with every animal in place.', {}),
        lose: o('A camel breaks loose and takes an hour to catch.', { str: -5 }) },
      { label: 'Keep the fire high and sleep lightly', odds: { base: 0.6, mods: ['strength'] },
        win: o('Nothing comes close.', { str: -2 }),
        lose: o('A rope snaps and a camel bolts. You find it near dawn, but it is frightened.', { str: -9, days: 1 }) },
    ] },
  { id: 'fair', tags: ['civil', 'plain'], title: 'A fair at the crossroads',
    art: { time: 'day', props: ['market', 'crowd'] },
    text: 'The road runs through a fair, with banners and drums. Buyers are gathered from three valleys and prices look good.',
    choices: [
      { label: 'Sell a little of your cargo here', win: o('You sell a handful of bolts at a fair price.', { silver: 70, loss: 0.04 }) },
      { label: 'Join the contest of horsemanship', sub: 'Needs a steady head', odds: { base: 0.35, mods: ['strength', 'rep'] },
        win: o('To your own surprise, you win a ribbon. Merchants remember it.', { rep: 6 }),
        lose: o('You are thrown, to cheers. Your pride is hurt more than you are.', { rep: 1 }) },
      { label: 'Hurry through', win: o('You keep to your schedule.', {}) },
    ] },
  { id: 'heat', tags: ['desert'], title: 'A heat that bends the air',
    art: { time: 'day', props: ['mirage'] },
    text: 'By midday the sand burns the camels\' feet. The hands ask whether to rest through the worst of it.',
    choices: [
      { label: 'Rest through midday and travel at dusk', sub: '+1 day', win: o('You walk from sunset to the small hours under the stars.', { days: 1, str: 4, water: -2 }) },
      { label: 'Keep going', odds: { base: 0.55, mods: ['strength'] },
        win: o('The heat passes. You make good progress.', { str: -4, water: -4 }),
        lose: o('The camels flag and drink too much.', { str: -12, water: -9 }) },
    ] },
  { id: 'flood', tags: ['plain', 'river'], legs: [1, 7], title: 'Water in the dry riverbed',
    art: { time: 'day', props: ['river'] },
    text: 'A distant storm has sent a sudden flood down the dry riverbed ahead. It is brown, loud and rising.',
    choices: [
      { label: 'Wait on high ground', sub: '+1 day', win: o('It drops by the next morning. The camels drink their fill.', { days: 1, water: 8, str: 5 }) },
      { label: 'Cross at the narrowest point', odds: { base: 0.4, mods: ['strength', 'guards'] },
        win: o('You cross fast and keep dry.', { water: 8 }),
        lose: o('The current takes a few bales downstream.', { loss: 0.12, str: -8 }) },
    ] },
  { id: 'mishap', tags: ['civil', 'plain', 'desert'], title: 'A price misheard',
    art: { time: 'day', props: ['market'] },
    text: 'A buyer says a price you did not catch in his language. You nod, and now you are expected to hand over goods for it.',
    choices: [
      { label: 'Ask a bystander to translate', odds: { base: 0.6, mods: ['tongues', 'customs'] },
        win: o('The mistake is cleared up with a laugh and a handshake.', { rep: 2, tongues: 1 }),
        lose: o('The bystander makes it worse. You pay for the confusion.', { silver: -28 }) },
      { label: 'Sell at the offered price anyway', win: o('You sell at a loss but avoid the argument.', { silver: -20, rep: 1 }) },
    ] },
  { id: 'taxman', tags: ['civil'], legs: [0, 1], title: 'The road tax',
    art: { time: 'day', props: ['gate', 'crowd'] },
    text: 'A tax collector at a bridge reads out the tariff. It seems high compared to the goods he lists.',
    choices: [
      { label: 'Pay in full', sub: '30 silver', cost: { silver: 30 }, win: o('Papers stamped, bridge opened.', {}) },
      { label: 'Argue from the tariff list', odds: { base: 0.4, mods: ['customs', 'rep', 'tongues'] },
        win: o('You catch an error in his count. The tax drops by a third.', { silver: -10, rep: 3 }),
        lose: o('He insists. You pay a little more for the argument.', { silver: -38 }) },
    ] },
  { id: 'stars', tags: ['desert', 'mountain'], who: 'nasrin', title: 'Night travel by the stars',
    art: { time: 'night', props: ['stars'] },
    text: 'Nasrin offers to guide you through the cool night hours by the stars, so the camels can rest in the heat of day.',
    choices: [
      { label: 'Travel by night with Nasrin', sub: '12 silver', cost: { silver: 12 }, odds: { base: 0.7, mods: ['customs'] },
        win: o('A night of silver sand under a huge sky. The camels do better in the cool.', { str: 8, water: 5, customs: 1 }),
        lose: o('Cloud hides the stars and you lose your way for an hour.', { days: 1 }) },
      { label: 'Stay on your own schedule', win: o('You thank her and rest as usual.', {}) },
    ] },
  { id: 'welldispute', tags: ['desert'], title: 'Two caravans, one well',
    art: { time: 'day', props: ['well', 'caravan2', 'crowd'] },
    text: 'A herd of camels and a rival crew both arrived at the well at the same time. Voices rise.',
    choices: [
      { label: 'Propose to take turns', odds: { base: 0.55, mods: ['tongues', 'customs', 'rep'] },
        win: o('Everyone waters in order. The other crew gives you a skin of water in thanks.', { rep: 3, water: 6, days: 0 }),
        lose: o('Tempers flare and you wait half a day.', { days: 1 }) },
      { label: 'Push to the front with your guards', req: { guards: 1 }, odds: { base: 0.5, mods: ['guards'] },
        win: o('You fill first. Some there will not forget the manner of it.', { water: 8, rep: -3 }),
        lose: o('Words become shoving. You get little and lose a day.', { days: 1, rep: -4 }) },
    ] },
  { id: 'glassgift', tags: ['plain', 'civil'], legs: [6, 7], once: true, who: 'ibrahim', title: 'The glassblower\'s furnace',
    art: { time: 'dusk', props: ['workshop', 'fire'] },
    text: 'Ibrahim\'s furnace glows in the evening. He blows a bottle so thin that it chimes when tapped. He offers a crate at a good price.',
    choices: [
      { label: 'Buy a crate', sub: '50 silver', cost: { silver: 50 }, win: o('Packed in straw and felt, it rides well. Glass is dear in the far east.', { g: { glass: 3 } }) },
      { label: 'Ask how it is made', win: o('Sand, ash and fire. Ibrahim lets you blow a small cup.', { customs: 1, tongues: 1 }) },
    ] },
  { id: 'wounded', tags: ['desert', 'mountain', 'plain'], who: 'roxana', title: 'A traveller by the road',
    art: { time: 'day', props: ['sick'] },
    text: 'A woman sits by her pack with a swollen ankle. Roxana is a healer returning home to Rayy and her mule has bolted.',
    choices: [
      { label: 'Share your camel and take her along', sub: '+1 day', win: o('She repays you with remedies for the road and a letter to a friend in Rayy.', { days: 1, rep: 5, customs: 1, str: 6 }) },
      { label: 'Leave her water and a blanket', sub: '3 water', cost: { water: 3 }, win: o('A kind gesture. She wishes you a safe journey.', { rep: 2 }) },
      { label: 'Ride on', win: o('You hurry on.', { rep: -2 }) },
    ] },
  { id: 'saltflat', tags: ['desert'], title: 'A white plain',
    art: { time: 'day', props: ['mirage'] },
    text: 'The ground turns white and crackles underfoot. A salt flat. It is easy going, but the glare is fierce and there is no shade.',
    choices: [
      { label: 'Cross it quickly', odds: { base: 0.6, mods: ['strength'] }, win: o('You save half a day on the flat.', { days: -1, water: -4 }), lose: o('The glare and heat sap the camels.', { str: -10, water: -8 }) },
      { label: 'Skirt it along the edge', sub: '+1 day', win: o('Longer, but shade at the edge keeps the camels cool.', { days: 1, str: 3 }) },
    ] },
  { id: 'brokerwarn', tags: ['civil', 'plain'], legs: [7, 7], once: true, who: 'hasan', title: 'A broker meets the caravan',
    art: { time: 'day', props: ['market', 'boat'] },
    text: 'Near Baghdad, Hasan rides out to meet arriving caravans. He offers to arrange buyers for a share of the price.',
    choices: [
      { label: 'Accept his help', sub: 'Pay 4% of cargo', win: o('Hasan finds three buyers before you arrive and prepares the market.', { silver: 40, rep: 3, news: 1 }) },
      { label: 'Find buyers yourself', odds: { base: 0.55, mods: ['tongues', 'rep'] }, win: o('You keep the whole price, and a few friends.', { silver: 70, rep: 2 }), lose: o('It takes time and wits. You get less than Hasan would have found.', { silver: 0, days: 1 }) },
    ] },
  { id: 'mahanadvice', tags: ['civil', 'plain', 'desert'], who: 'mahan', once: true, title: 'A Sogdian merchant\'s advice',
    art: { time: 'dusk', props: ['fire', 'caravan2'] },
    text: 'Mahan, an old Sogdian merchant, invites you to share his fire. He has crossed the road forty times and says the secret is not the goods but who you know.',
    choices: [
      { label: 'Listen and take notes', win: o('He tells you which goods rise or fall in which cities, and how to read a buyer.', { customs: 1, tongues: 1, news: 1, rep: 2 }) },
      { label: 'Trade him a gift for a letter of introduction', sub: '15 silver', cost: { silver: 15 }, win: o('His letter opens doors in the next cities.', { rep: 6 }) },
    ] },
  { id: 'courier', tags: ['civil', 'plain', 'mountain'], who: 'wen', title: 'A courier on a lathered horse',
    art: { time: 'day', props: ['riders', 'gate'] },
    text: 'A rider in official colours reins in beside your caravan. Wen carries sealed letters between relay stations and asks if you will take one more to the next city.',
    choices: [
      { label: 'Carry the letter', sub: 'Small reward', win: o('Wen thanks you gravely, pays a few coins and shares the latest rumours of the road.', { silver: 18, rep: 3, news: 1 }) },
      { label: 'Ask for news in exchange for a meal', sub: '5 water', cost: { water: 5 }, win: o('Over a quick meal Wen reels off the market gossip of three cities.', { news: 1, tongues: 0, customs: 1 }) },
      { label: 'Wave him on', win: o('He gallops ahead in a cloud of dust.', {}) },
    ] },
  { id: 'reeler', tags: ['civil', 'plain'], legs: [0, 1], once: true, who: 'mei', title: 'The silk reeler\'s courtyard',
    art: { time: 'day', props: ['workshop', 'crowd'] },
    text: 'In a courtyard behind a mulberry grove, Mei lifts a cocoon from a steaming basin and draws out a thread as fine as hair. She will sell you bolts straight from her loom.',
    choices: [
      { label: 'Buy three bolts from the loom', sub: '75 silver', cost: { silver: 75 }, win: o('The cloth is smooth and bright. Mei wraps each bolt in paper against the dust.', { g: { silk: 3 }, rep: 1 }) },
      { label: 'Watch her reel the thread', win: o('A single cocoon gives a thread a kilometre long. Mei laughs at your face.', { customs: 1, tongues: 1 }) },
    ] },
  { id: 'dyer', tags: ['plain', 'civil'], legs: [5, 6], once: true, who: 'dilnoza', title: 'Blue hands at the dye vats',
    art: { time: 'day', props: ['workshop', 'market'] },
    text: 'Indigo cloth hangs drying across the lane. Dilnoza says merchants who wear a good colour get a better hearing, and offers to dye your headcloth.',
    choices: [
      { label: 'Have your cloth dyed', sub: '12 silver', cost: { silver: 12 }, odds: { base: 0.8, mods: ['customs'] }, win: o('A deep blue that turns heads in the next market.', { rep: 5 }), lose: o('The colour runs a little, but she lets you keep it for free.', { rep: 2 }) },
      { label: 'Trade stories about the road', win: o('She tells you which merchants pay on time and which do not.', { rep: 2, news: 1 }) },
    ] },
  { id: 'archer', tags: ['mountain', 'desert', 'plain'], who: 'bilge', title: 'A rider who shoots from the saddle',
    art: { time: 'day', props: ['riders', 'horses'] },
    text: 'A rider gallops a wide circle around your caravan, loosing arrows at a post. Bilge pulls up and challenges your guards, or you, to hit it.',
    choices: [
      { label: 'Take the challenge', sub: 'Risk your pride', odds: { base: 0.3, mods: ['strength', 'rep'] }, win: o('Your arrow thuds into the post. Bilge laughs and tells everyone she meets.', { rep: 6 }), lose: o('You miss by a hand. Bilge laughs kindly and rides on.', { rep: 0 }) },
      { label: 'Trade a lesson for a skin of water', sub: '5 water', cost: { water: 5 }, win: o('She shows you how to sit a horse at a gallop, and leaves you a fresh skin of water.', { water: 14, customs: 1 }) },
      { label: 'Applaud and move on', win: o('She bows in the saddle and is gone.', { rep: 1 }) },
    ] },
  { id: 'melons', tags: ['plain', 'civil', 'desert'], legs: [5, 7], once: true, who: 'farid', title: 'Melons by the canal',
    art: { time: 'day', props: ['market', 'river'] },
    text: 'A cart piled with striped melons sits at a canal bridge. Farid cuts one open and offers a slice to each of your crew.',
    choices: [
      { label: 'Buy a cartload for the road', sub: '14 silver', cost: { silver: 14 }, win: o('Sweet and heavy with water. Your crew eats well for days.', { food: 10, water: 4, str: 4 }) },
      { label: 'Share the slice and chat', win: o('Farid tells you about his cousin in the next city who is happy to find you a bed.', { rep: 2, customs: 1 }) },
    ] },
  { id: 'strayCamel', tags: ['desert', 'plain'], who: 'yusuf', title: 'A boy and a stray camel',
    art: { time: 'day', props: ['sick'] },
    text: 'Yusuf, a young camel-driver, has lost his caravan and found a strong camel with no owner. He offers it to you if you take him along to the next town.',
    choices: [
      { label: 'Take them both', sub: 'Needs room to spare', odds: { base: 0.75, mods: ['rep'] }, win: o('The camel is sound and Yusuf proves a fine hand. He leaves at the next town with a glowing report of you.', { camels: 1, rep: 3 }), lose: o('The camel turns out to be lame. Yusuf is sorry, and you give him a ride anyway.', { rep: 2, days: 1 }) },
      { label: 'Give him water and directions', sub: '4 water', cost: { water: 4 }, win: o('He thanks you with a grin and sets off down the road.', { rep: 2 }) },
      { label: 'Wish him luck', win: o('You ride on and he waves until you are out of sight.', {}) },
    ] },
];

export const EVENT_BY_ID = Object.fromEntries(EVENTS.map((e) => [e.id, e]));
