// EVERY name, place, chapter title and line of story text in the game lives in this one module.
// Nothing else in web/src may spell a character or place name: change a name here and the whole
// game follows.

const N = {
  ram: 'Ram',
  sita: 'Sita',
  lakshman: 'Lakshman',
  bharat: 'Bharat',
  hanuman: 'Hanuman',
  ravan: 'Ravan',
  sugriv: 'Sugriv',
  jatayu: 'Jatayu',
  vibhishan: 'Vibhishan',
  janak: 'Janak',
  dasharath: 'Dasharath',
  kaikeyi: 'Kaikeyi',
  shurpanakha: 'Shurpanakha',
  marich: 'Marich',
  surasa: 'Surasa',
  nal: 'Nal',
  neel: 'Neel',
  kumbhakarna: 'Kumbhakarna',
  indrajit: 'Indrajit',
  pushpak: 'Pushpak',
  vanara: 'vanara',
  vanaras: 'vanaras',
  host: "Ravan's host",
  raiders: 'raiders',
};

const P = {
  janakpur: 'Janakpur',
  ayodhya: 'Ayodhya',
  nandigram: 'Nandigram',
  panchavati: 'Panchavati',
  kishkindha: 'Kishkindha',
  sea: 'The Southern Sea',
  lanka: 'Lanka',
  ashokGrove: 'the Ashok grove',
};

const en = {
  title: 'The Road to Lanka',
  tagline: 'An exiled prince. A stolen princess. A leap across the sea.',
  about: 'A retelling of the Ramayana, the great Sanskrit epic attributed to the poet Valmiki, from one of the world\'s oldest storytelling traditions.',
  names: N,
  places: P,

  ui: {
    begin: 'Begin the journey',
    continue: 'Continue',
    chapterWord: 'Chapter',
    road: 'The road',
    about: 'About',
    back: 'Back',
    play: 'Begin',
    next: 'Onward',
    retry: 'Try again',
    toRoad: 'The road',
    replay: 'Play again',
    lost: 'The path is lost',
    lostSub: 'Every storyteller begins the verse again.',
    soundOn: 'Sound on',
    soundOff: 'Sound off',
    motionFull: 'Motion: full',
    motionReduced: 'Motion: reduced',
    locked: 'Finish the chapter before to open this one',
    skip: 'Skip (tester)',
    devNote: 'Tester mode: every chapter open',
    tapToContinue: 'Tap to continue',
    totalStars: 'Stars gathered',
    world: 'The Story & Its World',
    worldNext: 'Next',
    worldPrev: 'Previous',
    didYouKnow: 'Did you know',
    endTitle: 'The journey is told',
    endText: `From ${P.janakpur} to ${P.lanka} and home to ${P.ayodhya}. Walk the road again to gather every star.`,
    demoTitle: 'The road goes on',
    demoText: `The rest of the journey, from ${P.kishkindha} to ${P.lanka} and home, is in the full game on iPhone and Android.`,
    // Auto Play: a free, silent, whole-journey watch-and-learn mode (never touches real progress).
    autoPlay: 'Auto Play — watch and learn',
    autoThink: 'Think: how would you try this one?',
    autoReveal: 'Watching now - here is how it unfolds.',
    autoExit: 'Exit',
    autoPause: 'Pause',
    autoResume: 'Resume',
    autoSkip: 'Skip',
    autoExitMenu: 'Exit to menu',
  },

  // The teaching system. One command vocabulary everywhere: TAP, HOLD, DRAG, RELEASE (capitals in
  // any string are drawn in gold with an icon) and [KEY] tokens (drawn as key caps, browser only).
  // Every command below was read off the chapter's real input code; keep them true to the build.
  howto: {
    title: 'How to play',
    controls: 'Controls',
    watch: 'Watch',
    yourTurn: 'Your turn',
    skip: 'Skip',
    resume: 'Resume',
    paused: 'Paused',
    leave: 'Leave to the road',
    replayDemo: 'How to play',
    keysHead: 'Keyboard (browser only)',
    legendHead: 'The five commands',
    legend: [
      ['TAP', 'Touch the screen once, briefly. With a mouse: click.'],
      ['HOLD', 'Press and keep your finger down. The time is shown where it matters.'],
      ['DRAG', 'Keep your finger down and slide it. The arrow shows which way.'],
      ['RELEASE', 'Lift your finger.'],
      ['[KEY]', 'A key on a keyboard. Only shown in the browser.'],
    ],
    ch: [
      { // 1 bow
        steps: ['HOLD anywhere on the screen for about 1 to 2 seconds. The strength column rises.', 'RELEASE when the level is inside the gold band.'],
        note: 'Do this three times: Lift, Bend, String.',
        short: 'HOLD to gather strength.  RELEASE inside the gold band.',
        kbd: 'Hold [SPACE], then let go of [SPACE].',
        labels: { band: 'Gold band', column: 'Strength' },
      },
      { // 2 exile
        steps: ['HOLD anywhere to walk on.', 'RELEASE beside people who wait with lamps, and stand still for a moment.'],
        note: 'They give their farewell only if you stop.',
        short: 'HOLD to walk.  RELEASE beside the people with lamps.',
        kbd: 'Hold [SPACE] or [→] to walk.',
        labels: { people: 'Farewell', walk: 'Walking' },
      },
      { // 3 forest
        steps: ['TAP a raider to shoot an arrow at it.', 'Tough raiders need 2 TAPS. Never TAP a deer or a bird.'],
        note: 'Five arrows in the quiver; each one returns after a moment.',
        short: 'TAP a raider to shoot it.  Never TAP the deer or birds.',
        kbd: null,
        labels: { raider: 'Raider', flyer: 'Swooping raider', deer: 'Spare it' },
      },
      { // 4 regency
        steps: ['TAP the judgement you choose.'],
        note: 'Each answer moves the kingdom in good order.',
        short: 'TAP the judgement you choose.',
        kbd: '[↑] or [←] picks the upper answer, [↓] or [→] the lower.',
        labels: { pick: 'Your judgement', meter: 'Good order' },
      },
      { // 5 deer
        steps: ['TAP just ahead of the golden deer. Your arrow lands a moment later.', 'Later, TAP the chariot wheel while it glints.'],
        note: 'Three arrows can be in the air at once.',
        short: 'TAP just ahead of the deer.  TAP the wheel that glints.',
        kbd: null,
        labels: { ahead: 'Aim ahead', deer: 'Golden deer', wheel: 'Glinting wheel' },
      },
      { // 6 allies
        steps: ['TAP a band on its ledge to call it to the search.'],
        note: 'Eight calls only. Choose who joins.',
        short: 'TAP a band on its ledge to call it.',
        kbd: null,
        labels: { band: 'A band' },
      },
      { // 7 flight
        steps: ['HOLD a finger on the sky.', ['DRAG up to climb, DRAG down to dive. Hanuman flies to your finger.', 'up'], 'Lift your finger to fly level.'],
        note: 'Ride the wind streams in mid-air for speed.',
        short: 'HOLD and DRAG up or down to steer Hanuman.',
        kbd: 'Hold [↑] to climb, hold [↓] to dive.',
        labels: { wind: 'Wind stream', finger: 'Your finger', hanuman: 'Hanuman' },
      },
      { // 8 night
        steps: ['TAP a patch of shadow on your roof or the roof above.', 'Wait until the lantern light swings away first.'],
        note: 'Being seen four times loses the path.',
        short: 'TAP a shadow to slip to it when the light swings away.',
        kbd: null,
        labels: { shadow: 'Shadow', beam: 'Lantern light' },
      },
      { // 9 burn
        steps: ['TAP for a short leap over a gap.', 'HOLD for a higher leap up to the upper roofs.'],
        note: 'Pass every tower to set it alight.',
        short: 'TAP for a short leap.  HOLD for a high leap.',
        kbd: 'Tap or hold [SPACE] or [↑].',
        labels: { gap: 'Gap', tower: 'Tower', roof: 'Upper roof' },
      },
      { // 10 bridge
        steps: ['TAP a carrier as he leaps overhead to drop his stone.', 'Drop it above the next gap to extend the bridge, or on a finished span to strengthen it.'],
        note: 'Big waves break spans that are not strengthened.',
        short: 'TAP a carrier over the gap to drop his stone.',
        kbd: '[SPACE] drops the stone of the carrier over the next gap.',
        labels: { carrier: 'Carrier', gap: 'Next gap' },
      },
      { // 11 war
        steps: ['TAP a unit card to choose it.', 'TAP a lane to send it up the field. Match the colour of each enemy.', 'Once: TAP the Hanuman card, then TAP a lane.'],
        note: 'In the night flight for the herb: HOLD and DRAG up or down to steer through the clouds.',
        short: 'TAP a unit card, then TAP a lane.',
        kbd: '[1] [2] [3] choose a unit; you still TAP a lane.',
        labels: { cards: 'Unit cards', lane: 'Lane', hanuman: 'Call Hanuman', enemy: 'Enemy colour' },
      },
      { // 12 duel
        steps: [['DRAG back, away from the target.', 'down'], 'HOLD and line up the dotted arc.', 'RELEASE to shoot.'],
        note: 'Start anywhere on the screen; a longer pull shoots harder. Arrows also knock fire-bolts out of the sky.',
        short: 'DRAG back, aim along the dotted arc, RELEASE.',
        kbd: '[←] [→] tilt the aim, [SPACE] shoots.',
        labels: { bow: 'Your bow', arc: 'Dotted arc', head: 'Glinting head', bolt: 'Fire-bolt' },
      },
      { // 13 return
        steps: [['HOLD and DRAG up or down to steer the flying chariot through the lights.', 'up'], 'Later, DRAG across the lamps in the city to light them.'],
        note: 'The lights are gathered by flying through them.',
        short: 'HOLD and DRAG up or down to steer the chariot.',
        kbd: '[↑] [↓] steer the chariot.',
        labels: { light: 'Light', car: 'Chariot', lamp: 'Lamp' },
      },
    ],
  },

  // The Chapter Guide: an additive reference page (title screen and pause menu) that never repeats
  // or overrides howto.ch above - it reuses the same TAP/HOLD/DRAG/RELEASE vocabulary to describe
  // each chapter's real mechanic and how it is actually won or lost, plus the systems that carry
  // across the whole journey. Every line below was read off the chapter's own code, not the GDD.
  rules: {
    title: 'Chapter Guide',
    intro: 'How each of the thirteen chapters actually works, and how it is won or lost. For the exact taps and holds, open Controls; this page is about what they achieve.',
    campaignHead: 'Across the whole journey',
    campaign: [
      { h: 'Stars', t: 'Every chapter can be finished for at least one star. Playing it more precisely, in the way described on its own page below, earns two or three. Your best result for each chapter is kept and totalled on the title screen and the closing page, out of three per chapter.' },
      { h: 'The road opens one step at a time', t: 'Finishing a chapter unlocks the next one on the road below it. A locked chapter cannot be reached early.' },
      { h: 'The allies of Kishkindha', t: 'In the Allies chapter, whichever kind of band you call most - scouts, leapers or strong ones - becomes your chosen ally for the rest of the journey. It shows itself as one lasting edge in the War for Lanka: scouts make Strength regenerate faster, leapers make the Leaper unit cost less Strength, strong ones make the Thrower hit harder.' },
    ],
    ch: [
      { // 1 bow
        mechanic: 'Three stages - Lift, Bend, String. HOLD anywhere to raise the strength column, then RELEASE while it sits inside the gold band.',
        win: 'String all three stages; the great bow always breaks in the end, however many tries it takes.',
        lose: null,
        stars: 'Fewer slips (missing the band, or holding until the column overflows) earn more: 3 stars for at most one slip, 2 for at most three, 1 otherwise.',
      },
      { // 2 exile
        mechanic: 'HOLD to walk the road out of Ayodhya. RELEASE and stand still beside one of five groups waiting with lamps for about a second to receive their farewell.',
        win: 'Reach the far bank of the river and the forest beyond, however many farewells you stopped for.',
        lose: null,
        stars: '3 stars for 4 or 5 farewells received, 2 for 2 or 3, 1 for fewer.',
      },
      { // 3 forest
        mechanic: 'Raiders close in on the ground (runners; tougher brutes need two hits) or swoop from the corners (flyers). TAP one within range to loose an auto-homing arrow from your five-arrow quiver, which refills over time. Never TAP the deer or the passing birds - that counts as harming a creature of the forest.',
        win: "Hold the hermitage until the raiders' waves stop and the last one falls.",
        lose: 'The hermitage\'s calm (starts at 5) runs out - five raiders reaching the hut unstopped.',
        stars: '3 stars for at least 4 calm remaining with no creature harmed, 2 for at least 2 calm, 1 otherwise.',
      },
      { // 4 regency
        mechanic: "TAP the judgement you choose for each of six petitions Bharat hears before Ram's empty throne. Each choice adds a different amount to the kingdom's good order.",
        win: 'Hear all six petitions; the sandals keep the throne in good order however you judge them.',
        lose: null,
        stars: 'Good order out of 12: 3 stars for 10 or more, 2 for 7 or more, 1 otherwise.',
      },
      { // 5 deer
        mechanic: "Chase: TAP just ahead of the bounding golden deer, which hops between three lanes, to land an arrow a moment later - five hits ends the chase, or it simply times out. Later, once Ravan's chariot flees south with Sita, TAP the chariot wheel while it glints so Jatayu's dive strikes it.",
        win: "The sequence always plays through to Jatayu's fall and the chariot's escape - that is the story.",
        lose: null,
        stars: 'Combined deer hits and eagle strikes: 3 stars for 9 or more, 2 for 6 or more, 1 otherwise.',
      },
      { // 6 allies
        mechanic: "After the meeting on the hilltop, TAP a band's ledge as the hillside pans past to call it with a horn. Only 8 horn calls are given for 16 bands of scouts, leapers and strong ones - choose who joins the search.",
        win: 'The pan always reaches the far hillside, however many of your 8 calls you spend.',
        lose: null,
        stars: '3 stars for using all 8 calls, 2 for using 5 or more, 1 otherwise. Whichever kind you called most becomes your ally for the war - see "The allies of Kishkindha" above.',
      },
      { // 7 flight
        mechanic: "HOLD a finger on the sky and DRAG up or down (or hold the arrow keys) to steer Hanuman's height over the sea. Wind streams build speed if you fly through them; Surasa's jaws, the shadow-catcher and the storms all cost speed if you fly too close to them; the golden mountain Mainaka costs speed if you sink into it, but a brush near its peak grants a free boost and forgives one earlier hit.",
        win: "Reach Lanka's shore at the far end of the crossing - the leap always lands.",
        lose: null,
        stars: 'Fewer hits and a faster crossing earn more: 3 stars for at most one hit in under 78 seconds, 2 for at most four hits, 1 otherwise.',
      },
      { // 8 night
        mechanic: 'TAP a shadow patch on your own terrace or the one above it to DASH to it. Guards\' lantern beams sweep the terraces; getting caught mid-dash counts as being seen and sends you back to your last patch.',
        win: 'Reach the topmost terrace and the Ashok grove where Sita is hidden.',
        lose: 'Being seen four times.',
        stars: '3 stars for never being seen, 2 for being seen once, 1 for being seen twice or three times.',
      },
      { // 9 burn
        mechanic: 'An auto-running dash over the rooftops with your tail alight: TAP for a short leap over a gap, HOLD for a higher leap up to the upper roofs. Passing near a tower sets it alight on its own. The fire chasing you gains ground a little every time you fall short of a landing.',
        win: 'Reach the end of the rooftops and leap out over the sea.',
        lose: 'Falling short too many times lets the fire catch up completely.',
        stars: 'Share of towers lit: 3 stars for at least 70%, 2 for at least 40%, 1 otherwise.',
      },
      { // 10 bridge
        mechanic: 'Carriers leap overhead in rhythm; TAP one as he passes over the right spot to drop his stone. A stone on the very next open gap extends the bridge; a stone on a built-but-plain span strengthens it; a stone dropped anywhere else splashes into the sea. Big waves knock one level off any span that is not strengthened.',
        win: "Complete all 14 spans yourself, or let 130 seconds pass: the vanaras will finish the bridge together for you, but that always caps the chapter at 1 star.",
        lose: null,
        stars: 'Finishing it yourself: 3 stars under 75 seconds, 2 under 100 seconds, 1 otherwise. Letting the army finish it for you: always 1 star.',
      },
      { // 11 war
        mechanic: 'TAP a unit card (Leaper, Thrower or Rallyer, each costing its own Strength) then TAP a lane to send it up the field. Each unit beats one raider colour for bonus damage and is preyed on by another; Rallyers also heal nearby allies. Once per chapter, TAP the Hanuman card, then a lane, to sweep it clean. Once the gate is about half broken, the giant Kumbhakarna spawns; felling him opens a HOLD-and-DRAG night flight for the healing herb - dodging the drifting clouds there only changes how much of your line you get back, it cannot fail the chapter.',
        win: "Break the enemy gate's strength to zero.",
        lose: 'Your line (a pool of 8) reaches zero - every raider that reaches your side costs a point, three for the giant.',
        stars: '3 stars for at least 6 of the line remaining, 2 for at least 3, 1 otherwise.',
      },
      { // 12 duel
        mechanic: "DRAG back from anywhere to draw the bow (a dotted arc previews the shot), RELEASE to shoot. Ravan's ten heads keep regrowing; only the one head glinting at that moment can actually be felled - fell ten of them. After Vibhishan's counsel, the finishing shot must strike Ravan's chest while his arms are raised; the same shot while his arms are down only sparks off him. Throughout, his fire-bolts fall on your army's line, but any arrow already in flight that passes near a bolt shoots it down for free.",
        win: "Land the finishing shot on Ravan's chest while his arms are raised.",
        lose: "Your army's resolve (a pool of 8) reaches zero from unshot fire-bolts landing.",
        stars: '3 stars for at least 6 resolve remaining, 2 for at least 3, 1 otherwise.',
      },
      { // 13 return
        mechanic: 'A short reunion plays on its own - TAP or simply wait. Then HOLD and DRAG up or down (or the arrow keys) to fly the chariot Pushpak over every place you once walked, for 30 seconds - the drifting lights gathered here are a keepsake only and never affect your stars. Once the city appears, DRAG across its rooftop lamps to light any within reach.',
        win: 'Light the city\'s lamps until time runs out (about 35 seconds) or every lamp is lit, then watch the crowning.',
        lose: null,
        stars: 'Share of lamps lit: 3 stars for at least 80%, 2 for at least 50%, 1 otherwise.',
      },
    ],
  },

  world: [
    { title: 'A poet\'s epic', text: 'The Ramayana is traditionally attributed to the poet Valmiki and was composed in Sanskrit. Tradition counts about 24,000 verses in seven books.', art: 'poet' },
    { title: 'Where the story walks', text: 'Janakpur lies in present-day Nepal, and Ayodhya in Uttar Pradesh, India. Panchavati is traditionally placed near Nashik, and Kishkindha in the Hampi region of Karnataka.', art: 'map' },
    { title: 'The island and the bridge', text: 'Lanka is traditionally identified with Sri Lanka. A chain of shoals called Adam\'s Bridge, about fifty kilometres long, still links the two coasts, and tradition connects it with the causeway of stones.', art: 'bridge' },
    { title: 'A story that travelled', text: 'The epic spread across Asia and is retold in many forms: the Ramakien of Thailand, the Reamker of Cambodia, the Hikayat Seri Rama of the Malay world, Myanmar\'s Yama Zatdaw and the Lao Phra Lak Phra Lam. Versions are also known in Tibetan and Chinese.', art: 'travel' },
    { title: 'Loved across communities', text: 'It is performed and cherished far beyond its region of origin. In Muslim-majority Indonesia it is part of Javanese and Balinese dance and puppet theatre, and in Buddhist-majority Thailand and Cambodia it is a national tradition, carved and painted in famous galleries such as Angkor Wat.', art: 'travel' },
    { title: 'Shadow theatre', text: 'The epic is one of the great living subjects of shadow-puppet theatre: Indonesian wayang kulit, Thai nang yai and Indian tholu bommalata all tell it with pierced leather figures lit from behind. This game\'s figures are fully painted and lit rather than silhouettes, but they share the same theatrical staging on a glowing backdrop. Wayang was recognised by UNESCO in 2003 as a masterpiece of intangible heritage.', art: 'puppet' },
    { title: 'About this retelling', text: 'This retelling follows Valmiki\'s outline as it is commonly told. Tellings differ from place to place, and every tradition has its own beloved details.', art: 'poet' },
  ],

  chapters: [
    {
      key: 'bow', portrait: 'prince', fact: 'Janakpur lies in present-day Nepal, near the border with India.', place: P.janakpur, title: 'The Great Bow',
      card: `King ${N.janak} of ${P.janakpur} has promised his daughter ${N.sita} to whoever can string the great bow no one has ever lifted. Prince ${N.ram} of ${P.ayodhya} steps forward.`,
      hint: 'Hold to gather strength. Let go inside the gold band.',
      outro: `The bow bends, and breaks with a sound like thunder. ${N.sita} chooses ${N.ram}, and ${P.janakpur} rejoices.`,
      lines: { lift: 'Lift', bend: 'Bend', string: 'String', slipped: 'Steady... again', steady: 'Steady' },
    },
    {
      key: 'exile', portrait: 'prince', fact: 'Ayodhya is a city in Uttar Pradesh, India, on the Sarayu river.', place: P.ayodhya, title: 'The Exile',
      card: `On the eve of ${N.ram}'s crowning, Queen ${N.kaikeyi} claims two boons the king once promised her: the throne for her son ${N.bharat}, and fourteen years of forest exile for ${N.ram}. ${N.ram} accepts without anger.`,
      hint: 'Hold to walk. Pause where the people wait with lamps.',
      outro: `${N.sita} and ${N.lakshman} would not let him go alone. The three cross the river and enter the forest, and ${P.ayodhya} grieves with its king.`,
      lines: {
        gate: `${N.sita} and ${N.lakshman} choose to share the exile.`,
        city: `All ${P.ayodhya} follows them to the edge of the city.`,
        river: 'A boatman carries them over the river.',
        forest: 'Fourteen years begin under the trees.',
        farewell: 'Farewells received',
      },
    },
    {
      key: 'forest', portrait: 'brother', fact: 'Panchavati is traditionally placed beside the Godavari river near Nashik, in Maharashtra.', place: P.panchavati, title: 'The Forest Years',
      card: `Years pass among the forest hermits. At ${P.panchavati}, by the river, the three build a home of leaves. ${N.shurpanakha}, sister of ${N.ravan}, is turned away, and ${N.raiders} come by night for revenge.`,
      hint: 'Tap a raider to loose an arrow. Choose who to stop first. Never harm the deer or the birds.',
      outro: `The ${N.raiders} are driven off. But word of ${P.panchavati}, and of ${N.sita}, reaches the king of ${P.lanka}.`,
      lines: { quiver: 'Quiver', calm: 'Hermitage', spare: 'Spare the creatures of the forest', wave: 'They come again' },
    },
    {
      key: 'regency', portrait: 'regent', place: P.nandigram, title: `${N.bharat}'s Regency`,
      card: `${N.bharat} refuses a throne won by a wrong. He carries ${N.ram}'s sandals home, sets them on the throne, and rules from ${P.nandigram} only as his brother's keeper.`,
      hint: 'Hear each petition. Choose the judgement that keeps the kingdom in good order.',
      outro: `Fourteen years the sandals keep the throne. ${P.ayodhya} waits, in good order, for its prince.`,
      lines: { meter: 'Kingdom in good order' },
      petitions: [
        { who: 'A farmer', text: 'The river took my field this year, and the tax is due.', a: 'Forgive the tax this season', b: 'Collect it; the law is the law', ra: 'He sows again. The granary gains a friend.', rb: 'The law is kept, but a field lies empty.', va: 2, vb: 0 },
        { who: 'Two merchants', text: 'We both claim the same stall by the east gate.', a: 'Hear their neighbours, then decide', b: 'Give it to the elder of the two', ra: 'The truth comes out, and both accept it.', rb: 'It is settled quickly, though one leaves bitter.', va: 2, vb: 1 },
        { who: 'A captain', text: 'The border is quiet. Shall the guard stand down for the harvest?', a: 'Send half home, turn by turn', b: 'Send them all home', ra: 'Fields and walls are both tended.', rb: 'The harvest is rich; the walls stand thin.', va: 2, vb: 1 },
        { who: 'A herdsman', text: 'Wolves are taking sheep from the northern pastures.', a: 'Send the guard to walk the pastures', b: 'Tell him to pen his flock at dusk', ra: 'The flocks are safe, and the herdsmen sleep easy.', rb: 'The flock is safer, but the wolves still prowl.', va: 2, vb: 1 },
        { who: 'A traveller', text: 'My cart broke on the king\'s road, and the toll is due.', a: 'Waive the toll and mend the cart', b: 'The toll is the toll', ra: 'The word spreads that the road is kind.', rb: 'The toll is kept, and the traveller walks on in silence.', va: 2, vb: 0 },
        { who: 'A minister', text: `The people ask that you sit upon the throne itself.`, a: `The throne is ${N.ram}'s. I only keep it.`, b: 'Perhaps, for the sake of order', ra: 'The court bows to the sandals, and is content.', rb: 'The court falls silent, uneasy.', va: 2, vb: 0 },
      ],
    },
    {
      key: 'deer', portrait: 'eagle', place: P.panchavati, title: 'The Golden Deer',
      card: `A deer of living gold appears at ${P.panchavati}; it is ${N.marich}, sent by ${N.ravan}. ${N.sita} asks for it, and ${N.ram} follows it deep into the forest.`,
      hint: 'Tap ahead of the deer to loose an arrow where it will be.',
      outro: `${N.jatayu} gave everything he had. The chariot is gone to the south, and ${N.ram} and ${N.lakshman} begin the long search.`,
      lines: {
        cry: `Struck, ${N.marich} cries out in ${N.ram}'s voice. ${N.lakshman} draws a line around the hut and goes to help.`,
        disguise: `${N.ravan} comes disguised as a wandering hermit, and carries ${N.sita} away in his flying chariot.`,
        eagle: `Old ${N.jatayu}, the great bird who was ${N.dasharath}'s friend, rises to bar the way. Tap the glinting wheel!`,
        strikes: 'Strikes',
      },
    },
    {
      key: 'allies', portrait: 'vking', fact: 'Kishkindha is traditionally identified with the Hampi region of Karnataka, a land of great boulder hills.', place: P.kishkindha, title: 'Allies',
      card: `In the hills of ${P.kishkindha}, ${N.hanuman} brings ${N.ram} to ${N.sugriv}, the exiled king of the ${N.vanaras}. They swear friendship: a kingdom restored for one, a search for ${N.sita} for the other.`,
      hint: 'Tap bands on the hillside to call them. Eight horn calls only: choose who joins.',
      outro: `Search parties go out to every quarter. ${N.hanuman} goes south, carrying ${N.ram}'s ring.`,
      lines: {
        calls: 'Horn calls', scouts: 'Scouts', leapers: 'Leapers', strong: 'Strong ones',
        bonusScouts: 'Scouts lead: the army gathers strength faster in the war.',
        bonusLeapers: 'Leapers lead: leapers cost less in the war.',
        bonusStrong: 'Strong ones lead: boulders hit harder in the war.',
      },
    },
    {
      key: 'flight', portrait: 'swift', fact: 'Lanka is traditionally identified with Sri Lanka. The strait between it and India is roughly fifty kilometres wide at its narrowest.', place: P.sea, title: `${N.hanuman}'s Leap`,
      card: `The sea lies between the searchers and ${P.lanka}. ${N.hanuman}, swiftest of the ${N.vanaras}, climbs the last hill and leaps.`,
      hint: 'Drag to steer. Ride the wind streams for speed. Watch the sea below and the storms above.',
      outro: `Past ${N.surasa}'s jaws, past the mountain that rose to offer rest, past the shadow-catcher in the deep: ${P.lanka}'s golden towers stand ahead.`,
      lines: { speed: 'Speed', toLanka: `To ${P.lanka}`, wind: 'Wind stream', rest: 'The mountain offers rest', jaws: `${N.surasa} rises`, shadow: 'The shadow-catcher', storm: 'Storm', sighted: `${P.lanka} in sight` },
    },
    {
      key: 'night', portrait: 'princess', place: P.lanka, title: `${P.lanka} by Night`,
      card: `Small as a cat in the dark, ${N.hanuman} searches ${P.lanka}'s roofs and gardens for ${N.sita} while the watch goes by with lanterns.`,
      hint: 'Tap a patch of shadow to slip to it. Wait for the lantern light to swing away.',
      outro: `In ${P.ashokGrove} he finds her, unbowed. He gives her ${N.ram}'s ring; she gives him a jewel from her hair to carry back.`,
      lines: { seen: 'Seen', hush: 'Back into the dark...', grove: P.ashokGrove },
    },
    {
      key: 'burn', portrait: 'swift', place: P.lanka, title: `${P.lanka} Burns`,
      card: `${N.hanuman} lets himself be taken before ${N.ravan}, who orders his tail wrapped in cloth and set alight. It is a mistake.`,
      hint: 'Tap to leap; hold for a higher leap to the upper roofs. Pass the towers to set them alight.',
      outro: `${P.lanka} burns behind him. He cools his tail in the sea, and leaps north with news: ${N.sita} is found.`,
      lines: { towers: 'Towers alight', slip: 'A slip! Up again...' },
    },
    {
      key: 'bridge', portrait: 'vking', fact: "A chain of shoals called Adam's Bridge still links India and Sri Lanka. Tradition connects it with the causeway of stones.", place: P.sea, title: 'The Bridge',
      card: `The army reaches the shore. ${N.nal} and ${N.neel} lead the ${N.vanaras} in building a bridge of stones across the sea to ${P.lanka}.`,
      hint: 'Tap a carrier to drop his stone. Fill the gap, or strengthen a span before the wave arrives.',
      outro: `Stone by stone the bridge reaches ${P.lanka}'s shore, and the army crosses.`,
      lines: { spans: 'Spans', wave: 'Wave coming', strong: 'Strengthened', splash: 'Lost to the sea' },
    },
    {
      key: 'war', portrait: 'brother', place: P.lanka, title: `The War for ${P.lanka}`,
      card: `${N.vibhishan}, ${N.ravan}'s own brother, has urged him to return ${N.sita}, been cast out, and joined ${N.ram}. Now the ${N.vanara} army stands before the gates.`,
      hint: 'Choose a unit, then tap a lane. Match the colour on each enemy to beat it.',
      outro: `${N.kumbhakarna} the giant has fallen, and ${N.indrajit} after him. The gate breaks. Only ${N.ravan} remains.`,
      lines: {
        gate: 'Gate', line: 'Our line', energy: 'Strength',
        leaper: 'Leaper', thrower: 'Boulder', rallyer: 'Rallyer', call: `Call ${N.hanuman}`,
        giant: `${N.kumbhakarna} wakes!`,
        herbCard: `A mighty weapon fells ${N.lakshman}. Only a herb from a far northern mountain can wake him before dawn. ${N.hanuman} flies, and, unsure which herb it is, brings the whole mountain.`,
        herbHint: 'Drag to steer clear of the clouds. Dawn is coming!',
        herbDone: `${N.lakshman} rises, healed. The army roars.`,
        dawn: 'Before dawn',
      },
    },
    {
      key: 'duel', portrait: 'tenking', fact: 'In Java, dancers stage episodes of the epic in the Ramayana ballet, performed near the Prambanan complex.', place: P.lanka, title: `${N.ram} and ${N.ravan}`,
      card: `The ten-crowned king of ${P.lanka} rides out himself. Each head that falls grows back. ${N.ram} raises his bow.`,
      hint: 'Drag back to aim, release to shoot. Strike the head that glints, or it grows back.',
      outro: `${N.ravan} falls. ${N.ram} orders him honoured as a great king, and ${N.vibhishan} is crowned in ${P.lanka}.`,
      lines: {
        counsel: `${N.vibhishan}: "His life is hidden at his centre. Aim there when he raises his arms."`,
        resolve: 'The army holds', heads: 'Crowns', now: 'Now!',
      },
    },
    {
      key: 'return', portrait: 'princess', fact: 'The epic is traditionally said to hold about 24,000 verses, in seven books.', place: P.ayodhya, title: 'Reunion and Return',
      card: `The war is over. ${N.sita} is free, and the fourteen years are done.`,
      hint: 'Drag to steer the flying chariot through the drifting lights.',
      outro: `${N.ram} is crowned in ${P.ayodhya}, ${N.sita} beside him, his brothers and ${N.hanuman} at his side. The lamps burn until morning.`,
      lines: {
        reunion: `${N.sita} walks out of ${P.lanka}, free.`,
        chariot: `The flying chariot ${N.pushpak} carries them home over every place they walked.`,
        over: ['The bridge of stones', P.kishkindha, P.panchavati, 'The river', P.ayodhya],
        lamps: `${P.ayodhya} lights a lamp at every door to welcome them home. Sweep across the lamps to light them!`,
        lit: 'Lamps lit',
        crown: `${N.bharat} returns the sandals, and the kingdom.`,
      },
    },
  ],
};

// Every player-facing string lives under a language key. Add a sibling block (for example `zh`) to
// translate; `pick` falls back to English for anything missing.
export const LANGS = { en };
export const pick = (code) => LANGS[code] ?? LANGS.en;
export const T = pick('en');
