// Learn-to-play content as data. Every lesson is a position, one thing to do, and the exact taps that do it.
// Points: index = ring*8 + k (ring 0 outer .. 2 inner; k 0..7 clockwise from the top-left corner).
// Fields: title, text (the instruction, uses the verbs TAP / DRAG), light/dark (points), hand [light, dark], turn,
//   want: 'place' | 'step' | 'fly' | 'mill' | 'win' | 'refused'   what the player must do
//   at: allowed destination points (optional), takeAt: allowed men to take (optional, mill lessons)
//   solve: the taps that complete it (used by the Show me button and by the tests), hint: shown after a wrong try.
export const LESSONS = [
  { title: 'The board', text: 'Twenty-four points, where the lines meet. TAP the glowing point to place your first man.', light: [], dark: [], hand: [9, 9], turn: 0, want: 'place', at: [9], solve: [9], hint: 'TAP the glowing point on the middle square.' },
  { title: 'Make a mill', text: 'Two of your men stand in a row. TAP the glowing point to make three in a row: a mill. Then TAP a glowing enemy man to take it.', light: [0, 1], dark: [11, 20], hand: [7, 7], turn: 0, want: 'mill', at: [2], solve: [2, 20], hint: 'TAP the glowing point at the end of your row.' },
  { title: 'Protected men', text: 'Dark has a mill (top row): those men are protected. Make your mill on the inner square, then take the loose man.', light: [16, 17], dark: [0, 1, 2, 12], hand: [7, 5], turn: 0, want: 'mill', at: [18], takeAt: [12], solve: [18, 12], hint: 'Men in a mill cannot be taken while another man is free. Take the loose man in the lower right.' },
  { title: 'Block their mill', text: 'Dark has two in a row on the top edge. Stop the mill: TAP the glowing point between them and the corner.', light: [10, 18], dark: [0, 1], hand: [7, 7], turn: 0, want: 'place', at: [2], solve: [2], hint: 'The empty point at the top-right corner finishes their row. Place your man there.' },
  { title: 'Slide a man', text: 'Once all nine men are placed, men slide. TAP the man at the top, then TAP the glowing point beside it.', light: [1, 12, 20, 22], dark: [4, 13, 21, 23], hand: [0, 0], turn: 0, want: 'step', at: [2], solve: [1, 2], hint: 'A man slides one step along a line to an empty point. TAP the man at the top middle first.' },
  { title: 'Lines only', text: 'A man moves one point along a line, never over another man. Try to slide the top man two points to the right corner of the middle square.', light: [1, 12, 20, 22], dark: [4, 13, 21, 23], hand: [0, 0], turn: 0, want: 'refused', solve: [1, 10], hint: 'TAP the man at the top, then TAP the corner of the middle square on the right.' },
  { title: 'Close a mill by sliding', text: 'Slide the man from the right side up to the corner to close your top row, then take a man.', light: [0, 1, 3], dark: [12, 13, 20], hand: [0, 0], turn: 0, want: 'mill', at: [2], solve: [3, 2, 20], hint: 'TAP the man on the right side of the outer square, then TAP the empty corner above it.' },
  { title: 'Two threats at once', text: 'Place a man that makes TWO rows of two at once. Dark can only stop one of them.', light: [9, 11], dark: [5, 20], hand: [6, 6], turn: 0, want: 'place', at: [10], solve: [10], hint: 'The middle square top-right corner joins your two men on two different lines.' },
  { title: 'Flying', text: 'With only three men left, a player flies: any man jumps to ANY empty point. Fly a man to close your top row.', light: [1, 2, 17], dark: [10, 13, 19, 21], hand: [0, 0], turn: 0, want: 'mill', at: [0], solve: [17, 0, 10], hint: 'TAP the man on the inner square, then TAP the empty top-left corner.' },
  { title: 'Winning the game', text: 'Dark has only three men. Close your mill and take one: two men left, and you win.', light: [0, 1, 3], dark: [12, 13, 21], hand: [0, 0], turn: 0, want: 'win', at: [2], solve: [3, 2, 12], hint: 'Slide the right-hand man up to the corner, then take any Dark man.' },
];
