// Words shown to players: the heritage page, the controls page. Facts are limited to what public sources
// confirm. Both are paginated - one topic per page, same shape as RULES below (title + lines) - so each
// page stays a single, short, comfortable read at any text-size step (see view.js's drawRefPage()).
// Split fine enough to fit the 300% text-size step: the body-text wrap width is fixed (view.js's
// wrap() call at maxW=600), so the number of *lines* a sentence wraps to is what matters, not word
// count - a sentence that was one short page at 130-200% typically needs 2-3 pages at 300%, because
// each line now holds only a handful of words at an 87px font. Every page below was generated by
// greedily packing the ORIGINAL, un-split source sentences (see git history / the 200% pass) into
// chunks that the game's own wrapLines() measures at <=6 wrapped lines (<=4 for the piece page,
// which has less room below the illustration) at the 300% step, then verified by actually rendering
// and reading every single page (see STATUS.md) - not estimated. A numbered suffix like "(2)" marks
// a page that continues the same sentence/topic as the page before it, split only because the fixed
// wrap width could not fit it on one page as the text got 3x bigger.
export const ABOUT = [
  { title: 'Where it is played', lines: ['Nine Men\'s Morris is one of the most widely played traditional board games in'] },
  { title: 'Where it is played (2)', lines: ['Europe. It is called Muhle ("mill") in German, Moulin in French, and Morris or'] },
  { title: 'Where it is played (3)', lines: ['Merels in English, after the rows of three that give the game its name.'] },
  { title: 'Carved in stone and wood', lines: ['Boards are scratched into cloister seats and steps in medieval abbeys and'] },
  { title: 'Carved in stone and wood (2)', lines: ['cathedrals, including Westminster Abbey and the cathedrals of Canterbury,'] },
  { title: 'Carved in stone and wood (3)', lines: ['Gloucester, Norwich and Salisbury.'] },
  { title: 'The Gokstad ship board', lines: ['A board was also found in the Gokstad ship burial in Norway, from about AD 900.'] },
  { title: 'On the green and in the tavern', lines: ['The game needs only a pattern of lines and eighteen small markers. In England the'] },
  { title: 'On the green and in the tavern (2)', lines: ['board was sometimes cut into turf on a village green: Shakespeare has a character'] },
  { title: 'On the green and in the tavern (3)', lines: ['remark that "the nine men\'s morris is filled up with mud".'] },
  { title: 'A game with a known answer', lines: ['In the 1990s the computer scientist Ralph Gasser searched every position of the'] },
  { title: 'A game with a known answer (2)', lines: ['game and showed that with perfect play by both sides it ends in a draw.'] },
  { title: 'Still won every day', lines: ['People still win it every day, because nobody plays perfectly.'] },
];

export const HOW = [
  { title: 'Goal', lines: ['Reduce the enemy to two men, or leave them with no legal move.'] },
  { title: '1. Placing', lines: ['Light starts. TAP an empty point to place a man.'] },
  { title: '1. Placing: turns', lines: ['Each side places nine, one turn at a time.'] },
  { title: '2. Sliding', lines: ['When all men are placed, TAP one of your men, then TAP a glowing point next to it. You'] },
  { title: '2. Sliding (2)', lines: ['can also DRAG the man there.'] },
  { title: '2. Sliding: dragging', lines: ['Men slide one step along a line.'] },
  { title: 'Mills', lines: ['Three of your men in a row on one line is a mill. Each time you make one, TAP a glowing red'] },
  { title: 'Mills (2)', lines: ['enemy man to take it.'] },
  { title: 'Mills: safety', lines: ['Men in a mill are safe unless all the enemy men are in mills.'] },
  { title: '3. Flying', lines: ['A side with exactly three men left may fly: any man jumps to any empty point.'] },
  { title: 'Draws', lines: ['The same position three times, or fifty moves each with no mill, is a draw.'] },
  { title: 'Buttons', lines: ['Undo takes back your last move. Hint shows a good move and why.'] },
  { title: 'Buttons: keyboard', lines: ['On a keyboard: arrow keys move, Space or Enter is a TAP, U is Undo, H is Hint, Esc is'] },
  { title: 'Buttons: keyboard (2)', lines: ['Menu.'] },
  { title: 'Auto Play', lines: ['On the title screen, TAP Auto Play (free, silent) to watch a full game play itself, one move at'] },
  { title: 'Auto Play (2)', lines: ['a time.'] },
  { title: 'Auto Play (3)', lines: ['It pauses so you can guess the move yourself, then reveals every legal point and the one it chose.'] },
  { title: 'Auto Play (4)', lines: ['A stepper on that screen sets how long it pauses, from 2 to 10 seconds.'] },
];

// Exhaustive rules reference, paginated (Rules button on the title screen). Every claim here is
// cross-checked against the actual implementation in rules.js (the single source of truth for
// legality), so this page can never contradict the engine. `piece: true` marks the one page that
// shows the real in-game man sprite in both colours, drawn with pieces.js's own drawMan() - never a
// separate simplified icon.
export const RULES = [
  { title: 'The board', lines: ['The board has 24 points, laid out as three concentric squares - an outer, a middle'] },
  { title: 'The board (2)', lines: ['and an inner square - joined by four spokes that run from the middle of each side,'] },
  { title: 'The board (3)', lines: ['through all three squares, to the centre.'] },
  { title: 'Setting up', lines: ['Each side has nine men: nine Light and nine Dark. At the very start of the game the board'] },
  { title: 'Setting up (2)', lines: ['is completely empty - every one of the eighteen men begins off the board, in hand.'] },
  { title: 'Turn order', lines: ['Light always moves first. After that, the two sides strictly alternate turns, one'] },
  { title: 'Turn order (2)', lines: ['placement or move per turn, for the whole game.'] },
  { title: 'Turn order: note', lines: ['(This page covers the rules only. See Controls / How to play for taps, drags and'] },
  { title: 'Turn order: note (2)', lines: ['keyboard.)'] },
  { title: 'The man', piece: true, lines: ['There is only one kind of piece in this game - the man'] },
  { title: 'The man (2)', lines: ['- in two colours, Light and Dark. No man is stronger than'] },
  { title: 'The man (3)', lines: ['any other, and nothing is ever promoted.'] },
  { title: 'Placing phase', lines: ['Placing phase: while a side still has men in hand, its turn is spent placing one of them on'] },
  { title: 'Placing phase (2)', lines: ['any empty point of its choice, anywhere on the board.'] },
  { title: 'Sliding', lines: ['Sliding phase: once a side has placed all nine of its men, its men no longer go into hand -'] },
  { title: 'Sliding (2)', lines: ['on its turn it must instead slide one man already on the board to an empty point'] },
  { title: 'Sliding (3)', lines: ['directly next to it along a line. It can never jump to a point that is not adjacent, and never onto'] },
  { title: 'Sliding (4)', lines: ['an occupied point.'] },
  { title: 'Sliding: mixed phases', lines: ['The two sides can be in different phases at the same time - for example one'] },
  { title: 'Sliding: mixed phases (2)', lines: ['side already flying while the other is still sliding, or even still placing.'] },
  { title: 'Flying', lines: ['Flying: the instant a side is left with exactly three men on the board and none left in'] },
  { title: 'Flying (2)', lines: ['hand, that side starts flying - each turn it may move one man to ANY empty point on the'] },
  { title: 'Flying (3)', lines: ['board, not only an adjacent one.'] },
  { title: 'Flying: keeping it', lines: ['It keeps this privilege for as long as it stays at exactly three men (and can lose it again if it'] },
  { title: 'Flying: keeping it (2)', lines: ['is reduced further, at which point the very next mill against it usually ends'] },
  { title: 'Flying: keeping it (3)', lines: ['the game - see Winning).'] },
  { title: 'Mills', lines: ['A mill is three of your own men in a row along one of the board\'s 16 lines - 12 lines run'] },
  { title: 'Mills (2)', lines: ['along the three squares (4 per square) and 4 run along the spokes.'] },
  { title: 'Forming a mill', lines: ['You can form a mill either by placing the third man during the placing phase,'] },
  { title: 'Forming a mill (2)', lines: ['or by sliding or flying a man onto the third point during the moving phase.'] },
  { title: 'Taking a man', lines: ['The instant you form a mill, you immediately remove one enemy man from the board'] },
  { title: 'Taking a man (2)', lines: ['(see the Captures page for which one). A man removed this way is gone for the rest of'] },
  { title: 'Taking a man (3)', lines: ['the game - it does not return to hand.'] },
  { title: 'Remaking a mill', lines: ['A mill can be broken and remade: sliding a man out of a mill and later back into it'] },
  { title: 'Remaking a mill (2)', lines: ['forms the mill again and takes another man each time it closes. There is no limit on how'] },
  { title: 'Remaking a mill (3)', lines: ['many times this can happen.'] },
  { title: 'Double mills', lines: ['If a single move happens to close two mills at once, you still only take one enemy man,'] },
  { title: 'Double mills (2)', lines: ['and you choose which.'] },
  { title: 'Captures', lines: ['Not every enemy man is up for grabs when you form a mill. A man that is currently'] },
  { title: 'Captures (2)', lines: ['part of one of the enemy\'s own mills is protected and cannot be taken.'] },
  { title: 'The one exception', lines: ['The one exception: if every single one of the enemy\'s men is presently sitting'] },
  { title: 'The one exception (2)', lines: ['in a mill, that protection is dropped entirely, and any of its men may be taken.'] },
  { title: 'Choosing which man', lines: ['You choose which eligible man to remove by tapping it; the game will only let you tap'] },
  { title: 'Choosing which man (2)', lines: ['a man the rule above allows.'] },
  { title: 'Winning by reduction', lines: ['A side wins the instant, right after its move, its opponent is left with fewer than three men'] },
  { title: 'Winning by reduction (2)', lines: ['in total - counting both the men still waiting in hand and the men on the board. In'] },
  { title: 'Winning by reduction (3)', lines: ['practice this means the opponent has been reduced to two men or fewer.'] },
  { title: 'Winning: no legal move', lines: ['A side also wins if its opponent has no legal move at all when its turn comes - every'] },
  { title: 'Winning: no legal move (2)', lines: ['one of its men is boxed in with no empty adjacent point to slide to (and it is not flying).'] },
  { title: 'Winning: no legal move (3)', lines: ['This can only arise once the placing phase has ended, since a side that still has'] },
  { title: 'Winning: no legal move (4)', lines: ['men in hand can always place one, and a flying side can always move to any empty'] },
  { title: 'Winning: no legal move (5)', lines: ['point.'] },
  { title: 'Winning ends it at once', lines: ['Either of these ends the game immediately - there is no requirement to also check for a'] },
  { title: 'Winning ends it at once (2)', lines: ['draw once a side has won this way.'] },
  { title: 'Draws', lines: ['A game that nobody has won this way can still end in a draw, but only once the'] },
  { title: 'Draws (2)', lines: ['placing phase is completely finished - both sides\' hands are empty and the game is in'] },
  { title: 'Draws (3)', lines: ['the sliding/flying phase. No draw can be declared while men are still being'] },
  { title: 'Draws (4)', lines: ['placed.'] },
  { title: 'Threefold repetition', lines: ['Threefold repetition: if the exact same position - the same men on the same points'] },
  { title: 'Threefold repetition (2)', lines: ['and the same side to move - occurs three separate times during the moving phase,'] },
  { title: 'Threefold repetition (3)', lines: ['the game is drawn at once.'] },
  { title: 'The 100-ply rule', lines: ['The 100-ply rule: if 100 plies pass in the moving phase - 50 full moves by each side -'] },
  { title: 'The 100-ply rule (2)', lines: ['without either side forming a mill, the game is drawn. Every slide or flight that does not'] },
  { title: 'The 100-ply rule (3)', lines: ['close a mill counts toward this limit; forming a mill resets the count to zero.'] },
];
