// Text for the About, How to Play and Rules pages. Blocks are paginated at draw time (view.js), so the same text
// reflows at every text size (100%-300%). Every rule here was cross-checked against rules.js (the engine).
//
// Block kinds:  { h: 'Heading' }  { p: 'Paragraph' }  { tiles: [spec...], cap: 'caption' }
// Tile specs:   { c: 0..3, n: 1..13 } (0 red, 1 blue, 2 black, 3 yellow), { fake: true }, { okey: true, c, n } (a gold-rimmed wild),
//               { gap: true } leaves a space between groups.
export const ABOUT = [
  { h: 'Okey' },
  { p: 'Okey is a tile rummy game from Turkey, played at tea-house tables and family tables alike, and loved by Turkish communities around the world.' },
  { p: 'Four players sit around a table with 106 tiles. Each deal, a turned-up tile decides which tile is the wild "okey" for that deal only.' },
  { tiles: [{ c: 0, n: 3 }, { c: 0, n: 4 }, { c: 0, n: 5 }, { gap: true }, { c: 1, n: 9 }, { c: 2, n: 9 }, { c: 3, n: 9 }], cap: 'A run and a set: the two shapes you build.' },
  { h: 'This version' },
  { p: 'You sit at the bottom of the table against three computer players, Elif, Mehmet and Deniz. Everything is offline: no accounts, no ads, no betting.' },
  { p: 'Scoring is points only. There are no chips or stakes of any kind.' },
  { p: 'Arrange your tiles on a two-row rack by dragging them, or let the sort helpers and Smart arrange do the tidying for you.' },
  { p: 'Three computer levels (Casual, Club and Master) and an unlimited Hint button that explains its reasoning make it easy to learn and hard to master.' },
  { p: 'Watch & Learn plays a whole deal for you to study: it pauses to let you think, then shows the choices and the move it picks, with the reason.' },
  { h: 'Settings you can change' },
  { p: 'Sound, computer level, match length (1, 3 or 5 deals), the "tell me when I can finish" assist, English or Turkish labels, and text size up to 300%.' },
  { h: 'Words on the table' },
  { p: 'Okey: the wild tile. Gosterge: the indicator tile. Sahte okey: the false okey. Per: a run or set. Cift: a pair. Istaka: the rack.' },
];

export const HOWTO = [
  { h: 'The goal' },
  { p: 'Turn your 14 tiles into complete runs and sets (or seven pairs), then finish by discarding your last tile.' },
  { tiles: [{ c: 2, n: 6 }, { c: 2, n: 7 }, { c: 2, n: 8 }, { gap: true }, { c: 0, n: 11 }, { c: 1, n: 11 }, { c: 3, n: 11 }, { gap: true }, { okey: true, c: 1, n: 4 }, { c: 3, n: 5 }, { c: 3, n: 6 }], cap: 'A run, a set, and a run that uses the gold okey as a wild.' },
  { h: 'Your turn' },
  { p: '1. DRAW one tile: tap the face-down stack in the middle, or tap the top tile of the pile on your LEFT (the tile your left neighbour just threw).' },
  { p: '2. ARRANGE your rack if you like. 3. DISCARD one tile: drag it onto your own pile at the bottom of the table, or tap it and press Discard.' },
  { p: 'You always hold 14 tiles when your turn is over. The player who starts the deal has 15 and begins by discarding.' },
  { h: 'The rack' },
  { p: 'Your rack has two rows. DRAG a tile to any slot: it pushes its neighbours aside or swaps if the row is full. Leave gaps to keep groups apart.' },
  { p: 'A green line under tiles means they already make a valid run or set. The counter shows how many of your 14 tiles are in valid sets.' },
  { p: 'The newest tile you drew has a glow so you can find it.' },
  { h: 'Sort buttons' },
  { p: 'Runs sorts by colour and number. Sets sorts by number. Smart arranges the rack into the best runs and sets it can find and puts loose tiles at the end.' },
  { h: 'Hint' },
  { p: 'Hint is free and unlimited. It marks the best place to draw from or the best tile to discard and says why, so you can learn from it.' },
  { h: 'The gold tile' },
  { p: 'The tile with a gold rim is the okey for this deal, a wild that can stand for any tile. The star tiles are false okeys: they stand for the okey tile itself.' },
  { h: 'Finishing' },
  { p: 'Discard the tile that leaves 14 complete tiles and the deal ends at once. With "tell me when I can finish" on, the game points out the winning tile.' },
  { p: 'Finishing by discarding the okey, or with seven pairs, scores double (both together, four times).' },
  { h: 'Watch & Learn' },
  { p: 'From the menu, Watch & Learn plays a full deal with the computer at your seat. It THINKS (your time to guess), REVEALS the options and the move it picks, then plays it.' },
  { p: 'Use the minus and plus buttons for the think time (up to 10 seconds), Speed to go faster, and Pause to freeze everything and pick up exactly where it stopped.' },
  { h: 'Keyboard' },
  { p: 'D draws from the stack and T takes the left pile. Left and Right pick a tile on your rack, and Space discards the picked tile. S is Smart, H is Hint and Esc opens the menu.' },
];

export const RULES = [
  { h: 'The tiles' },
  { p: 'Okey uses 106 tiles: numbers 1 to 13 in four colours (red, blue, black and yellow), two identical copies of each, making 104. Two more tiles are false okeys.' },
  { tiles: [{ c: 0, n: 1 }, { c: 1, n: 1 }, { c: 2, n: 1 }, { c: 3, n: 1 }, { gap: true }, { fake: true }], cap: 'Each colour has its own shape under the number. At right: a false okey.' },
  { h: 'The table' },
  { p: 'Four players sit around the table. Play passes in the order bottom, right, top, left (counter-clockwise). The player before you is on your left.' },
  { h: 'The deal' },
  { p: 'The tiles are shuffled. One numbered tile is turned face up as the INDICATOR (the game never turns up a false okey). The indicator is set aside and is not played.' },
  { p: 'The starting player is dealt 15 tiles, the other three players 14 each. The remaining 48 tiles form the face-down stack. The starter rotates each deal.' },
  { h: 'The okey' },
  { p: 'The okey is the tile of the SAME COLOUR with the number ONE HIGHER than the indicator. If the indicator is a 13, the okey is the 1 of that colour.' },
  { tiles: [{ c: 1, n: 5 }, { gap: true }, { okey: true, c: 1, n: 6 }], cap: 'Indicator blue 5, so blue 6 is the okey this deal.' },
  { p: 'Both tiles with the okey face are WILD: each can stand for any numbered tile you need.' },
  { h: 'False okeys' },
  { p: 'A false okey is NOT wild. It simply wears the face of the okey tile, so it works as that one tile (blue 6 in the example) and nothing else.' },
  { h: 'What you need to win' },
  { p: 'Every one of your 14 tiles must belong to a run or a set (each of three or more tiles), or all 14 must form seven pairs. The 15th tile is the one you discard.' },
  { h: 'Runs' },
  { p: 'A run is three or more tiles of one colour in number order: red 4-5-6 or blue 9-10-11-12.' },
  { p: 'The 1 may follow the 13, so 12-13-1 is a legal run. A run never wraps further: 13-1-2 is not a run.' },
  { tiles: [{ c: 2, n: 4 }, { c: 2, n: 5 }, { c: 2, n: 6 }, { gap: true }, { c: 0, n: 12 }, { c: 0, n: 13 }, { c: 0, n: 1 }], cap: 'Black 4-5-6 and red 12-13-1 are runs.' },
  { h: 'Sets' },
  { p: 'A set is three or four tiles with the SAME number in DIFFERENT colours: red 8, blue 8, black 8. Two tiles of one colour can never share a set, so a set holds at most four tiles.' },
  { tiles: [{ c: 0, n: 8 }, { c: 1, n: 8 }, { c: 2, n: 8 }, { c: 3, n: 8 }], cap: 'A set of four 8s, one of each colour.' },
  { h: 'Using a wild' },
  { p: 'A wild can fill a gap inside a run, extend either end of a run, or be the missing colour in a set. Three wilds on their own also make a legal set.' },
  { tiles: [{ c: 1, n: 3 }, { okey: true, c: 1, n: 6 }, { c: 1, n: 5 }, { gap: true }, { c: 0, n: 9 }, { okey: true, c: 1, n: 6 }, { c: 3, n: 9 }], cap: 'With blue 6 as okey, the gold tile stands for the blue 4, and for a blue or black 9.' },
  { h: 'Seven pairs' },
  { p: 'Instead of runs and sets you may finish with seven pairs. A pair is two identical tiles: the same colour and the same number.' },
  { p: 'A wild can complete any single tile into a pair, and two wilds make a pair together.' },
  { tiles: [{ c: 0, n: 3 }, { c: 0, n: 3 }, { gap: true }, { c: 2, n: 10 }, { c: 2, n: 10 }, { gap: true }, { okey: true, c: 1, n: 6 }, { c: 3, n: 12 }], cap: 'Three pairs; the gold okey completes the yellow 12.' },
  { h: 'Taking a turn' },
  { p: 'On your turn you first DRAW one tile, then DISCARD one tile. The starter of the deal already holds 15 tiles and so only discards on the first turn.' },
  { p: 'You may draw from the face-down stack, or take the top tile of the discard pile of the player before you (on your left).' },
  { p: 'You may not take from any other pile. Once a tile is covered by a newer discard it can no longer be taken.' },
  { p: 'Rearranging your rack costs nothing and takes no turn.' },
  { h: 'Discard piles' },
  { p: 'Each player has their own pile. You discard onto your own pile. The next player in turn order (on your right) may take your discard.' },
  { h: 'Finishing' },
  { p: 'When you discard and the 14 tiles you keep make a complete rack, the deal ends and you win it. You may never finish without discarding.' },
  { p: 'Finishing by discarding the okey as your last tile is worth double. Finishing with seven pairs is worth double. A pairs finish that also discards the okey is worth four times.' },
  { h: 'A drawn deal' },
  { p: 'If the stack is empty when the next player is due to draw, nobody wins the deal and nobody scores. The next deal begins as normal.' },
  { h: 'Scoring' },
  { p: 'Points only. A normal finish is worth 2 points per opponent: the winner gains 6 and each opponent loses 2.' },
  { p: 'Double finishes use 4 points per opponent (the winner gains 12, each opponent loses 4); a pairs finish that also discards the okey uses 8 (the winner gains 24, each opponent loses 8).' },
  { h: 'A match' },
  { p: 'A match is 1, 3 or 5 deals, chosen in Settings. The starter moves one seat on each deal. After the last deal, the highest total wins; equal totals share the win.' },
  { h: 'The computer players' },
  { p: 'Elif, Mehmet and Deniz use the same rules and see only what a person at the table sees: their own tiles, the piles, and the indicator. They never look at the stack or at your rack.' },
  { p: 'Casual makes simple choices and sometimes slips. Club counts which tiles could still complete its groups. Master also reads what the next player has been collecting and weighs every draw.' },
  { h: 'Turkish terms' },
  { p: 'Okey: the wild tile. Gosterge: the indicator. Sahte okey: a false okey. Per: a run or set. Cift: a pair. Istaka: the rack. Tas: a tile.' },
];
