// Words for the How to play, Rules and About pages. Facts only; anything uncertain is left out.
// Each page is { blocks: [{ h?, p }], art? }. `art` names a small illustration the Rules view draws with the game's own
// checker art: 'checkers' (both colours), 'pin' (a pinned checker), 'dice', 'wall' (a row of held points).
// Every rule below was cross-checked against the shipped engine in rules.js (and the scoring/flow in game.js), not against
// textbook rules. Pages are one sentence (or one clause) each so a page always fits the reader card at 300% text size, and a page
// never ends mid-sentence.
export const HOWTO = [
  { blocks: [ { h: 'Controls', p: 'TAP the dice to roll.' } ], art: 'dice' },
  { blocks: [ { p: 'TAP one of your checkers: the points it can reach glow.' } ] },
  { blocks: [ { p: 'TAP a glowing point to move there, or DRAG the checker and drop it there.' } ] },
  { blocks: [ { p: 'TAP Undo to take a move back during your turn.' } ] },
  { blocks: [ { p: 'TAP Hint for a good move and the reason for it. You have three hints in each game.' } ] },
  { blocks: [ { p: 'TAP the round pause button at the top left to freeze the game.' } ] },
  { blocks: [ { h: 'Keyboard', p: 'Space rolls, Left and Right choose, Enter moves, U undoes, H hints, P pauses.' } ] },
  { blocks: [ { h: 'Three games, one board', p: 'Tavli is really three games played in turn on the same board and the same dice.' } ] },
  { blocks: [ { p: 'Portes: hit lone checkers and send them to the bar.' } ] },
  { blocks: [ { p: 'Plakoto: land on a lone checker to pin it under yours.' } ] },
  { blocks: [ { p: 'Fevga: nothing is ever hit. Build walls and keep running.' } ] },
  { blocks: [ { h: 'The goal', p: 'In all three, bring your 15 checkers home and bear them all off first.' } ] },
  { blocks: [ { h: 'A match', p: 'The Greek match plays Portes, then Plakoto, then Fevga, and round again.' } ] },
  { blocks: [ { p: 'A win scores 1 point. A double win scores 2. The first to 5 or 7 points wins the match.' } ] },
  { blocks: [ { h: 'If a move is refused', p: 'The checker shakes and comes back, and a plain sentence says why.' } ] },
  { blocks: [ { h: 'Watch and Learn', p: 'From the menu, the computer plays both sides: it thinks, shows its move, then plays it.' } ] },
  { blocks: [ { p: 'Change how long it thinks with the Think buttons, or pause it at any time.' } ] },
];

export const RULES = [
  // ---- the basics shared by all three games ----
  { blocks: [ { h: 'The board', p: 'The board has 24 points, numbered 1 to 24 on the board itself.' } ] },
  { blocks: [ { p: 'Point 1 is bottom left, point 12 top left, point 13 top right, point 24 bottom right.' } ] },
  { art: 'checkers', blocks: [ { h: 'The checkers', p: 'Each side has 15 identical checkers: yours are the light ones, the rival’s are dark.' } ] },
  { blocks: [ { p: 'Checkers only ever move forward along their own path, never back.' } ] },
  { blocks: [ { h: 'Home', p: 'Your home board is points 1 to 6. In Portes and Plakoto the rival’s is points 19 to 24; in Fevga the rival’s is points 13 to 18.' } ] },
  { art: 'dice', blocks: [ { h: 'The dice', p: 'Each turn you roll two dice.' } ] },
  { blocks: [ { p: 'Each die is a separate move of one checker by that many points.' } ] },
  { blocks: [ { p: 'A double (the same number twice) gives four moves of that number.' } ] },
  { blocks: [ { h: 'Play all you can', p: 'You must play as many dice as any legal order allows.' } ] },
  { blocks: [ { p: 'If only one die can be played, you must play the larger when you can.' } ] },
  { blocks: [ { p: 'If nothing can be played, the turn simply passes.' } ] },
  { blocks: [ { h: 'Who starts', p: 'Each side throws one die, and the higher plays both dice as the first move.' } ] },
  { blocks: [ { p: 'A tie is thrown again, so the very first move is never a double.' } ] },
  { blocks: [ { h: 'Bearing off', p: 'Once all 15 of your checkers are in your home board, you may bear them off.' } ] },
  { blocks: [ { p: 'A die that exactly matches a checker’s distance from off bears that checker off.' } ] },
  { blocks: [ { p: 'A bigger die may bear off a checker from your highest occupied point, and only from there.' } ] },
  { blocks: [ { h: 'Winning a game', p: 'The first side to bear off all 15 checkers wins the game.' } ] },
  { blocks: [ { h: 'Scoring', p: 'A win scores 1 point.' } ] },
  { blocks: [ { p: 'If the loser has not borne off a single checker, it is a double win worth 2 points.' } ] },
  { blocks: [ { p: 'Points are only a score. There is no doubling cube and no stakes of any kind.' } ] },
  { blocks: [ { h: 'The Greek match', p: 'A match plays Portes, then Plakoto, then Fevga, and starts the circle again.' } ] },
  { blocks: [ { p: 'The first side to reach the chosen target, 5 or 7 points, wins the match.' } ] },
  { blocks: [ { p: 'You can also play a single game of just one of the three.' } ] },
  // ---- Portes ----
  { blocks: [ { h: 'Portes: the start', p: 'Portes is the familiar backgammon layout: 2 checkers on your 24-point, 5 on the 13-point, 3 on the 8-point and 5 on the 6-point.' } ] },
  { blocks: [ { p: 'You travel from point 24 down toward point 1. The rival mirrors this and travels from 1 up toward 24.' } ] },
  { blocks: [ { h: 'Portes: landing', p: 'You may land on an empty point, on your own checkers, or on a single enemy checker.' } ] },
  { blocks: [ { p: 'A point held by two or more enemy checkers is blocked: you cannot land there.' } ] },
  { blocks: [ { h: 'Portes: hitting', p: 'Landing on a lone enemy checker hits it, and it goes to the bar.' } ] },
  { blocks: [ { h: 'Portes: the bar', p: 'While you have a checker on the bar, nothing else of yours may move.' } ] },
  { blocks: [ { p: 'A checker on the bar enters with a die of N on point 25 minus N, in the rival’s home board.' } ] },
  { blocks: [ { p: 'If the entry point is blocked, that die cannot be used. If no die can enter, the turn passes.' } ] },
  { blocks: [ { p: 'You cannot bear off while a checker of yours is on the bar.' } ] },
  // ---- Plakoto ----
  { blocks: [ { h: 'Plakoto: the start', p: 'Each side starts with all 15 checkers stacked on one point: yours on point 24, the rival’s on point 1.' } ] },
  { blocks: [ { p: 'Direction and home boards are the same as in Portes.' } ] },
  { blocks: [ { h: 'Plakoto: landing', p: 'You may land on an empty point, on your own checkers, or on a single enemy checker.' } ] },
  { blocks: [ { p: 'A point with two or more enemy checkers on top is blocked.' } ] },
  { art: 'pin', blocks: [ { h: 'Plakoto: pinning', p: 'Nothing is ever hit. Landing on a lone enemy checker pins it: it stays underneath yours.' } ] },
  { blocks: [ { p: 'A pinned checker cannot move at all while the checker above it stays.' } ] },
  { blocks: [ { p: 'A point with a pinned checker is closed to the opponent. You may keep adding your own checkers on top.' } ] },
  { blocks: [ { p: 'When your last checker leaves the point, the pinned checker is free again.' } ] },
  { blocks: [ { p: 'A pinned checker still counts as its owner’s: a side cannot bear off while any of its checkers, a pinned one included, is outside its home board.' } ] },
  { blocks: [ { h: 'Plakoto: a blocked game', p: 'Rarely, both sides have a checker pinned and nothing can move for either side.' } ] },
  { blocks: [ { p: 'Then the game is void: nobody scores, and the game is played again.' } ] },
  // ---- Fevga ----
  { blocks: [ { h: 'Fevga: the start', p: 'Each side starts with all 15 checkers on its head: yours on point 24, the rival’s on point 12.' } ] },
  { blocks: [ { p: 'Both sides travel the same way round the board. You go 24 down to 1. The rival goes 12 down to 1, then 24 down to 13.' } ] },
  { blocks: [ { p: 'Your home is points 1 to 6 and the rival’s home is points 13 to 18.' } ] },
  { blocks: [ { h: 'Fevga: closed points', p: 'Nothing is ever hit. A point with any enemy checker on it is closed to you.' } ] },
  { blocks: [ { p: 'You may land only on empty points or on your own checkers.' } ] },
  { blocks: [ { h: 'Fevga: the head', p: 'Only one checker may leave the head in a turn.' } ] },
  { blocks: [ { p: 'On a side’s very first turn, a double 3 or a double 4 may take two checkers off the head.' } ] },
  { art: 'wall', blocks: [ { h: 'Fevga: the wall rule', p: 'You may not hold six points in a row, which would be an unbreakable wall.' } ] },
  { blocks: [ { p: 'Unless at least one enemy checker has already passed that wall.' } ] },
  { blocks: [ { p: 'A move that would make such a wall is refused, with the reason given.' } ] },
];

export const ABOUT = [
  { blocks: [ { h: 'Tavli', p: 'Tavli is the Greek name for the old tables family of dice-and-checkers games, and for the board itself.' } ] },
  { blocks: [ { p: 'In Greek coffeehouses, the kafeneia, it is played by all ages, for the pleasure of the game.' } ] },
  { blocks: [ { h: 'Three games on one board', p: 'The Greek way is to play three games in turn: Portes, Plakoto and Fevga.' } ] },
  { blocks: [ { p: 'Portes is the form closest to international backgammon, with hitting and the bar.' } ] },
  { blocks: [ { p: 'In Plakoto, a lone checker is not hit but pinned under an opposing checker.' } ] },
  { blocks: [ { p: 'In Fevga, everyone runs the same way round the board, nothing is ever hit, and the game is about walls.' } ] },
  { blocks: [ { h: 'The names', p: 'The names are Greek words: portes means doors, plakoto comes from a verb for pressing down, and fevga from a word for leaving.' } ] },
  { blocks: [ { h: 'A very wide family', p: 'The same family is played far beyond Greece, under other names.' } ] },
  { blocks: [ { p: 'It is tavla in Turkey, tawla in the Arab world, takhteh nard in Persia, and nard or nardy in the Caucasus and Russia.' } ] },
  { blocks: [ { p: 'Fevga is the closest relative of long nard: fifteen checkers from one head, all running one way, nothing hit.' } ] },
  { blocks: [ { p: 'So if you know nard or nardy, Fevga will feel familiar, and Portes is the backgammon you may know.' } ] },
  { blocks: [ { h: 'Old roots', p: 'Roman writers described a dice-and-checkers game called tabula, and the word tabula is the usual source of the names for the board.' } ] },
  { blocks: [ { p: 'Dice and a racing track are far older still: the Royal Game of Ur and Senet were played over four thousand years ago.' } ] },
  { blocks: [ { h: 'This game', p: 'The board here is painted in an Aegean kafeneio style, with a Greek key border, olive wood and island blue.' } ] },
  { blocks: [ { p: 'The computer plays all three games, and Watch and Learn lets you see it think.' } ] },
];
