// Text pages: how to play, controls, a short heritage note, and an exhaustive rules reference.
// Facts only; every claim in `rules` is cross-checked against the real rule book (millfamily.js +
// morabaraba.js), never idealized/textbook Morabaraba or Nine Men's Morris rules.
// Fragmented into short single-thought pages so every one fits at the top text-size step (300%); a
// "(cont.)" title continues the previous page's topic.
export const PAGES = {
  howto: [
    { title: "The board", lines: ["Three squares sit one inside another."] },
    { title: "The board (cont.)", lines: ["Their 24 corners and midpoints are the points where cows stand."] },
    { title: "The board (cont.)", lines: ["Lines join the points around each square, four lines join the middles of the squares,"] },
    { title: "The board (cont.)", lines: ["and four DIAGONAL lines join the corners."] },
    { title: "The board (cont.)", lines: ["Each player has twelve cows. Dark goes first."] },
    { title: "Placing and mills", lines: ["First, players take turns placing one cow each on any empty"] },
    { title: "Placing and mills (cont.)", lines: ["point until all twelve cows of both sides are down."] },
    { title: "Placing and mills (cont.)", lines: ["Three of your cows in one line make a MILL."] },
    { title: "Placing and mills (cont.)", lines: ["Close a mill and you SHOOT one cow of the other side:"] },
    { title: "Placing and mills (cont.)", lines: ["it leaves the board."] },
    { title: "Placing and mills (cont.)", lines: ["A cow standing in a mill is protected,"] },
    { title: "Placing and mills (cont.)", lines: ["unless every cow of that side is in a mill."] },
    { title: "Placing and mills (cont.)", lines: ["One move shoots at most one cow."] },
    { title: "Sliding and flying", lines: ["Then cows slide one step along a line to an empty point, diagonals included."] },
    { title: "Sliding and flying (cont.)", lines: ["Open a mill by sliding a cow out and close it again to shoot again."] },
    { title: "Sliding and flying (cont.)", lines: ["A player with exactly three cows left may FLY:"] },
    { title: "Sliding and flying (cont.)", lines: ["a cow moves to any empty point."] },
    { title: "Winning and draws", lines: ["You win when the other side has fewer than three cows,"] },
    { title: "Winning and draws (cont.)", lines: ["or when it is its turn and none of its cows can move."] },
    { title: "Winning and draws (cont.)", lines: ["A draw: the board is full after placing with no shot,"] },
    { title: "Winning and draws (cont.)", lines: ["the same position comes up three times, or 40 moves pass without a shot."] },
    { title: "Winning and draws (cont.)", lines: ["Rules differ from place to place."] },
    { title: "Winning and draws (cont.)", lines: ["This game shoots while placing, one cow per move, and flies at three."] },
    { title: "Controls", lines: ["PLACING: TAP an empty point."] },
    { title: "Controls (cont.)", lines: ["SLIDING: TAP a cow (its legal points glow), then TAP a glowing point."] },
    { title: "Controls (cont.)", lines: ["Or DRAG the cow and drop it on a point."] },
    { title: "Controls (cont.)", lines: ["SHOOTING: after a mill, TAP a glowing cow."] },
    { title: "Controls (cont.)", lines: ["A refused move tries, comes back, and a message says why."] },
    { title: "Controls (cont.)", lines: ["Take back undoes your last move; Hint shows a good move and why."] },
    { title: "Controls (cont.)", lines: ["Keyboard: arrow keys move the cursor, Space or Enter is a TAP, U takes back,"] },
    { title: "Controls (cont.)", lines: ["H hints, Escape is Menu."] },
    { title: "Auto Play", lines: ["On the title screen, TAP Auto Play (free, silent) to watch a full game play itself,"] },
    { title: "Auto Play (cont.)", lines: ["one move at a time."] },
    { title: "Auto Play (cont.)", lines: ["It pauses so you can guess the move yourself, then reveals every legal point and the one it chose."] },
    { title: "Auto Play (cont.)", lines: ["A stepper on that screen sets how long it pauses, from 2 to 10 seconds."] },
  ],
  about: [
    { title: "About Morabaraba", lines: ["Morabaraba (also called Umlabalaba) is a traditional two-player board game of Southern Africa,"] },
    { title: "About Morabaraba (cont.)", lines: ["played in places including Lesotho, South Africa, Botswana and Zimbabwe."] },
    { title: "About Morabaraba (cont.)", lines: ["Each player has twelve pieces, called cows. The board is three squares one inside another,"] },
    { title: "About Morabaraba (cont.)", lines: ["joined by lines across the middles and by diagonals across the corners."] },
    { title: "About Morabaraba (cont.)", lines: ["A board can be scratched into the ground or made of wood,"] },
    { title: "About Morabaraba (cont.)", lines: ["and stones or other small objects can serve as cows."] },
    { title: "A family of games", lines: ["Morabaraba belongs to the family of mill games, which includes Nine Men's Morris."] },
    { title: "A family of games (cont.)", lines: ["The diagonals and the extra cows make it quick and tactical."] },
    { title: "A family of games (cont.)", lines: ["Local rules vary. This version shoots while placing, one cow per move,"] },
    { title: "A family of games (cont.)", lines: ["and lets a player with three cows fly."] },
    { title: "A family of games (cont.)", lines: ["The board and the cows are painted for this game."] },
    { title: "A family of games (cont.)", lines: ["The bands around the board are decoration only."] },
  ],
  // Exhaustive rules reference (added for the in-app Rules page). Every claim here is cross-checked
  // against millfamily.js + morabaraba.js, the actual move/mill/win logic, not idealized rules.
  rules: [
    { title: "The board and setup", lines: ["Three squares sit one inside another: outer, middle and inner."] },
    { title: "The board and setup (cont.)", lines: ["Their corners and midpoints are the 24 points where cows stand."] },
    { title: "The board and setup (cont.)", lines: ["Each square is a ring of eight points joined around its own edge."] },
    { title: "The board and setup (cont.)", lines: ["Four SPOKES also join the midpoints of the three rings,"] },
    { title: "The board and setup (cont.)", lines: ["and four DIAGONALS join the corners of the three rings."] },
    { title: "Mills, and the setup", lines: ["A MILL is three cows of the same side standing on one straight line."] },
    { title: "Mills, and the setup (cont.)", lines: ["There are 20 such lines in total: 12 ring sides, 4 spokes and 4 diagonals."] },
    { title: "Mills, and the setup (cont.)", lines: ["Each player starts with twelve cows in hand and none on the board."] },
    { title: "Mills, and the setup (cont.)", lines: ["Dark places the first cow."] },
    { title: "The cow", cows: true, lines: ["Morabaraba has only one kind of piece: the cow."] },
    { title: "The cow (cont.)", lines: ["Dark and Light each herd twelve identical cows —"] },
    { title: "The cow (cont.)", lines: ["no cow is stronger than another."] },
    { title: "The cow (cont.)", lines: ["PLACING (while any cows remain in your hand):"] },
    { title: "The cow (cont.)", lines: ["TAP an empty point to place one there."] },
    { title: "The cow: moving and flying", lines: ["MOVING (once your hand is empty):"] },
    { title: "The cow: moving and flying (cont.)", lines: ["slide one cow one step to an adjacent empty point, along a ring side,"] },
    { title: "The cow: moving and flying (cont.)", lines: ["a spoke or a diagonal."] },
    { title: "The cow: moving and flying (cont.)", lines: ["FLYING: the instant you are down to exactly three"] },
    { title: "The cow: moving and flying (cont.)", lines: ["cows in total with none left in hand,"] },
    { title: "The cow: moving and flying (cont.)", lines: ["that cow may move to ANY empty point on the board —"] },
    { title: "The cow: moving and flying (cont.)", lines: ["adjacency no longer matters."] },
    { title: "Mills and shooting", lines: ["Closing a mill — by placing a cow,"] },
    { title: "Mills and shooting (cont.)", lines: ["or by sliding or flying one into place — lets you SHOOT:"] },
    { title: "Mills and shooting (cont.)", lines: ["remove one of the other side's cows from the board at once."] },
    { title: "Mills and shooting (cont.)", lines: ["A cow standing inside a currently formed mill is protected and cannot be shot,"] },
    { title: "Mills and shooting (cont.)", lines: ["UNLESS every one of that side's cows on the board is inside a mill —"] },
    { title: "Mills and shooting (cont.)", lines: ["then any of them, mill or not, becomes shootable."] },
    { title: "Shooting: one at a time, and swinging", lines: ["One move that closes two mills at the same time still shoots only ONE cow,"] },
    { title: "Shooting: one at a time, and swinging (cont.)", lines: ["never two. You choose which eligible cow to remove."] },
    { title: "Shooting: one at a time, and swinging (cont.)", lines: ["Swinging a mill open and shut works exactly as it sounds:"] },
    { title: "Shooting: one at a time, and swinging (cont.)", lines: ["sliding a cow out breaks the mill,"] },
    { title: "Shooting: one at a time, and swinging (cont.)", lines: ["and sliding it back in closes it again and lets you shoot again —"] },
    { title: "Shooting: one at a time, and swinging (cont.)", lines: ["as many times as you can repeat the swing."] },
    { title: "Winning the game", lines: ["You win the instant the other side is left with"] },
    { title: "Winning the game (cont.)", lines: ["fewer than three cows in total (hand plus board) —"] },
    { title: "Winning the game (cont.)", lines: ["usually the moment your shot brings them down to two."] },
    { title: "Winning the game (cont.)", lines: ["You also win if, on the other side's turn,"] },
    { title: "Winning the game (cont.)", lines: ["none of their cows can move at all."] },
    { title: "Winning the game (cont.)", lines: ["A flying side (already down to three cows) can never be blocked this way,"] },
    { title: "Winning the game (cont.)", lines: ["as long as at least one point on the board is empty."] },
    { title: "Draws", lines: ["If the board fills completely right after the very last cow is placed —"] },
    { title: "Draws (cont.)", lines: ["all 24 points taken, both hands empty, and nobody able to slide —"] },
    { title: "Draws (cont.)", lines: ["the game is drawn at once."] },
    { title: "Draws (cont.)", lines: ["From then on (once both hands are empty): the same position,"] },
    { title: "Draws (cont.)", lines: ["with the same side to move, occurring three times draws the game."] },
    { title: "Draws (cont.)", lines: ["Also from then on: 40 moves (plies) passing in a row without"] },
    { title: "Draws (cont.)", lines: ["either side landing a shot draws the game."] },
  ],
};
