// Word bank: the studio's own vocabulary list (graduate level), compiled from a hand-written
// notebook; synonyms/antonyms/distractors are our own. Each row is
// [word, synonym, antonym | null, distractor1, distractor2, meaning].
// The distractors are deliberately unrelated to the target so every round has exactly one
// unambiguous correct answer. A null antonym means the word is only used in Synonym mode.
// The `meaning` is the player's own definition, shown on the session review screen.
// An optional 7th element 'm' marks a mobile-only word: the free web preview leaves it out, so the
// apps can carry more words than the browser version (add new rows with ..., 'm' at the end).

export const WORDS = [
  ['abate', 'subside', 'intensify', 'fold', 'measure', 'subside; moderate'],
  ['aberrant', 'deviant', 'normal', 'wooden', 'striped', 'abnormal; deviant'],
  ['abeyance', 'suspension', 'continuation', 'harbor', 'ladder', 'suspended action'],
  ['abscond', 'flee', 'remain', 'travel', 'borrow', 'depart secretly; hide'],
  ['abstemious', 'temperate', 'indulgent', 'triangular', 'circular', 'sparing in eating & drinking; temperate'],
  ['admonish', 'reprove', 'praise', 'launch', 'paddle', 'warn; reprove'],
  ['adulterate', 'contaminate', 'purify', 'weave', 'sail', 'make impure by adding inferior substance'],
  ['aesthetic', 'artistic', 'utilitarian', 'cylindrical', 'coastal', 'artistic'],
  ['aggregate', 'gather', 'scatter', 'stitch', 'whistle', 'gather; accumulate'],
  ['alacrity', 'eagerness', 'reluctance', 'orchard', 'lantern', 'eagerness'],
  ['alleviate', 'relieve', 'aggravate', 'unpack', 'fold', 'relieve'],
  ['amalgamate', 'combine', 'separate', 'measure', 'travel', 'combine; unite'],
  ['ambiguous', 'unclear', 'explicit', 'metallic', 'northern', 'unclear'],
  ['ambivalence', 'uncertainty', 'conviction', 'blanket', 'saddle', 'contradictory or conflicting emotional attitudes'],
  ['ameliorate', 'improve', 'worsen', 'borrow', 'launch', 'improve'],
  ['anachronism', 'relic', null, 'meadow', 'kettle', 'something or someone misplaced in time'],
  ['analogous', 'comparable', 'dissimilar', 'freckled', 'rectangular', 'comparable'],
  ['anarchy', 'lawlessness', 'order', 'window', 'market', 'absence of governing body'],
  ['anomalous', 'irregular', 'typical', 'nocturnal', 'crimson', 'abnormal; irregular'],
  ['antipathy', 'aversion', 'affinity', 'teapot', 'bridge', 'dislike; aversion'],
  ['apathy', 'indifference', 'enthusiasm', 'harbor', 'ladder', 'indifference; lack of caring'],
  ['appease', 'pacify', 'provoke', 'paddle', 'weave', 'relieve; pacify or soothe'],
  ['apprise', 'inform', 'mislead', 'sail', 'stitch', 'inform'],
  ['approbation', 'approval', 'disapproval', 'orchard', 'lantern', 'approval'],
  ['appropriate', 'take', 'relinquish', 'whistle', 'unpack', 'acquire'],
  ['arduous', 'strenuous', 'easy', 'woolen', 'urban', 'hard; strenuous'],
  ['artless', 'guileless', 'cunning', 'rural', 'spherical', 'open and honest; without guile'],
  ['ascetic', 'austere', 'indulgent', 'ceramic', 'portable', 'practicing self-denial; austere'],
  ['assiduous', 'diligent', 'lazy', 'glassy', 'wooden', 'diligent'],
  ['assuage', 'soothe', 'aggravate', 'fold', 'measure', 'ease or lessen (pain); satisfy (hunger)'],
  ['attenuate', 'weaken', 'strengthen', 'travel', 'borrow', 'weaken, lessen, make thinner'],
  ['audacious', 'bold', 'timid', 'striped', 'triangular', 'daring; bold'],
  ['austere', 'stern', 'lavish', 'circular', 'cylindrical', 'severely simple and unornamented'],
  ['autonomous', 'independent', 'dependent', 'coastal', 'metallic', 'self-governing'],
  ['aver', 'declare', 'deny', 'launch', 'paddle', 'declare'],
  ['banal', 'trite', 'original', 'northern', 'freckled', 'commonplace, lacking originality'],
  ['belie', 'contradict', 'confirm', 'weave', 'sail', 'give a false impression; contradict'],
  ['beneficent', 'kindly', 'harmful', 'rectangular', 'nocturnal', 'doing good; kindly'],
  ['bolster', 'reinforce', 'undermine', 'stitch', 'whistle', 'reinforce; support'],
  ['bombastic', 'pompous', 'understated', 'crimson', 'woolen', 'using inflated language; pompous'],
  ['boorish', 'rude', 'refined', 'urban', 'rural', 'rude; insensitive'],
  ['burgeoning', 'flourishing', 'dwindling', 'spherical', 'ceramic', 'growing quickly; flourishing'],
  ['burnish', 'polish', 'tarnish', 'unpack', 'fold', 'polish'],
  ['buttress', 'support', 'undermine', 'measure', 'travel', 'support'],
  ['cacophonous', 'discordant', 'harmonious', 'portable', 'glassy', 'inharmonious; discordant'],
  ['capricious', 'fickle', 'steady', 'wooden', 'striped', 'unpredictable; fickle'],
  ['castigation', 'punishment', 'praise', 'blanket', 'saddle', 'punishment; severe criticism'],
  ['catalyst', 'trigger', 'obstacle', 'meadow', 'kettle', 'person or thing that causes action'],
  ['caustic', 'biting', 'gentle', 'triangular', 'circular', 'sarcastically biting; burning'],
  ['chicanery', 'trickery', 'honesty', 'window', 'market', 'deception; trickery'],
  ['cogent', 'convincing', 'unpersuasive', 'cylindrical', 'coastal', 'convincing'],
  ['commensurate', 'proportionate', 'disproportionate', 'metallic', 'northern', 'corresponding in extent, degree'],
  ['compendium', 'summary', null, 'teapot', 'bridge', 'brief'],
  ['complaisant', 'obliging', 'stubborn', 'freckled', 'rectangular', 'trying to please'],
  ['compliant', 'yielding', 'defiant', 'nocturnal', 'crimson', 'yielding'],
  ['conciliatory', 'placating', 'hostile', 'woolen', 'urban', 'reconciling; soothing'],
  ['condone', 'excuse', 'condemn', 'borrow', 'launch', 'overlook; forgive'],
  ['confound', 'confuse', 'clarify', 'paddle', 'weave', 'confuse'],
  ['connoisseur', 'expert', 'amateur', 'harbor', 'ladder', 'person competent to act as a judge of art'],
  ['contention', 'claim', 'concession', 'orchard', 'lantern', 'claim, thesis'],
  ['contentious', 'quarrelsome', 'agreeable', 'rural', 'spherical', 'quarrelsome'],
  ['contortion', 'distortion', null, 'blanket', 'saddle', 'distortion; twisting'],
  ['contrite', 'penitent', 'unrepentant', 'ceramic', 'portable', 'penitent'],
  ['conundrum', 'riddle', 'solution', 'meadow', 'kettle', 'riddle; difficult problem'],
  ['converge', 'meet', 'diverge', 'sail', 'stitch', 'tend to meet'],
  ['convoluted', 'intricate', 'straightforward', 'glassy', 'wooden', 'coiled around; intricate'],
  ['copious', 'plentiful', 'scant', 'striped', 'triangular', 'plentiful'],
  ['cow', 'intimidate', 'encourage', 'whistle', 'unpack', 'terrorize; intimidate'],
  ['craven', 'cowardly', 'brave', 'circular', 'cylindrical', 'cowardly'],
  ['daunt', 'intimidate', 'encourage', 'fold', 'measure', 'intimidate; frighten'],
  ['dearth', 'scarcity', 'abundance', 'window', 'market', 'scarcity'],
  ['debilitate', 'weaken', 'strengthen', 'travel', 'borrow', 'weaken'],
  ['decorum', 'propriety', 'rudeness', 'teapot', 'bridge', 'propriety; orderliness & good taste in manners'],
  ['default', 'failure', null, 'harbor', 'ladder', 'failure to act'],
  ['deference', 'respect', 'defiance', 'orchard', 'lantern', 'courteous regard for another\'s wish'],
  ['delineate', 'depict', 'blur', 'launch', 'paddle', 'sketch; depict; portray'],
  ['denigrate', 'disparage', 'praise', 'weave', 'sail', 'blacken'],
  ['deride', 'mock', 'admire', 'stitch', 'whistle', 'ridicule; make fun of'],
  ['derivative', 'unoriginal', 'innovative', 'coastal', 'metallic', 'unoriginal; obtained from another source'],
  ['desiccate', 'dry', 'moisten', 'unpack', 'fold', 'dry up'],
  ['desultory', 'aimless', 'methodical', 'northern', 'freckled', 'aimless; haphazard'],
  ['deterrent', 'hindrance', 'incentive', 'blanket', 'saddle', 'hindrance; something that discourages'],
  ['diatribe', 'harangue', 'compliment', 'meadow', 'kettle', 'bitter scolding'],
  ['dichotomy', 'division', 'unity', 'window', 'market', 'split'],
  ['diffidence', 'shyness', 'confidence', 'teapot', 'bridge', 'shyness'],
  ['diffuse', 'wordy', 'concise', 'rectangular', 'nocturnal', 'wordy; rambling'],
  ['digression', 'detour', 'focus', 'harbor', 'ladder', 'wandering away from the subject'],
  ['disabuse', 'enlighten', 'deceive', 'measure', 'travel', 'correct a false impression'],
  ['discerning', 'perceptive', 'obtuse', 'crimson', 'woolen', 'mentally quick & observant'],
  ['discordant', 'clashing', 'harmonious', 'urban', 'rural', 'not harmonious'],
  ['discredit', 'defame', 'vindicate', 'borrow', 'launch', 'defame; disbelieve'],
  ['discrepancy', 'inconsistency', 'agreement', 'orchard', 'lantern', 'lack of consistency'],
  ['discrete', 'separate', 'connected', 'spherical', 'ceramic', 'separate; unconnected'],
  ['disingenuous', 'insincere', 'candid', 'portable', 'glassy', 'insincere; lacking genuine candor'],
  ['disinterested', 'impartial', 'biased', 'wooden', 'striped', 'unprejudiced'],
  ['disjointed', 'incoherent', 'coherent', 'triangular', 'circular', 'lacking coherence'],
  ['dismiss', 'reject', 'accept', 'paddle', 'weave', 'reject'],
  ['disparage', 'belittle', 'praise', 'sail', 'stitch', 'belittle'],
  ['disparate', 'dissimilar', 'alike', 'cylindrical', 'coastal', 'unrelated; basically different'],
  ['dissemble', 'feign', 'reveal', 'whistle', 'unpack', 'disguise; pretend'],
  ['disseminate', 'distribute', 'withhold', 'fold', 'measure', 'distribute'],
  ['dissolution', 'disintegration', 'union', 'blanket', 'saddle', 'disintegration; looseness in morals'],
  ['dissonance', 'discord', 'harmony', 'meadow', 'kettle', 'discord; opposite of harmony'],
  ['distend', 'swell', 'shrink', 'travel', 'borrow', 'expand; swell out'],
  ['distill', 'purify', 'contaminate', 'launch', 'paddle', 'purify; refine'],
  ['diverge', 'split', 'converge', 'weave', 'sail', 'vary'],
  ['divest', 'strip', 'endow', 'stitch', 'whistle', 'strip; deprive'],
  ['document', 'record', null, 'unpack', 'fold', 'provide written evidence'],
  ['dogmatic', 'opinionated', 'flexible', 'metallic', 'northern', 'opinionated; arbitrary'],
  ['dormant', 'inactive', 'active', 'freckled', 'rectangular', 'sleeping; lethargic'],
  ['dupe', 'victim', null, 'window', 'market', 'someone easily fooled'],
  ['earthy', 'unrefined', 'refined', 'nocturnal', 'crimson', 'unrefined (e.g. earthy remarks)'],
  ['ebullient', 'exuberant', 'despondent', 'woolen', 'urban', 'showing excitement'],
  ['eclectic', 'diverse', 'narrow', 'rural', 'spherical', 'selective'],
  ['edify', 'instruct', 'corrupt', 'measure', 'travel', 'correct morally; instruct'],
  ['efficacy', 'effectiveness', 'futility', 'teapot', 'bridge', 'power to produce desired effect'],
  ['effrontery', 'audacity', 'timidity', 'harbor', 'ladder', 'presumptuousness'],
  ['elegy', 'lament', 'celebration', 'orchard', 'lantern', 'poem or song expressing lamentation'],
  ['elicit', 'evoke', 'suppress', 'borrow', 'launch', 'draw out by discussion'],
  ['elucidate', 'explain', 'obscure', 'paddle', 'weave', 'explain; enlighten'],
  ['embellish', 'adorn', 'simplify', 'sail', 'stitch', 'adorn; ornament'],
  ['embezzlement', 'theft', null, 'blanket', 'saddle', 'stealing'],
  ['emancipate', 'liberate', 'enslave', 'whistle', 'unpack', 'free from slavery; set free'],
  ['empirical', 'observed', 'theoretical', 'ceramic', 'portable', 'based on experience'],
  ['emulate', 'imitate', 'shun', 'fold', 'measure', 'imitate'],
  ['endemic', 'native', 'foreign', 'glassy', 'wooden', 'prevailing among specific group of people'],
  ['enervate', 'weaken', 'invigorate', 'travel', 'borrow', 'weaken'],
  ['engender', 'produce', 'prevent', 'launch', 'paddle', 'cause; produce'],
  ['enhance', 'improve', 'diminish', 'weave', 'sail', 'increase; improve'],
  ['eon', 'age', null, 'meadow', 'kettle', 'long period of time'],
  ['ephemeral', 'fleeting', 'permanent', 'striped', 'triangular', 'short lived'],
  ['equanimity', 'composure', 'agitation', 'window', 'market', 'calmness of temperament'],
  ['equivocate', 'hedge', 'commit', 'stitch', 'whistle', 'lie; mislead'],
  ['erudite', 'scholarly', 'ignorant', 'circular', 'cylindrical', 'learned; scholarly'],
  ['esoteric', 'obscure', 'common', 'coastal', 'metallic', 'hard to understand'],
  ['eulogy', 'tribute', 'condemnation', 'teapot', 'bridge', 'expression of praise'],
  ['euphemism', 'understatement', null, 'harbor', 'ladder', 'mild expression in place of an unpleasant statement'],
  ['exacerbate', 'worsen', 'soothe', 'unpack', 'fold', 'worsen; embitter'],
  ['exculpate', 'absolve', 'blame', 'measure', 'travel', 'clear from blame'],
  ['exigency', 'crisis', 'calm', 'orchard', 'lantern', 'urgent situation'],
  ['extrapolation', 'projection', null, 'blanket', 'saddle', 'projection; conjecture'],
  ['facetious', 'joking', 'serious', 'northern', 'freckled', 'joking (often inappropriate); humorous'],
  ['facilitate', 'ease', 'hinder', 'borrow', 'launch', 'make less difficult'],
  ['fallacious', 'erroneous', 'valid', 'rectangular', 'nocturnal', 'false; misleading'],
  ['fatuous', 'inane', 'sensible', 'crimson', 'woolen', 'brainless; inane; foolish, yet smug'],
  ['fawning', 'flattering', 'aloof', 'urban', 'rural', 'flattering'],
  ['felicitous', 'apt', 'inappropriate', 'spherical', 'ceramic', 'apt; well chosen; suitably expressed'],
  ['fervor', 'ardor', 'apathy', 'meadow', 'kettle', 'glowing ardor; intensity of feeling'],
  ['flag', 'wilt', 'flourish', 'paddle', 'weave', 'grow feeble; droop'],
  ['fledgling', 'novice', 'veteran', 'window', 'market', 'inexperienced'],
  ['flout', 'defy', 'obey', 'sail', 'stitch', 'reject; mock'],
  ['foment', 'incite', 'quell', 'whistle', 'unpack', 'stir up; instigate'],
  ['forestall', 'preempt', 'allow', 'fold', 'measure', 'prevent by taking action in advance'],
  ['frugality', 'thrift', 'extravagance', 'teapot', 'bridge', 'economy; thrift'],
  ['futile', 'useless', 'fruitful', 'portable', 'glassy', 'useless; hopeless; ineffectual'],
  ['gainsay', 'deny', 'affirm', 'travel', 'borrow', 'deny'],
  ['garrulous', 'talkative', 'reticent', 'wooden', 'striped', 'wordy; loquacious; talkative'],
  ['goad', 'prod', 'deter', 'launch', 'paddle', 'urge on; prod; incite'],
  ['grandiloquent', 'pompous', 'plain', 'triangular', 'circular', 'bombastic; pompous'],
  ['gregarious', 'sociable', 'reclusive', 'cylindrical', 'coastal', 'sociable'],
  ['guileless', 'candid', 'deceitful', 'metallic', 'northern', 'without deceit'],
  ['gullible', 'credulous', 'skeptical', 'freckled', 'rectangular', 'easily deceived'],
  ['harangue', 'rant', null, 'harbor', 'ladder', 'long, passionate, and vehement speech'],
  ['homogeneous', 'uniform', 'varied', 'nocturnal', 'crimson', 'of the same kind'],
  ['husband', 'conserve', 'squander', 'weave', 'sail', 'save'],
  ['hyperbole', 'exaggeration', 'understatement', 'orchard', 'lantern', 'exaggeration; overstatement'],
  ['iconoclastic', 'rebellious', 'conventional', 'woolen', 'urban', 'attacking cherished traditions'],
  ['idolatry', 'adoration', null, 'blanket', 'saddle', 'worship of idols; excessive admiration'],
  ['idyllic', 'peaceful', 'turbulent', 'rural', 'spherical', 'charmingly carefree; simple'],
  ['immutable', 'fixed', 'variable', 'ceramic', 'portable', 'unchangeable'],
  ['impair', 'damage', 'improve', 'stitch', 'whistle', 'injure; hurt'],
  ['impassive', 'stoic', 'emotional', 'glassy', 'wooden', 'without feeling; imperturbable; stoical'],
  ['impede', 'hinder', 'assist', 'unpack', 'fold', 'hinder; block'],
  ['impermeable', 'sealed', 'porous', 'striped', 'triangular', 'not permitting passage through'],
  ['imperturbable', 'unflappable', 'excitable', 'circular', 'cylindrical', 'calm; placid'],
  ['impervious', 'resistant', 'vulnerable', 'coastal', 'metallic', 'impenetrable; incapable of being damaged'],
  ['implacable', 'relentless', 'forgiving', 'northern', 'freckled', 'incapable of being pacified'],
  ['implicit', 'unstated', 'explicit', 'rectangular', 'nocturnal', 'understood but not stated'],
  ['implode', 'collapse', 'explode', 'measure', 'travel', 'burst inward'],
  ['implore', 'beg', 'command', 'borrow', 'launch', 'beg'],
  ['inadvertently', 'accidentally', 'deliberately', 'annually', 'nightly', 'unintentionally; carelessly'],
  ['inchoate', 'nascent', 'complete', 'crimson', 'woolen', 'recently begun; rudimentary'],
  ['incongruity', 'absurdity', 'harmony', 'meadow', 'kettle', 'lack of harmony; absurdity'],
  ['inconsequential', 'trivial', 'significant', 'urban', 'rural', 'insignificant; unimportant'],
  ['incorporate', 'include', 'exclude', 'paddle', 'weave', 'combine; unite'],
  ['indeterminate', 'vague', 'definite', 'spherical', 'ceramic', 'indefinite; uncertain'],
  ['indigence', 'poverty', 'wealth', 'window', 'market', 'poverty'],
  ['indolent', 'lazy', 'industrious', 'portable', 'glassy', 'lazy'],
  ['inert', 'inactive', 'dynamic', 'wooden', 'striped', 'inactive; lacking power to move'],
  ['ingenuous', 'naive', 'sophisticated', 'triangular', 'circular', 'naive and trusting; young'],
  ['inherent', 'innate', 'acquired', 'cylindrical', 'coastal', 'firmly established by nature or habit'],
  ['innocuous', 'harmless', 'harmful', 'metallic', 'northern', 'harmless'],
  ['insensible', 'unconscious', 'aware', 'freckled', 'rectangular', 'unconscious; unresponsive'],
  ['insinuate', 'imply', 'declare', 'sail', 'stitch', 'hint; imply; creep in'],
  ['insipid', 'bland', 'flavorful', 'nocturnal', 'crimson', 'lacking in flavor; dull'],
  ['insularity', 'isolation', 'openness', 'teapot', 'bridge', 'isolation; narrow-mindedness'],
  ['intractable', 'unruly', 'obedient', 'woolen', 'urban', 'unruly; stubborn; unyielding'],
  ['intransigence', 'obstinacy', 'flexibility', 'harbor', 'ladder', 'stubbornness'],
  ['inundate', 'flood', 'drain', 'whistle', 'unpack', 'overwhelm; flood; submerge'],
  ['inured', 'accustomed', 'unaccustomed', 'rural', 'spherical', 'accustomed; hardened'],
  ['irascible', 'irritable', 'placid', 'ceramic', 'portable', 'irritable; easily angered'],
  ['irresolute', 'hesitant', 'decisive', 'glassy', 'wooden', 'uncertain how to act; weak'],
  ['itinerary', 'route', null, 'orchard', 'lantern', 'plan of a trip'],
  ['laconic', 'terse', 'verbose', 'striped', 'triangular', 'brief and to the point'],
  ['lassitude', 'weariness', 'vigor', 'blanket', 'saddle', 'weariness; languor'],
  ['latent', 'hidden', 'apparent', 'circular', 'cylindrical', 'potential but undeveloped; dormant'],
  ['laud', 'praise', 'criticize', 'fold', 'measure', 'praise'],
  ['lethargic', 'sluggish', 'energetic', 'coastal', 'metallic', 'dull; drowsy'],
  ['levity', 'frivolity', 'gravity', 'meadow', 'kettle', 'lack of seriousness or steadiness'],
  ['log', 'record', null, 'window', 'market', 'record of day-to-day activities'],
  ['loquacious', 'talkative', 'taciturn', 'northern', 'freckled', 'talkative'],
  ['lucid', 'clear', 'obscure', 'rectangular', 'nocturnal', 'easily understood; clear; intelligible'],
  ['luminous', 'radiant', 'dim', 'crimson', 'woolen', 'shining; issuing light'],
  ['magnanimity', 'generosity', 'pettiness', 'teapot', 'bridge', 'generosity'],
  ['malingerer', 'shirker', null, 'harbor', 'ladder', 'one who feigns illness to escape duty'],
  ['malleable', 'pliable', 'rigid', 'urban', 'rural', 'capable of being shaped by pounding'],
  ['maverick', 'nonconformist', 'conformist', 'orchard', 'lantern', 'rebel; nonconformist'],
  ['mendacious', 'dishonest', 'truthful', 'spherical', 'ceramic', 'lying; habitually dishonest'],
  ['metamorphosis', 'transformation', 'stability', 'blanket', 'saddle', 'change of form'],
  ['meticulous', 'painstaking', 'careless', 'portable', 'glassy', 'excessively careful; painstaking'],
  ['misanthrope', 'cynic', 'philanthropist', 'meadow', 'kettle', 'one who hates mankind'],
  ['mitigate', 'lessen', 'aggravate', 'travel', 'borrow', 'lessen in intensity; moderate; appease'],
  ['mollify', 'soothe', 'enrage', 'launch', 'paddle', 'soothe'],
  ['morose', 'sullen', 'cheerful', 'wooden', 'striped', 'ill-humored; sullen; melancholy'],
  ['mundane', 'ordinary', 'extraordinary', 'triangular', 'circular', 'everyday; worldly as opposed to spiritual'],
  ['negate', 'nullify', 'affirm', 'weave', 'sail', 'cancel out; nullify; deny'],
  ['neophyte', 'beginner', 'expert', 'window', 'market', 'recent convert; beginner'],
  ['obdurate', 'stubborn', 'yielding', 'cylindrical', 'coastal', 'stubborn'],
  ['obsequious', 'servile', 'domineering', 'metallic', 'northern', 'slavishly attentive; servile; sycophantic'],
  ['obviate', 'preclude', 'necessitate', 'stitch', 'whistle', 'make unnecessary; get rid of'],
  ['occlude', 'obstruct', 'unblock', 'unpack', 'fold', 'clog; obstruct; close'],
  ['officious', 'meddlesome', 'reserved', 'freckled', 'rectangular', 'meddlesome; excessively pushy in offering services'],
  ['onerous', 'burdensome', 'easy', 'nocturnal', 'crimson', 'burdensome'],
  ['opprobrium', 'disgrace', 'honor', 'teapot', 'bridge', 'infamy; vilification'],
  ['oscillate', 'swing', 'remain', 'measure', 'travel', 'vibrate pendulum-like; waver'],
  ['ostentatious', 'showy', 'modest', 'woolen', 'urban', 'showy; pretentious; trying to attract attention'],
  ['paean', 'tribute', 'lament', 'harbor', 'ladder', 'song of joy'],
  ['palpable', 'tangible', 'intangible', 'rural', 'spherical', 'tangible; easily perceived'],
  ['paragon', 'exemplar', 'failure', 'orchard', 'lantern', 'model of perfection'],
  ['partisan', 'biased', 'neutral', 'ceramic', 'portable', 'one-sided; prejudiced; committed to a party'],
  ['pathological', 'diseased', 'sound', 'glassy', 'wooden', 'pertaining to disease'],
  ['paucity', 'scarcity', 'abundance', 'blanket', 'saddle', 'scarcity'],
  ['pedantic', 'fussy', 'casual', 'striped', 'triangular', 'showing off learning; bookish'],
  ['penchant', 'inclination', 'aversion', 'meadow', 'kettle', 'strong inclination; liking'],
  ['penury', 'destitution', 'affluence', 'window', 'market', 'severe poverty; stinginess'],
  ['perennial', 'enduring', 'temporary', 'circular', 'cylindrical', 'something long-lasting'],
  ['perfidious', 'treacherous', 'loyal', 'coastal', 'metallic', 'disloyal; treacherous'],
  ['perfunctory', 'cursory', 'thorough', 'northern', 'freckled', 'superficial; not thorough'],
  ['permeable', 'porous', 'impenetrable', 'rectangular', 'nocturnal', 'penetrable; porous'],
  ['pervasive', 'widespread', 'confined', 'crimson', 'woolen', 'spread throughout'],
  ['phlegmatic', 'composed', 'excitable', 'urban', 'rural', 'calm; not easily disturbed'],
  ['piety', 'devoutness', 'irreverence', 'teapot', 'bridge', 'devoutness; reverence for God'],
  ['placate', 'appease', 'anger', 'borrow', 'launch', 'pacify; conciliate'],
  ['plasticity', 'flexibility', 'rigidity', 'harbor', 'ladder', 'ability to be molded'],
  ['platitude', 'cliche', 'insight', 'orchard', 'lantern', 'trite remark; commonplace statement'],
  ['plethora', 'excess', 'shortage', 'blanket', 'saddle', 'excess; overabundance'],
  ['porous', 'permeable', 'solid', 'spherical', 'ceramic', 'full of pores; like a sieve'],
  ['pragmatic', 'practical', 'idealistic', 'portable', 'glassy', 'practical'],
  ['precarious', 'unstable', 'secure', 'wooden', 'striped', 'uncertain; risky'],
  ['precipitate', 'hasty', 'deliberate', 'triangular', 'circular', 'rash; premature; hasty; sudden'],
  ['precursor', 'forerunner', 'successor', 'meadow', 'kettle', 'forerunner'],
  ['presumptuous', 'arrogant', 'humble', 'cylindrical', 'coastal', 'arrogant; taking liberties'],
  ['prevaricate', 'evade', 'confess', 'paddle', 'weave', 'lie'],
  ['pristine', 'spotless', 'soiled', 'metallic', 'northern', 'unspoiled; primitive'],
  ['probity', 'integrity', 'dishonesty', 'window', 'market', 'uprightness; incorruptibility'],
  ['problematic', 'questionable', 'straightforward', 'freckled', 'rectangular', 'doubtful; unsettled; questionable'],
  ['prodigal', 'wasteful', 'thrifty', 'nocturnal', 'crimson', 'wasteful; reckless with money'],
  ['profound', 'deep', 'shallow', 'woolen', 'urban', 'deep; complete'],
  ['prohibitive', 'forbidding', 'permissive', 'rural', 'spherical', 'inclined to prevent or forbid'],
  ['proliferate', 'multiply', 'dwindle', 'sail', 'stitch', 'grow rapidly'],
  ['propensity', 'tendency', 'aversion', 'teapot', 'bridge', 'natural inclination'],
  ['propitiate', 'conciliate', 'provoke', 'whistle', 'unpack', 'appease'],
  ['propriety', 'decorum', 'vulgarity', 'harbor', 'ladder', 'fitness; correct conduct'],
  ['proscribe', 'forbid', 'permit', 'fold', 'measure', 'outlaw; banish; ostracize'],
  ['qualified', 'limited', 'unconditional', 'ceramic', 'portable', 'limited; restricted'],
  ['quibble', 'nitpick', 'agree', 'travel', 'borrow', 'minor objection or complaint'],
  ['quiescent', 'inactive', 'restless', 'glassy', 'wooden', 'at rest; dormant'],
  ['rarefied', 'thin', 'dense', 'striped', 'triangular', 'made less dense'],
  ['recalcitrant', 'defiant', 'obedient', 'circular', 'cylindrical', 'determined to resist authority'],
  ['recant', 'retract', 'affirm', 'launch', 'paddle', 'retract a previous statement'],
  ['recondite', 'obscure', 'obvious', 'coastal', 'metallic', 'secret; abstruse; profound'],
  ['refractory', 'unruly', 'docile', 'northern', 'freckled', 'stubborn; unmanageable'],
  ['refute', 'disprove', 'confirm', 'weave', 'sail', 'disprove'],
  ['relegate', 'demote', 'promote', 'stitch', 'whistle', 'assign; delegate; banish to an inferior position'],
  ['reproach', 'rebuke', 'praise', 'unpack', 'fold', 'express disapproval or disappointment'],
  ['reprobate', 'scoundrel', 'saint', 'orchard', 'lantern', 'person hardened in sin, devoid of sense of decency'],
  ['repudiate', 'disown', 'accept', 'measure', 'travel', 'disown; disavow'],
  ['rescind', 'revoke', 'enact', 'borrow', 'launch', 'cancel'],
  ['resolution', 'determination', 'indecision', 'blanket', 'saddle', 'determination'],
  ['resolve', 'firmness', 'indecision', 'meadow', 'kettle', 'determination; firmness of purpose'],
  ['reticent', 'reserved', 'talkative', 'rectangular', 'nocturnal', 'reserved; uncommunicative'],
  ['reverent', 'respectful', 'irreverent', 'crimson', 'woolen', 'respectful; worshipful'],
  ['sage', 'philosopher', 'fool', 'window', 'market', 'person celebrated for wisdom'],
  ['salubrious', 'wholesome', 'noxious', 'urban', 'rural', 'healthful'],
  ['sanction', 'approve', 'forbid', 'paddle', 'weave', 'approve; ratify'],
  ['satiate', 'satisfy', 'deprive', 'sail', 'stitch', 'satisfy fully'],
  ['saturate', 'soak', 'dry', 'whistle', 'unpack', 'soak thoroughly'],
  ['savor', 'relish', 'dislike', 'fold', 'measure', 'enjoy; have a distinctive flavor, smell or quality'],
  ['secrete', 'conceal', 'reveal', 'travel', 'borrow', 'hide away or cache'],
  ['shard', 'fragment', null, 'teapot', 'bridge', 'fragment, generally of pottery'],
  ['skeptic', 'doubter', 'believer', 'harbor', 'ladder', 'doubter'],
  ['solicitous', 'concerned', 'indifferent', 'spherical', 'ceramic', 'worried; concerned'],
  ['soporific', 'sedative', 'stimulating', 'portable', 'glassy', 'sleep-causing; marked by sleepiness'],
  ['specious', 'plausible', 'genuine', 'wooden', 'striped', 'seemingly reasonable but incorrect'],
  ['spectrum', 'range', null, 'orchard', 'lantern', 'colored band produced when a beam of white light is diffracted'],
  ['sporadic', 'irregular', 'constant', 'triangular', 'circular', 'occurring irregularly'],
  ['stigma', 'disgrace', 'honor', 'blanket', 'saddle', 'token of disgrace; brand'],
  ['stint', 'skimp', 'lavish', 'launch', 'paddle', 'set limits; be thrifty'],
  ['stipulate', 'specify', 'waive', 'weave', 'sail', 'make express conditions, specify'],
  ['stolid', 'unemotional', 'excitable', 'cylindrical', 'coastal', 'dull; impassive'],
  ['subpoena', 'summons', null, 'meadow', 'kettle', 'writ summoning a witness to appear'],
  ['subside', 'abate', 'intensify', 'stitch', 'whistle', 'settle down; descend; grow quiet'],
  ['substantiate', 'verify', 'refute', 'unpack', 'fold', 'establish by evidence; verify'],
  ['supersede', 'replace', 'retain', 'measure', 'travel', 'replace, make obsolete'],
  ['supposition', 'surmise', 'fact', 'window', 'market', 'hypothesis; surmise'],
  ['tacit', 'implicit', 'explicit', 'metallic', 'northern', 'understood'],
  ['tangential', 'peripheral', 'central', 'freckled', 'rectangular', 'peripheral; only slightly connected'],
  ['tenuous', 'flimsy', 'solid', 'nocturnal', 'crimson', 'thin; rare; slim'],
  ['tirade', 'rant', 'compliment', 'teapot', 'bridge', 'extended scolding; denunciation'],
  ['torpor', 'lethargy', 'vigor', 'harbor', 'ladder', 'lethargy; sluggishness; dormancy'],
  ['tortuous', 'winding', 'direct', 'woolen', 'urban', 'winding; full of curves'],
  ['tractable', 'docile', 'stubborn', 'rural', 'spherical', 'docile; easily managed'],
  ['transgression', 'violation', 'obedience', 'orchard', 'lantern', 'violation of law; sin'],
  ['truculence', 'belligerence', 'gentleness', 'blanket', 'saddle', 'aggressiveness; ferocity'],
  ['vacillate', 'waver', 'decide', 'borrow', 'launch', 'waver; fluctuate'],
  ['venerate', 'revere', 'despise', 'paddle', 'weave', 'revere'],
  ['veracious', 'truthful', 'deceitful', 'ceramic', 'portable', 'truthful'],
  ['verbose', 'wordy', 'concise', 'glassy', 'wooden', 'wordy'],
  ['viable', 'workable', 'impractical', 'striped', 'triangular', 'practical or workable'],
  ['viscous', 'sticky', 'fluid', 'circular', 'cylindrical', 'sticky, gluey'],
  ['vituperative', 'abusive', 'complimentary', 'coastal', 'metallic', 'abusive; scolding'],
  ['volatile', 'unstable', 'steady', 'northern', 'freckled', 'changeable; explosive; rapidly evaporating'],
  ['warranted', 'justified', 'unjustified', 'rectangular', 'nocturnal', 'justified; authorized'],
  ['wary', 'cautious', 'reckless', 'crimson', 'woolen', 'very cautious'],
  ['welter', 'jumble', 'order', 'meadow', 'kettle', 'turmoil; bewildering jumble'],
  ['whimsical', 'fanciful', 'practical', 'urban', 'rural', 'fanciful; capricious'],
  ['zealot', 'fanatic', 'moderate', 'window', 'market', 'fanatic; person who shows excessive zeal'],
];
