// Text for How to Play, About and the full Rules reference. Pages are short and single-concept on purpose: the text size
// stepper goes up to 300%, and every page here still fits at that size (the renderer only shrinks text as a last
// resort). Every rule claim below is cross-checked against rules.js, the single source of truth; the diagrams reuse the
// game's own board and piece painting, and the dotted dots on them are generated by the real move generator (genInto),
// so a diagram cannot disagree with the engine.
import { genInto, parseSq, mFrom, mTo, startBoard, LIMIT_TABLE, NO_PAWN_COUNT_LIMIT, REPETITION_LIMIT } from './rules.js';
import { parseSetup } from './lessons.js';

const pad = new Int32Array(256);
// dia({ win: 'a1:h8', p: 'Md4 pe5', from: 'd4', arrows: 'd4-e5', rings: 'e5', S: 56, side: 1 })
function dia({ win = 'a1:h8', p = '', from = null, side = 1, arrows = '', rings = '', S = 56, board = null }) {
  const [a, b] = win.split(':'), s0 = parseSq(a), s1 = parseSq(b);
  const f0 = s0 & 7, r0 = s0 >> 3, f1 = s1 & 7, r1 = s1 >> 3;
  const bd = board || parseSetup(p), pieces = [];
  // only pieces inside the diagram's window are drawn: a window smaller than the board must not draw the rest of the board outside it
  bd.forEach((v, s) => { const f = s & 7, r = s >> 3; if (v && f >= f0 && f <= f1 && r >= r0 && r <= r1) pieces.push([s, v]); });
  const marks = [];
  if (from) {
    const fs = parseSq(from), n = genInto(bd, bd[fs] > 0 ? 1 : -1, pad, 0, false);
    for (let i = 0; i < n; i++) if (mFrom(pad[i]) === fs) marks.push([mTo(pad[i]), bd[mTo(pad[i])] ? 'x' : 'm']);
  }
  const pt = (str) => str.split(' ').filter(Boolean).map((x) => parseSq(x));
  const ar = arrows ? arrows.split(' ').map((x) => { const [u, v] = x.split('-'); return [parseSq(u), parseSq(v)]; }) : [];
  return { f0, f1, r0, r1, S, pieces, marks, arrows: ar, rings: rings ? pt(rings) : [] };
}
const start = () => dia({ board: startBoard(), S: 36 });

export const HOWTO = [
  { title: 'The goal', diagram: dia({ win: 'e4:h8', p: 'Kg6 kh8 Re8', arrows: 'e8-h8', S: 60 }), lines: ['Checkmate the other side\'s Khun (king): attack it so it cannot escape. You play Gold or Ruby against the computer.'] },
  { title: 'Making a move', diagram: dia({ win: 'a1:h8', p: 'Nd4 pe6 Pc4', from: 'd4', S: 50 }), lines: ['Tap one of your pieces. Its legal squares light up. Tap a lit square to move there. You can also drag the piece and let go.'] },
  { title: 'Gold moves first', lines: ['Players take turns, one move each. Gold always starts. In the settings you can choose to play Ruby, who answers.'] },
  { title: 'Think', lines: ['Not sure? Tap Think. The computer marks a strong move with a gold arrow and says why it is good. It never moves for you.'] },
  { title: 'Threats and Undo', lines: ['Threats rings your pieces that could be taken next move. Undo takes back your last move and the reply, as often as you like.'] },
  { title: 'The dotted rank', diagram: dia({ win: 'a1:h8', p: 'Pd5', from: 'd5', S: 50 }), lines: ['The dotted row is your sixth rank. A Bia (cowrie) that reaches it flips into a Bia-ngai, a stronger piece that steps like a Met.'] },
  { title: 'The Count strip', lines: ['Under the board, the Count strip shows the counting rule. It starts when no Bia remain, and shows how many moves are left to mate.'] },
  { title: 'Learn, and Watch & Learn', lines: ['Learn has eight short lessons. Watch & Learn plays a whole game between two computers: you guess first, then see the moves.'] },
  { title: 'Settings and text size', lines: ['Choose a level from Beginner to Master, a board look, and how long Watch & Learn thinks. The A- and A+ buttons enlarge text up to 300%.'] },
];

export const ABOUT = [
  { title: 'About Makruk', diagram: start(), lines: ['Makruk is the traditional chess of Thailand. It is played across the country, and a close relative is played in Cambodia.'] },
  { title: 'An old family', lines: ['Makruk comes from the same ancient game family as chess, shogi and xiangqi. It keeps older, slower pieces and its own endgame counting.'] },
  { title: 'What is different', lines: ['The board has no checkered colours. Pawns are cowries. The Met steps one square, pawns promote on the sixth rank, and endgames are timed by a count.'] },
  { title: 'About this game', lines: ['A complete Makruk with five computer levels, eight lessons, Watch & Learn, and a Rules reference. It works offline and has no ads.'] },
];

// ---- the exhaustive Rules reference -------------------------------------------------------------------------------------------------
const pieceDia = (letter, sq, extra = '') => dia({ win: 'a1:h8', p: `${letter}${sq} ${extra}`, from: sq, S: 50 });
export const RULES = [
  { title: 'The board', diagram: start(), lines: ['Eight files, a to h, and eight ranks, 1 to 8. The squares are all one colour.'] },
  { title: 'Two sides', lines: ['One side is Gold and the other is Ruby. Gold moves first, then the players take turns, one move each.'] },
  { title: 'Sixteen pieces each', lines: ['Each side has one Khun, one Met, two Khon, two Ma, two Rua and eight Bia.'] },
  { title: 'The start', diagram: start(), lines: ['The Bia stand on the third rank for Gold and the sixth rank for Ruby.'] },
  { title: 'Khun and Met', diagram: dia({ win: 'a1:h2', board: startBoard(), S: 66 }), lines: ['Gold\'s Khun starts on d1 and its Met on e1. Ruby\'s Khun starts on e8 and its Met on d8.'] },
  { title: 'Winning', lines: ['You win by checkmate. Nothing else wins a game. A game that cannot be won is drawn.'] },
  { title: 'Check', diagram: dia({ win: 'c4:g8', p: 'Ke4 re8', arrows: 'e8-e4', rings: 'e4', S: 60 }), lines: ['A Khun is in check when an enemy piece could capture it next move.'] },
  { title: 'Escaping check', lines: ['Get out of check by moving the Khun, capturing the attacker, or putting a piece in the way. A Ma cannot be blocked.'] },
  { title: 'Checkmate', diagram: dia({ win: 'e4:h8', p: 'Kg6 kh8 Re8', arrows: 'e8-h8', S: 60 }), lines: ['If a Khun is in check and no move escapes, that is checkmate.'] },
  { title: 'Never leave your Khun in check', lines: ['A move that leaves your own Khun attacked is not legal. A piece that guards your Khun may not step away.'] },
  { title: 'Capturing', lines: ['Move onto an enemy piece to capture it. The piece is removed. You may never capture your own piece.'] },
  { title: 'The Khun', diagram: pieceDia('K', 'd4'), lines: ['The Khun steps one square in any direction, and captures the same way.'] },
  { title: 'The Met', diagram: pieceDia('M', 'd4'), lines: ['The Met steps one square diagonally, and captures the same way. It is the weakest piece but the Khun\'s helper.'] },
  { title: 'The Khon', diagram: pieceDia('S', 'd4'), lines: ['The Khon steps one square diagonally, or one square straight forward.'] },
  { title: 'The Khon: no more', lines: ['A Khon cannot step backward or sideways. Forward means toward the other side.'] },
  { title: 'The Ma', diagram: pieceDia('N', 'd4'), lines: ['The Ma jumps two squares one way, then one square to the side.'] },
  { title: 'The Ma leaps', diagram: dia({ win: 'a1:h8', p: 'Nd4 Pd5 Pc4 Pe4 pd3 pe5 pf5', from: 'd4', S: 50 }), lines: ['The Ma jumps over any pieces. It captures the piece on the square where it lands.'] },
  { title: 'The Rua', diagram: pieceDia('R', 'd4'), lines: ['The Rua slides any number of squares along a rank or a file.'] },
  { title: 'The Rua is blocked', diagram: dia({ win: 'a1:h8', p: 'Rd4 Pd6 pf4 pd2', from: 'd4', S: 50 }), lines: ['The Rua cannot jump. It stops before its own piece, or on an enemy piece to capture it.'] },
  { title: 'The Bia', diagram: dia({ win: 'a1:h8', p: 'Pd3', from: 'd3', S: 50 }), lines: ['A Bia steps one square straight forward. There is no two-step first move.'] },
  { title: 'The Bia captures', diagram: dia({ win: 'a1:h8', p: 'Pd3 pc4 pe4', from: 'd3', S: 50 }), lines: ['A Bia captures one square diagonally forward. It cannot capture straight ahead.'] },
  { title: 'The Bia is blocked', diagram: dia({ win: 'a1:h8', p: 'Pd3 pd4', from: 'd3', S: 50 }), lines: ['An enemy piece straight ahead blocks a Bia. It must wait or go around.'] },
  { title: 'Promotion', diagram: dia({ win: 'a1:h8', p: 'Pd5', from: 'd5', S: 50 }), lines: ['A Gold Bia that reaches the sixth rank is promoted. A Ruby Bia is promoted on the third rank.'] },
  { title: 'The Bia-ngai', diagram: dia({ win: 'a1:h8', p: 'Gd6', from: 'd6', S: 50 }), lines: ['A promoted Bia is a Bia-ngai. It steps one square diagonally, exactly like a Met.'] },
  { title: 'Promotion is automatic', lines: ['There is no choice: a Bia always becomes a Bia-ngai. It is shown as the cowrie turned over.'] },
  { title: 'Not in Makruk', lines: ['There is no castling, no en passant, and no two-square first move for the Bia.'] },
  { title: 'Stalemate', lines: ['If the side to move has no legal move and is not in check, the game is drawn by stalemate.'] },
  { title: 'Bare Khun', lines: ['If both sides are down to a bare Khun, neither can mate and the game is drawn.'] },
  { title: 'Repetition', lines: [`In this game, if the same position appears ${REPETITION_LIMIT} times with the same side to move, the game is drawn.`] },
  { title: 'Why there is a count', lines: ['A lone Khun is hard to trap. To stop endless chases, Makruk limits how long the stronger side has to checkmate.'] },
  { title: 'Counting begins', lines: ['Counting is only used when no Bia remain on the board for either side. Promoted Bia are not Bia.'] },
  { title: 'Board\'s honour', lines: ['If both sides still have a piece besides the Khun, the count is Board\'s honour. It begins at 1.'] },
  { title: 'Board\'s honour: the limit', lines: [`The stronger side must checkmate by count ${NO_PAWN_COUNT_LIMIT}. If it does not, the game is drawn.`] },
  { title: 'Pieces\' honour', lines: ['If one side has only its Khun, the count is Pieces\' honour. The other side is the one counting.'] },
  { title: 'Where it starts', lines: ['Pieces\' honour starts at the number of pieces left on the board, both Khun included, plus one.'] },
  { title: 'An example', diagram: dia({ win: 'a1:h8', p: 'Ke1 Ra1 Rh1 kd5', S: 46 }), lines: ['Gold has a Khun and two Rua, Ruby has a Khun. That is four pieces, so the count starts at 5.'] },
  { title: 'A short count', lines: ['With many pieces left the count can start at or above its limit. Then the stronger side has just one counted move.'] },
  { title: 'The limit: strong pieces', lines: LIMIT_TABLE.slice(0, 3).map(([n, v]) => `${n}: count to ${v}.`) },
  { title: 'The limit: others', lines: LIMIT_TABLE.slice(3).map(([n, v]) => `${n}: count to ${v}.`) },
  { title: 'Which limit applies', lines: ['If several lines fit the pieces of the stronger side, the smallest limit applies.'] },
  { title: 'Counting in this game', lines: ['Counting starts by itself and cannot be stopped: nobody has to claim it. Only the stronger side\'s moves are counted, one count per move.'] },
  { title: 'The Count strip', lines: ['The strip under the board shows which rule is running, the count, the limit, and how many moves are left.'] },
  { title: 'The count runs out', lines: ['Checkmate on a counted move wins. If the stronger side moves at the limit without mate, the game is drawn.'] },
  { title: 'When the rule changes', lines: ['If Board\'s honour is running and one side loses all its pieces, the Pieces\' honour count begins instead.'] },
  { title: 'Winning with two Rua', lines: ['Two Rua can force mate: use one to cut the Khun off along a rank, and the other to follow and drive it to the edge.'] },
  { title: 'Tips: the Bia', lines: ['Advance Bia together so they protect each other. A promoted Bia-ngai is worth more than a Bia, so races matter.'] },
  { title: 'Tips: the middle', lines: ['Keep your Khon near your Khun, bring Ma to the centre, and use the Rua on open files.'] },
  { title: 'Tips: the endgame', lines: ['Before you trade down, check the count: some endings with one Ma or one Khon cannot be won in time.'] },
  { title: 'Controls', lines: ['Tap a piece and a lit square, or drag. Think, Undo, Threats and Resign are under the board. On a keyboard use arrows, Space, U, H and T.'] },
];
export const page = (scene) => (scene === 'howto' ? HOWTO : scene === 'about' ? ABOUT : RULES);
