// About, How to Play and Rules. Every rule here is cross-checked against engine.js / ball.js / field.js
// (numbers quoted are the real constants). Items use the ui.js column vocabulary; { t: 'fig', key } draws
// the game's own art (figures.js), never a separate icon set.
const h = (text) => ({ t: 'h', text });
const p = (text) => ({ t: 'para', text });
const fig = (key, height = 280) => ({ t: 'fig', key, h: height });
const gap = (n = 10) => ({ t: 'gap', h: n });
const rule = () => ({ t: 'rule' });

export const ABOUT = [
  { t: 'title', text: 'About Golden Hour Cricket', size: 38 },
  p('Golden Hour Cricket is an original cricket game for your phone: swipe to bat, flick to bowl, run between the wickets and chase a target before the sun goes down.'),
  rule(),
  h('Where cricket comes from'),
  p('Cricket began in England, where a bat-and-ball game was being played by the 1500s and grew into the sport we know. It spread with travellers, soldiers and traders through the Commonwealth and beyond, and today it is played and loved across Australia, India, Pakistan, Sri Lanka, Bangladesh, South Africa, the Caribbean, New Zealand, the United Kingdom and many other places.'),
  h('Backyard cricket'),
  p('Cricket did not start in Australia, but Australians have made it their own. Backyard and beach cricket is a beloved tradition there: a tennis ball, a bin or a set of stumps for a wicket, the garden fence for a boundary, and house rules argued over at every barbecue. Tippy-go, one-hand-one-bounce and six-and-out are three of the best known. They are all in this game.'),
  h('What is in the game'),
  p('A limited-overs chase with real scoring, a full match where you bowl first, a Super Over, four backyard house-rule modes, a Daily Innings, three golden-hour grounds (stadium, backyard and beach), four opponents of rising skill and an Auto Play mode that shows a computer batter thinking through every ball.'),
  h('Original, and for everyone'),
  p('Every player, team and ground in this game is invented. It is not connected to any league, board or tournament. It is a score-only game: no chips, no stakes, no betting of any kind.'),
  gap(6),
];

export const HOWTO = [
  { t: 'title', text: 'How to Play', size: 40 },
  h('1. Bat: swipe'),
  p('When the bowler lets go of the ball, swipe on the screen. The direction of your swipe is the direction the ball goes on the field: up is straight back over the bowler, right is the off side, left is the leg side, down-right is a late cut behind square.'),
  fig('wheel', 300),
  h('2. Timing'),
  p('The moment you start the swipe is your timing. Swipe just as the ball reaches the bat: PERFECT or GOOD timing gives clean, powerful contact. Too early pulls the ball to the leg side, too late sends it to the off side or off the edge.'),
  fig('timing', 150),
  h('3. Power'),
  p('A slow, gentle drag pushes the ball along the ground for singles. A firm swipe drives it hard along the ground. A fast flick lifts it into the air for a six, but hitting hard makes the timing window smaller and the ball can be caught.'),
  h('4. Tap to block, do nothing to leave'),
  p('A quick tap is a forward defence: the safe answer to a yorker or a ball you do not trust. If a ball is far outside off, leave it alone.'),
  h('5. Read the field'),
  p('The round radar shows every fielder as a dot. Swipe toward the gaps. Fielders run from where they stand, so a ground shot between two of them is a four, and a shot straight at one is a dot.'),
  fig('field', 360),
  h('6. Run'),
  p('After you hit the ball, the big RUN button appears. Tap it to run. Tap it again while running to queue another run. Fielders pick up and throw: if the throw beats you, you are run out. Watch where the ball goes before you commit.'),
  fig('run', 250),
  h('7. Bowl'),
  p('In a Full Match you bowl the first innings. Choose a delivery type, drag the target ring on the pitch to pick line and length, then flick up to bowl. A faster flick is quicker but less accurate. Set a field between overs.'),
  h('8. Think'),
  p('The Think button gives a hint before the ball (what is coming and where the gap is) or while running (whether the run is safe). You get three per innings.'),
  h('9. Auto Play'),
  p('Choose Auto Play from the menu to watch the computer bat a whole innings. For every ball it thinks, shows you its choice, then plays it. You can pause, change the thinking time and speed it up.'),
];

export const RULES = [
  { t: 'title', text: 'Rules', size: 44 },
  p('Cricket basics first, then exactly how this game works. Everything here matches the game engine.'),
  rule(),
  h('Cricket in one minute'),
  p('Two teams take turns to bat and to field. The batting team scores runs. The fielding team tries to get the batters out. An innings ends when the batting team has used all its overs or lost all its wickets, or has passed the target.'),
  p('In this game you bat against a target (a chase), and in the Full Match you also bowl the first innings, which sets that target.'),
  h('The pitch and the wickets'),
  p('Two sets of stumps stand at either end of a flat strip called the pitch. The striker stands at one end and the bowler delivers from the other. The pitch is 20 metres in the stadium, 14 metres in the backyard and 15 metres on the beach.'),
  fig('stumps', 220),
  p('In the backyard modes a wheelie bin is the wicket, a little wider and taller than stumps: 0.31 m either side of centre and 0.95 m high, against 0.114 m and 0.71 m for stumps. The ball counts as hitting the wicket when it reaches it within those sizes, plus the radius of the ball itself.'),
  h('Overs and balls'),
  p('A delivery is one ball. Six legal deliveries make an over, and then a different bowler bowls from the other end and the batters swap ends. Wides and no-balls are not legal deliveries and are bowled again.'),
  h('Scoring runs'),
  p('Each completed run, with both batters reaching the opposite crease, scores 1. A shot that crosses the boundary after bouncing, or rolling, scores 4. A shot that crosses the boundary without bouncing scores 6. In the backyard the boundary is the garden fence: to score 6 the ball must clear the fence, which is 1.8 m high; a ball that hits the fence on the full or after a bounce scores 4.'),
  h('Run rate and required rate'),
  p('Run rate is runs scored per over so far. In a chase, required rate is the runs still needed divided by the overs still to bowl. If you are scoring faster than the required rate you are ahead.'),
  rule(),
  h('Ways to be out in this game'),
  p('Bowled: the ball hits the wicket. There is no LBW in this game, so a ball that hits your pad and would have hit the wicket is simply not out unless it actually hits the stumps or bin.'),
  p('Caught: a fielder holds the ball in the air before it bounces. The catch can fail: the chance depends on how hard and how high the ball is, how far the fielder had to run, and the opponent level.'),
  p('Run out: while batters are running, a fielder throws the ball to the stumps at the end a batter is heading to, and the batter has not yet reached it. A run that is not completed does not count.'),
  p('Not in this game: LBW, stumped, hit wicket and obstructing the field. Backyard Six-and-Out adds one house-rule dismissal, below.'),
  fig('ball', 150),
  h('Extras (stadium and full-match modes)'),
  p('Wide: a ball you do not swing at (and do not block) that passes more than 1.05 m from the stumps line, or higher than 2.05 m at the stumps. It adds 1 run and is bowled again. If you swing at it, it counts as a normal ball.'),
  p('No-ball: a ball that reaches the batter without bouncing and above waist height (above 1.12 m). It adds 1 run, is bowled again, and the next ball is a FREE HIT: you cannot be bowled or caught, only run out.'),
  p('Bye: if you miss or leave a ball that is not wide, there is a one in ten chance it slips past the wicket-keeper for 1 bye. There are no byes in the backyard modes.'),
  p('The backyard modes have no extras at all: no wides, no no-balls, no free hits and no byes.'),
  
  rule(),
  h('Batting: the swipe'),
  p('Swipe once the ball is released. Direction: the swipe angle is the shot angle on the field, measured from straight back over the bowler. Right is the off side, left is the leg side, past 90 degrees is behind square. For a left-handed batter (Settings) the picture is mirrored.'),
  fig('wheel', 300),
  p('Timing: the contact happens 0.05 seconds after your swipe starts. Compared with the moment the ball reaches the bat, within 0.032 s is PERFECT, within 0.07 s is GOOD, within 0.115 s is early or late, and within 0.165 s is an edge or a miss. The relaxed assist setting widens these by 40 percent and the sharp setting narrows them by 18 percent.'),
  fig('timing', 150),
  p('Hitting hard narrows the windows. The numbers above are for about a third of full power: with a gentle swipe they are 12 percent wider, at full power 22 percent narrower. A block has its own window, about 0.14 s either side.'),
  p('Early timing sends the ball toward the leg side, late timing toward the off side, by up to 28 degrees. Very early or very late is an edge toward the wicket-keeper and slips, or a miss.'),
  h('Batting: power and the air'),
  p('Power comes from swipe speed. A gentle drag is a push. Up to about half power the ball stays on the ground. Above that it climbs: about 11 degrees at 0.7, 21 degrees at 0.85 and 36 degrees at full power. Only a hard, well-timed hit near full power clears the stadium boundary. Hard hits also have a random sweet-spot: not every perfect swing is a six.'),
  p('Against a yorker a clean hit cannot rise more than about 9 degrees, and against a full ball about 17 degrees: you can only drive those along the ground. A mistimed hit rises more.'),
  h('Batting: reading the ball'),
  p('Every ball has an ideal shot. A ball wide of off wants a cut or cover drive to the off side, a ball on the pads wants a flick to leg, a short ball on the body can be pulled to leg, and a ball on the stumps can be driven straight. The closer your swipe is to the ideal angle the cleaner the contact.'),
  p('Balls above 2.2 m, more than 1.22 m outside off (1.4 m if you swing toward the off side) or more than 0.8 m down the leg side (1.05 m if you swing toward leg) are out of reach: swinging at them misses.'),
  h('Blocking and leaving'),
  p('A tap is a forward defence. If it is within about 0.14 s of the ball arriving it blocks the ball dead. A block cannot stop a ball above 1.6 m: it comes off the glove as an edge. Doing nothing leaves the ball: if it was going to hit the stumps you are bowled.'),
  rule(),
  h('The ball and the field'),
  p('Seven fielders, the wicket-keeper and the bowler are on the field in the stadium. The backyard has five fielders plus the keeper and bowler. Positions include slips and gully close to the bat, point, cover, mid-off, mid-on, midwicket and square leg in the ring, and deep fielders near the boundary.'),
  fig('field', 380),
  p('Fielders react after a short delay, then run at their own speed to intercept the ball on its real path. Slower opponents react later and run slower. A ball in the air below 2.3 m and above 0.45 m can be caught. A ball on the ground is stopped and picked up; very fast balls can be fumbled. A fielder who picks up the ball throws it to the end a batter is running to.'),
  p('Opponent captains change the field between overs: attacking with slips early, defensive and spread late, and they move a fielder toward the zone where you keep scoring boundaries. The bowler also bowls away from the zones you score in.'),
  h('Running between the wickets'),
  p('The RUN button appears once the ball is hit. Tap to start a run; tap again while running to queue one more; tap again to cancel it. The batters run at 7.4 metres a second. A run is completed when both reach the opposite crease. The first call takes about 0.1 s to react, and a turn costs about 0.16 s.'),
  fig('run', 260),
  p('A throw takes 0.25 s to release plus the flight at 27 metres a second. A direct hit is more likely when the throw is short and when the opponent is stronger. A miss is taken by the keeper or bowler 0.3 s later. An overthrow, when the ball gets away, gives 1 extra run.'),
  p('If a ball is hit to the boundary it scores 4 or 6 straight away and the runs you were taking do not add to it. If you are caught, no runs count.'),
  rule(),
  h('Bowling (Full Match)'),
  p('Choose a delivery: Pace, Inswinger, Outswinger, Off-spin, Leg-spin, Bouncer, Yorker, Slower ball or Full toss. Drag the ring on the pitch to the spot where you want the ball to bounce: further from you is fuller, closer is shorter. Flick up to bowl: flick speed sets pace within the delivery type, and a faster ball is less accurate.'),
  fig('lengths', 260),
  p('Swing curves the ball in the air, spin turns it after it bounces. Bouncers climb at the body and above 2.05 m become wides. The batter is a computer batter whose skill depends on the level; it picks gaps in your field, so set a good one between overs.'),
  h('Match modes'),
  p('Premium Chase: bat second against a target in 5, 10 or 20 overs. Full Match: bowl five overs, then chase the total you gave away. Super Over: one over, two wickets, a tight target. Auto Play: watch a computer bat five overs.'),
  p('The target is the runs per over for the mode, scaled by the opponent level (Little Cousin lowest, Uncle Rod highest), plus a small random variation. You win by reaching the target, lose by being bowled out or running out of overs, and tie by finishing exactly one run short.'),
  h('Backyard house rules'),
  p('Classic Backyard: tennis ball, bin wicket, garden fence boundary, fewer overs and wickets, no extras.'),
  p('Tippy-Go: any contact with the bat, even a block or an edge, and you must run. Fielders can run you out, so a soft tap is a gamble.'),
  p('One-Hand One-Bounce: a ball caught with one hand after one bounce is out, as well as one caught on the full.'),
  p('Six-and-Out: you score the 6 but you are out, because the ball is lost over the fence. This rule applies only in this mode.'),
  h('Opponent levels'),
  p('Little Cousin: loose bowling, slow fielders, easy catches, a lower target. The Neighbour: honest bowling and a sensible field. Big Brother: tight lines, smart fields, quick fielders. Uncle Rod: every trick, every gap closed, the highest target.'),
  h('Think and Auto Play'),
  p('Think gives three hints per innings. Before a ball it names the delivery and the best gap; while running it says whether the run is safe. Auto Play thinks for 5 seconds by default (2 to 10, in Settings), shows its choice for 2 seconds, then acts. Pause freezes everything; resume continues exactly where it stopped.'),
  h('Daily Innings and records'),
  p('Daily Innings gives every player the same target on the same day. The game keeps your best score for each mode on your device.'),
  gap(6),
];
